### ISSUE TITLE
Allow pubic field promotion for Record types

### ISSUE THREAD

**Issue by Zekfad** [dart-lang/language#3336] opened 2023-09-10 11:13 UTC
Every Record types in dart are read-only and user have no control over Record interface.
So it's impossible to override record field, therefore I think they should be eligible for promotion.

For example:
```dart
typedef R = ({ int? val, });

void test(R r, R? r2) {
  if (r.val != null) {
    // promote to int, so no need for null assertion
    print(r.val.sign);
  }
  if (r2?.val != null) {
    // promote both r2 to R and val to int
  }
}
```

**Comment by rrousselGit** [comment] 2023-09-10 11:43
Would that mean you could upcast the record itself?

```dart
void fn((int,) record) {}

void maybeFn((Object?,) record) {
  if (record.$1 is int) {
    fn(record); // (Object?,) is now assignable to (int,)
 }
}
```

If so, that'd be quite cool.

Currently to do that we'd have to use type matching against the entire object:

```dart
void maybeFn((Object?,) record) {
  if (record is (int,)) {
    fn(record);
 }
}
```

But that can be tedious as records get more properties.

**Comment by munificent** [comment] 2024-01-18 01:34
I think this is a duplicate of #2503.

**Closed by munificent** 2024-01-18 01:34 UTC
Labels: request
