### ISSUE TITLE
Possible bug? foo["a"]="b" results in TypeError, even if foo is a Map<String,dynamic>

### ISSUE THREAD

**Issue by sloisel** [dart-lang/language#892] opened 2020-03-23 20:29 UTC
I think I understand why this "bug" happens but it was so baffling, my head did a couple of turns like in the exorcist when it happened. Consider this code:

```
Map fixprobset(Map<String,dynamic> P) {
  if(!P.containsKey("name")) {
    P["name"] = (P["tileset"] as List<String>).join(" ");
  }
  if(P.containsKey("children")) {
    final Q = P["children"];
    for(var k=0; k<Q.length;k++) Q[k] = fixprobset(Q[k]);
  }
  return P;
}
```

One would expect the parameter `P` to be of type `Map<String,dynamic>`, since that's what it says right there, but sometimes `P.runtimeType` is, e.g. `Map<String,List<String>>` and then the line `P["name"]=...` results in a baffling run-time TypeError. By abusing `Map<String,dynamic>.from()` and friends, I was able to get around this but it seems like a crazy way to do things. It was even more bizarre in my case because, by adding one field to my data structure, whichever map was getting runtimeTyped to Map<String,List<String>>, was instead correctly typed as Map<String,dynamic>, which was getting around the real problem here, which is that the compiler ignores my type declaration in the parameter list of the function.

Here's a gist:

https://dartpad.dev/d041fe1d97bf1f6a378a45bc81cb4f28

**Comment by leafpetersen** [comment] 2020-03-23 23:03
Dart 2 generics are unsoundly covariant for historical reasons, with the consequence that errors like the above are only caught at runtime.  There's a proposal to add sound variance to Dart.  You can see some of the concrete proposals linked from [here](https://github.com/dart-lang/language/issues/213), and an article about the declaration site variance proposal [here](https://medium.com/dartlang/dart-declaration-site-variance-5c0e9c5f18a5), written by my intern from last fall who implemented this in several of our tools.

Since this is (somewhat unfortunately) working as intended at the moment, I'm going to close this out in favor of the existing issues linked above.

**Closed by leafpetersen** 2020-03-23 23:03 UTC
Labels: bug
