### ISSUE TITLE
could support static extension?

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/language#3921] opened 2024-06-19 03:37 UTC
```dart
class Foo {
  String name = "aa";
  static String prop = "bbb";
}

static extension FooExt on Foo {
  void aaa() {
    print(prop)
  }

  static bbb() {
    print("sss")
  }
}

main() {
  Foo.aaa(); // prints bbb
  FooExt.bbb();  // prints sss
}

```

**Comment by Wdestroier** [comment] 2024-06-19 17:02
It's a duplicate of #723, but it's already in the [language funnel](https://github.com/orgs/dart-lang/projects/90)!

The `static` modifier before the `extension` keyword would mean all members are static, I guess. Can we remove it?

```dart 
extension FooExt on Foo {
  aaa() => print(prop)
  static bbb() => print("sss")
}
```

**Comment by lrhn** [comment] 2024-06-19 19:33
I'm closing this as a duplicate of #723. The syntax suggested here isn't better, I'd rather have `static extension ...` be a normal extension where static members are *also* available on the target type (which must be a type that can have statics).

**Closed by lrhn** 2024-06-19 19:33 UTC
Labels: feature
