### ISSUE TITLE
callable class don't implement call interface

### ISSUE THREAD

**Issue by tarno0se** [dart-lang/language#272] opened 2019-03-17 16:56 UTC
```
abstract class Base {
  void f();
}

class Callable {
  void call() {}
}

class A implements Base {
  var f = Callable();//error: Class 'A' can't define field 'f' and have method 'Base.f' with the same name.
}
```

**Comment by eernstg** [comment] 2019-03-18 08:16
This repository is used for discussions about the design of the language Dart (that is, future developments of Dart as such). If you detect some issue with the existing implementation of Dart then it should be reported [here](https://github.com/dart-lang/sdk/issues). So I'll close this issue because it doesn't fit in this repository.

However, the behavior that you describe is as intended: It is not possible to implement a method `f` by declaring an instance variable named `f`: The latter introduces a getter and a setter into the interface of the class, and not a method. There is no way you can implement `Base` if you have a field named `f`, so this is an error.

**Closed by eernstg** 2019-03-18 08:16 UTC

**Comment by tarno0se** [comment] 2019-03-18 20:44
> This repository is used for discussions about the design of the language Dart

Yes, this is a language design problem.

> However, the behavior that you describe is as intended: It is not possible to implement a method f by declaring an instance variable named f: The latter introduces a getter and a setter into the interface of the class, and not a method. There is no way you can implement Base if you have a field named f, so this is an error.

Сallable class has method semantics. This code is logically correct.


```
class Callable {
  void call() {}
}

class A {
  var f = Callable();
}

void main() {
  A().f();//f is callable
}

```

**Comment by tatumizer** [comment] 2019-03-18 21:21
@tarno0se : Callable has nothing to do with it
```
abstract class Base {
  void f();
}

void foo(){}
class A implements Base {
  var f = foo;//error: Class 'A' can't define field 'f' and have method 'Base.f' with the same name.
}
```
You will get the same error. If you are wondering why, write a message to me and I will explain

**Comment by tarno0se** [comment] 2019-03-19 04:57
> Callable has nothing to do with the effect you observed.

I know. Dart has a design error. What he shows now - unimportant.

> You will get the same error. If you are wondering why, write a message to me and I will explain

```
abstract class Base {
  void f();
}

void foo(){}
class A implements Base {
  var f = foo;//error: Class 'A' can't define field 'f' and have method 'Base.f' with the same name.
}
```
A.f field implements Base.f logically. Just like getter/setter implements data field.

```
abstract class Base {
  int field;
}

class A {
  int get field => 0;
  set field(int value) {}
}

```

**Comment by leafpetersen** [comment] 2019-03-19 05:06
This is a design choice that was made a long, long time ago, way back when in Dart 1.  It's not something we're likely to change now.  I can appreciate the arguments for a more property based approach, but for better or worse, that's not the approach that Dart takes.

**Comment by tatumizer** [comment] 2019-03-19 12:35
@tarno0se : my question to you
```
abstract class Base {
  void f();
}

void foo(){ print(this); } // what "this" means here?
class A implements Base {
  var f = foo;
}
new A().f();  // foo is invoked indirectly
var q = foo(); // foo is invoked
```
We have 2 invocations of foo here. What would it print in each case?
Imagine the assignment `var f = foo` making foo a method of the class. Then certainly it should have an access to other methods/fields in the class, so it needs "this". Can you see the problem here?

**Comment by tarno0se** [comment] 2019-03-19 14:27
> We have 2 invocations of foo here. What would it print in each case?
> Imagine the assignment var f = foo making foo a method of the class. Then certainly it should have an access to other methods/fields in the class, so it needs "this". Can you see the problem here?

This is not related to the topic. There is no need to change language semantics to solve my problem.

> // what "this" means here?

Error. Using "this"(in methods) is optional. Function without using "this" without any problems turns into a method.

**Comment by tatumizer** [comment] 2019-03-19 16:00
@tarno0se : this would erase the distinction between the fields of functional type and the methods, where the latter have access to "this" while the former don't, so the distinction would still remain. It was not a design error, but a design decision to draw this distinction clearly. I believe it was a right choice, and you are certainly entitled to an opposite opinion, but qualifying it as an error would not be a correct characterization of the situation IMO :)

**Comment by tarno0se** [comment] 2019-03-20 03:44
> this would erase the distinction between the fields of functional type and the methods

Not. You said nonsense.

```
abstract class Base {
  void f();//require callable!
}

void foo(){}
class A implements Base {
  var f = foo;//callable
  f() {}//callable
  var f = CallableClass;//callable
}
```

Callable is what can be called. This may be a method. Maybe a field.

**Comment by leafpetersen** [comment] 2019-03-20 03:46
Folks, this is digressing into a fairly specific one-on-one discussion, and this forum really isn't intended for that.  Can you please take it offline?
