### ISSUE TITLE
Function Overloading

### ISSUE THREAD

**Issue by CXCubeHD** [dart-lang/language#1522] opened 2021-03-14 13:29 UTC
A small but important language feature that dart is missing that you can not overload functions!

In almost every other language you can overload a function, but not in Dart! Even Java has that! (Not counting C)

I think that the term function overloading is pretty self-explanatory:

```cs
void Say(String text) => print(text);
// In dart you can't make a function with the same name and different parameter types
void Say(int i) {
    print("Number: $i");
}

void Main() {
    Say("Hello World");
    Say(10);
}
```

This is a small language feature that really needs to be in dart!

Also the compiler should priotize the more "suitable" type.

**Comment by mateusfccp** [comment] 2021-03-14 13:42
Duplicate of #1122.

**Comment by lrhn** [comment] 2021-03-15 11:16
Indeed a duplicate.

**Closed by lrhn** 2021-03-15 11:16 UTC
Labels: feature
