### ISSUE TITLE
Why are non-nullable types allowed for optional parameters in abstract methods?

### ISSUE THREAD

**Issue by jmewes** [dart-lang/language#2676] opened 2022-12-01 05:56 UTC
## Observed

In the Dart language specification there is a code example with an abstract class that has a non-nullable type as optional parameter:

```dart
abstract class B {
  foo([int i]);
}
```

See [14efbe8/specification/dartLangSpec.tex#L3318-L3320](https://github.com/dart-lang/language/blob/14efbe8/specification/dartLangSpec.tex#L3318-L3320)

## Expected

The signature of optional parameters in abstract methods should not allow non-nullable types for optional parameters.

Instead, it should require the usage of nullable types for optional parameters:

```dart
abstract class B2 {
  foo([int? i]);
}
```

## Diagnostics

Implementations of `B#foo` using nullable types are valid, using Dart SDK 2.18.5:

```dart
abstract class B {
  foo([int i]);
}

class C extends B {
  @override
  foo([int? i]) {
    throw UnimplementedError();
  }
}
```

Implementations of `B#foo` using non-nullable types are invalid:

![invalid](https://user-images.githubusercontent.com/5235584/204976587-e40d4b7b-9168-499b-9b77-d712e3eb194b.png)

**Comment by mateusfccp** [comment] 2022-12-01 09:28
When providing an optional parameter, it's mandatory that you also provide a default value that is going to be used if no argument is provided.

In the case of nullable parameters it's also true, but with the difference that the language assumes `null` as the default if you do not specify it.

For non-nullable parameters, assuming `null` is an error, as, obviously, `null` is not a valid argument to the parameter. Hence the error.

You can still explicitly provide a non-null default argument.

```dart
void foo([int bar = 10]) {}
```

**Comment by eernstg** [comment] 2022-12-01 14:13
I'll close the issue because the situation is handled as intended.

**Closed by eernstg** 2022-12-01 14:13 UTC
Labels: bug
