### ISSUE TITLE
Inline if assignment instead of ternary operator with null else branch

### ISSUE THREAD

**Issue by petrnymsa** [dart-lang/language#1714] opened 2021-06-29 13:24 UTC
## Use case
Many times in Flutter I've found myself writing conditional rendering using ternary operator where "else" branch returns null.

For example, a custom Widget has a parameter that will set some property of the nested widget or even add another widget to the tree. 

Within `Column` or `Row` (or whenever we use array `[]`) it is possible to use `if statement`, however elsewhere I am forced to use ternary operator where else does nothing other than returning null.

1. Example  - simple conditional parameter:

```dart
BoxDecoration(
    gradient: gradientColors != null
        ? LinearGradient(
            colors: gradientColors!,
          )
        : null,
)
 ```

2. Example - Suppose I have some default `Scaffold` widget with shared settings and I can pass `drawerBuilder` to add a drawer to that Scaffold

```dart
return Scaffold(
      resizeToAvoidBottomInset: true,    
      ... // more shared settings etc...
      body: Padding(
        padding: padding,
        child:  ...., // shortened
      ),
      drawer: drawerBuilder != null
          ? Builder(builder: (context) => drawerBuilder!(context))
          : null,
    );

```

## Proposal
Probably this request will need support from dart-lang itself.  I am coming from React background and in JS / TS is possible to use `&&` operator for such inline rendering without an explicit `else` branch. E.g, example 2 could be rewritten into 

```dart
return Scaffold(
      drawer: drawerBuilder != null &&  Builder(builder: (context) => drawerBuilder!(context))l,
    );
```

It is maybe just personal preference, but I found this more clear than cluttering `: null` with a ternary operator.

**Comment by eernstg** [comment] 2021-06-29 15:17
@petrnymsa, note that this issue might be a duplicate of other proposals, or at least similar.

In particular, https://github.com/dart-lang/language/issues/361 proposes `a !! b` meaning `a == null ? null : b`, so you could do this:

```dart
...
BoxDecoration(
    gradient: gradientColors !!
        LinearGradient(
          colors: gradientColors!, // `!` only needed if `gradientColors` is not a local variable.
        ),
)
```

[This comment](https://github.com/dart-lang/language/issues/1039#issuecomment-646511428) mentions some other proposals in the same area.

**Comment by petrnymsa** [comment] 2021-06-30 07:29
> @petrnymsa, note that this issue might be a duplicate of other proposals, or at least similar.
> 
> In particular, #361 proposes `a !! b` meaning `a == null ? null : b`, so you could do this:
> 
> ```dart
> ...
> BoxDecoration(
>     gradient: gradientColors !!
>         LinearGradient(
>           colors: gradientColors!, // `!` only needed if `gradientColors` is not a local variable.
>         ),
> )
> ```
> 
> [This comment](https://github.com/dart-lang/language/issues/1039#issuecomment-646511428) mentions some other proposals in the same area.

Thanks! I've tried to find similar issues as I was nearly sure there should be already some discussion about this topic, but failed to found it :) 

Feel free to close this issue in favour of  #361

**Closed** 2021-06-30 07:52 UTC
Labels: feature
