### ISSUE TITLE
Referencing `Record` from "legacy" code.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#2661] opened 2022-11-28 12:00 UTC
The record specification states, under "Interactions with libraries using older language versions", that:

> It is an error for the identifier `Record`, denoting the `Record` class from `dart:core`, where that import scope name is only imported from platform libraries, to appear in a library whose language version is less than *v*.

That requires the front end to remember where a name is imported from, which (AFAIK) it currently doesn't. If there is no conflict between imports, all it needs to remember is which declaration is imported, not which path it took to get there.
This will require checking each import for whether it includes the `Record` class in its (non-hidden) export scope, and if so, whether that library is a platform library, and if not to mark that import as special in the importing library (not just if there is a conflict, because the library might not import `dart:core`).

Further, it only mentions the *identifier* `Record`, but doesn't mention qualified identifiers like `prefix.Record`. 
It's not clear whether it should be an error to have:
```dart
import "dart:core" as p;
p.Record? x;
```
(It probably should, for consistency, but it's up for interpretation whether the spec covers it or not, and I'd probably say it doesn't as written.)

It's not entirely clear what we are trying to achieve with this restriction.
There are still plenty of ways to get the `Record` type, or any record type, into a legacy library type: going through a type alias, by inference, or through type parameters With inference and type aliases, the type is just as much part of the library as if it had been written explicitly, but we don't try to prevent that.

The only thing we prevent is code explicitly and directly referring to a library name which doesn't exist in the earlier SDK that the library is written for.
We have lots of other such SDK library declarations, which doesn't exist in all SDK versions, and all we've done for the rest are adding annotations like `@Since("2.17")` to the declarations, and intended that the analyzer will some day give warnings based on that. 
It seems unnecessary to introduce extra protection just for the `Record` type, especially if it needs special code and state to implement it in the front end. We didn't do that for `Never` introduced in SDK 2.12, pre-2.12 code can easily refer to the `Never` declaration. (It works like `Null`, but `Record` works like some arbitrary subclass of `Object` too to code which doesn't know what records are).

Using library code that isn't available for your (claimed) minimal supported SDK is a general problem. Special-casing this particular class into the language specification, and doing it only partially (there are many ways to circumvent the issue), suggests to me that this feels more as a heuristic warning than a language design feature. It should probably be left to the analyzer to give such a warning.

@johnniwinther

**Comment by johnniwinther** [comment] 2022-11-28 12:01
cc @chloestefantsova

**Comment by leafpetersen** [comment] 2022-11-28 16:24
> It's not entirely clear what we are trying to achieve with this restriction.

It should be clear, we discussed it at length in the pull request where this landed.  I think the phrasing is yours.  :)

> We have lots of other such SDK library declarations, which doesn't exist in all SDK versions, and all we've done for the rest are adding annotations like `@Since("2.17")` to the declarations, and intended that the analyzer will some day give warnings based on that.

This is just going to have to be one of those places where we don't see eye to eye.  Record is implemented in the SDK - it cannot be implemented in Dart.  The fact that the implementations choose to put a fake class in the core libraries to point to when the built in type `Record` is referenced is an implementation detail.  So the fact that we do something different with `Record` from real Dart code which we implement in the core libraries is no more relevant than the fact that `Object` also has various special errors and warnings associated with it.

> There are still plenty of ways to get the `Record` type, or any record type, into a legacy library type: going through a type alias, by inference, or through type parameters With inference and type aliases, the type is just as much part of the library as if it had been written explicitly, but we don't try to prevent that.

Yes, we don't prevent that, because it is not problematic.

> and doing it only partially (there are many ways to circumvent the issue),

I don't understand what you are saying here.  How do you circumvent the issue (where the issue is understood to be preventing someone from using the `Record` type in legacy code without an explicit or implicit dependency on a language version which supports it)?

> feels more as a heuristic warning than a language design feature

I don't follow you here.  In what way is this heuristic?  I think it entirely and correctly captures what we are trying to achieve.

**Comment by lrhn** [comment] 2022-11-28 22:25
We are trying to achieve is that it's impossible to access the `Record` type unless at least one library in your program has a language version of at least *v* (where we introduce the feature). No without `dart:mirrors` at least.

It's still not something we've done for other types or features that have been added to the platform libraries over time, which also only work if you use a new enough SDK. I'm not seeing the big benefit of special casing `Record`. Sure, it stops someone from writing code that doesn't work on old SDKs, but there are so many other ways to do that which we don't try to stop. If you write Dart 2.9 code which references `Never`, it won't compile on a 2.9 SDK, but we don't stop you from doing it.
It feels, to me, like something the analyzer should warn about, not something baked into the language for every compiler until we drop support for pre-3.0 code (if we ever do that). It just doesn't feel worth the complexity.

(I don't see `Record` as being any more special of a `class` than `int`, `String` or `Function`. There is nothing in `Record` that can't be implemented in `Dart` other than being sealed, and we are working on that. It is defined as a supertype of all record types, but that's a property of the record types, nothing special is needed of `Record` itself. Just like `Function` for function types. It doesn't have to be special like `FutureOr`, it can actually just be a (sealed) class).

**Comment by leafpetersen** [comment] 2022-11-29 00:08
> If you write Dart 2.9 code which references `Never`, it won't compile on a 2.9 SDK, but we don't stop you from doing it.

This was an oversight, as we discussed at the time.  It was released accidentally.

> There is nothing in `Record` that can't be implemented in `Dart` other than being sealed, and we are working on that.

How exactly do I as a user write a type which is a supertype of an infinite family of structural types in Dart?  Asking for a friend.... :)  We're just never going to see eye to eye here.  We've had this discussion many times before.  My position remains the same. The `Record` class (like `int` and `String` and `Object` and `Function` - please show me how to write `Function.apply` in Dart code?) is **built into the subtyping rules of the language**.  Its definition is part of both the static and the dynamic semantics of the language.  Its behavior arises not from the source code in the core libraries, but from text in the specification which tells the implementations how to interpret it in the compilers, runtimes, and static analysis tools.  There is no way for a user to write a type which integrates into the static and dynamic semantics in that way.  I don't know what else to say.  If you believe that this is not the case, then feel free to remove the references to it from the relevant parts of the specification and replace them with the appropriate Dart code in the core libraries.  :)

Nitpicking aside, I'm not strongly wedded to this error if it makes things difficult for the implementations.  I'm fine with removing it from the specification and making it tool specific, or just dropping it.

**Comment by munificent** [comment] 2022-11-29 01:50
> Nitpicking aside, I'm not strongly wedded to this error if it makes things difficult for the implementations. I'm fine with removing it from the specification and making it tool specific, or just dropping it.

For what it's worth, I don't care much about this corner of the feature either. If it makes things easier to have `Record` be visible to legacy libraries, I'm fine with it. If it makes things easier to have `Record` *not* be visible to legacy libraries, I'm fine with that too.

**Comment by lrhn** [comment] 2022-11-29 12:28
My main worry here is that it's more complicated for the front-end than necessary, for what I consider a fairly low benefit. Baking it into the language semantics means that we can't just leave it to the analyzer to figure out when best to make it a warning. We have to specify the precise rules, which locks us into those rules, even if there might be something *better* to do (heuristically).

The work needed by the front-end seems, to me, to be (at least):

* For each import clause in a pre-records-release-version (pre-*v*) library, check if it imports the declaration `Record` from `dart:core` (exported by the imported library, not hidden/un-showed).
* If so, check if the import URI is a platform library URI (`dart:*`)
* If so, mark that imported name as "bad" in some way. (This may require extra state that we don't currently have.)

If any (possibly qualified) identifier resolves to a "bad" import name, make it a compile-time error with an error saying that `Record` cannot be accessed from a library with language version \< *v*.

It might be possible to piggy-back on conflicted import errors in some way, since triggering an error only when the library actually refers to the identifier is what we already do for conflicts. It's like treating `Record` as conflicting with itself if one of the imports goes through a non-platform library. (And with a different error message, but complications that only happen in case of errors is better than complications on the valid code path.)

If any other declaration with name `Record` is also imported (into the same scope), it takes precedence over the platform declaration, and the platform libraries will not expose any other declaration named `Record`, so at least we don't need to worry about the `Record` declaration also being part of a normal import conflict.

We probably should also prevent a pre-*v* library from exporting `Record`, otherwise an entirely-pre-*v* program can get to `Record` anyway. We can just make it an error, but if someone ever does `export 'dart:core` hide Symbol;`, they would get broken by that.
It might be better to simply remove `Record`-from-`dart:core` from the export scope of a pre-*v* library, if it somehow ends up there.
(Mainly hypothetical, nobody re-exports `dart:core`. I could see someone doing that, while replacing the implementations of `DateTime` and `Stopwatch`, in order to mock timing, but I doubt that's the approach anyone will take in practice..)

**Alternative**

Maybe we could reduce the complexity for the front-end.

Tweak the rules so the front-end doesn't need to care about the path at all:
* If a pre-*v* library contains a (possibly qualified) identifier which resolves to the declaration `Record` from `dart:core`, it's a compile-time error. It doesn't matter *how* it's re-exported, even if it's re-exported through a post-*v* library. The declaration itself is off-limits to pre-*v* code.
* This should probably also include using the name `Record` in a `show` clause which ends up denoting the declaration from `dart:core`. (Don't know about `hide`, we don't usually make it an error to hide things which don't exist.)
* Still can't export it either. Remove it from the export scope. (Or not, it can still only be used by post-*v* libraries, so it's not that important.)

That should only require special-casing when resolving the identifier `Record` to the `Record`-from-`dart:core` declaration. No extra state is needed in the library import logic, to remember *how* the record type was imported.

It should still catch any accidental references to `Record` from pre-*v* code.

It won't make it as *easy* for someone to deliberately introduce `Record` into a pre-*v* library. They can't just export it, so it's not a one-liner. It's still a two-liner if they really want it:
```dart
//@dart=3.0
import "dart:core" as core;
typedef Record = core.Record;
```

It seems *to me*, as a non-front-end-developer, that this functionality might be semi-simple to implement. Still more logic on every identifier lookup (to check if the identifier is `Record`), but it's localized, and doesn't change import logic in any way.

Maybe even simple enough that it should be something we can *generalize* and use again for other names in the future.

**Comment by leafpetersen** [comment] 2022-11-30 06:02
I'm fine with either doing no checking, or doing the simpler alternative @lrhn proposes.  I'd suggest we just go with no checking.

**Comment by munificent** [comment] 2022-12-01 00:22
SGTM. Removed the restriction.

**Closed** 2022-12-01 00:22 UTC
Labels: records
