### ISSUE TITLE
Type aliases: Typedefs for non-function types 

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/language#65] opened 2018-10-31 12:17 UTC
Realizes https://github.com/dart-lang/language/issues/66, [Feature specification](https://github.com/dart-lang/language/blob/master/accepted/2.13/nonfunction-type-aliases/feature-specification.md)

Sample typedef & usage:
```dart
typedef IntList = List<int>;
IntList il = [1,2,3];
```

Related issues: https://github.com/dart-lang/sdk/issues/2626

**Comment by eernstg** [comment] 2018-10-31 13:46
Specification CL at https://dart-review.googlesource.com/c/sdk/+/81414.

**Comment by eernstg** [comment] 2018-11-01 10:59
Feature specification proposal in [this PR](https://github.com/dart-lang/language/pull/75).

**Comment by eernstg** [comment] 2018-11-08 15:46
[PR](https://github.com/dart-lang/language/pull/88) created for the feature specification: One rule needs to be discussed, and the right thing to do is to say explicitly that no conclusion has been reached yet, with respect to that particular rule.

**Comment by leafpetersen** [comment] 2018-11-08 19:21
I opened an issue for discussion of the question of using typedefs where classes are expected [here](https://github.com/dart-lang/language/issues/89).

**Comment by leafpetersen** [comment] 2018-11-28 23:31
I think we need to update the spec to reflect the consensus on static method access.

**Comment by eernstg** [comment] 2018-11-30 10:41
Landed https://github.com/dart-lang/language/pull/116 for that.

**Comment by georgelesica-wf** [comment] 2019-07-08 17:12
I perused the spec, but I didn't see an obvious answer. How will the analyzer handle this?

```{dart}
typedef IntList = List<int>;
IntList il = [1,2,3];
List<int> li = il; // potentially problematic
```

Presumably that would be either a warning or an error, correct? What about this one (building on the code above)?

```{dart}
void foo(IntList a) {}
List<int> b = [1,2,3];
foo(b); // potentially problematic
```

In this case it isn't clear that `b` is intended to be an actual `IntList`, so allowing the call to `foo` might introduce a bug. On the other hand, I suspect that quite a few people would want to do this without an explicit cast for the sake of convenience.

**Comment by eernstg** [comment] 2019-07-08 17:54
`List<int>` and `IntList` is the same type, just different spelling, so there should not be a problem with this example: Inference should make `[1,2,3]` mean `<int>[1,2,3]` and the initialization of `li` is fine. Same situation with `foo(b)`.

**Comment by georgelesica-wf** [comment] 2019-07-08 18:35
But someone might change the definition of `IntList`, and if the piece of data in question was never really intended to follow `IntList` in the first place, a call like the second one in my comment shouldn't be allowed in that case. In other words, everything might type check accidentally.

For example, the second call to `foo` here won't compile because I've declared `b` to be an `int`, but not necessarily a `MyInt`.

```go
package main

type MyInt int

func foo(a MyInt) {
    println(a)
}

func main() {
    var a MyInt = 0
    foo(a)
    var b int = 0
    foo(b)
}
```

**Comment by rrousselGit** [comment] 2019-07-08 18:41
That's not the same thing. 
This feature doesn't create a new type, it just makes an alias.

```
typedef Foo = int;

void main() {
  print(int == Foo); // true
}
```

**Comment by georgelesica-wf** [comment] 2019-07-08 18:42
OK, that's really what I was curious about. Thanks for clarifying!

**Comment by rrousselGit** [comment] 2019-11-05 12:14
Would this include:

```dart
typedef Test<T> = T Function();

typedef Test2 = Test<int>;
```

?

Currently, this code does not compile, for no obvious reason. This is very limiting if we have anything more complex than `T Function()`.

**Comment by eernstg** [comment] 2019-11-05 12:41
The 'typedefs for non-function types' feature has not yet been implemented. It will happen, but the efforts to support other features (especially extension methods and non-nullable types) have left no resources available for this feature, so it's been postponed for a while.

This means that we only have the kind of type alias that does not support non-function types: The [grammar rule](https://github.com/dart-lang/language/blob/e208d99dd67aa800ee80d8bf1531221683c06094/specification/dartLangSpec.tex#L16840) requires a `<functionType>` on the right hand side of `=`.

That makes `typedef Test2 = Test<int>` a syntax error (actually, no tool is required to tell which compile-time errors are syntax errors and which ones are "other" compile-time errors, but it must be a compile-time error of some kind). 

When this feature is implemented it will certainly be possible to have declarations like `typedef Test2 = Test<int>;`.

In any case, there should not be any particular limits on the complexity of the types that you define a given type alias to denote (neither with the current type alias feature, nor with the generalization that supports `= <type>` rather than `= <functionType>`).

**Comment by shinayser** [comment] 2019-11-07 14:34
One question about this proposal: 
If I define an extension function on a type alias, it will be available to the 'aliased' type? Like:

```dart
typedef IntList = List<int>;

extension on IntList {
   doSometing();
}

var listOfItens = [1,2,3];

listOfItens.doSomething(); <-- It will be available?
```

**Comment by rrousselGit** [comment] 2019-11-07 15:04
That's how it already works with extensions on functions, so likely.

```
typedef VoidCallback = void Function();

extension on VoidCallback {
  void foo() {}
}

void main() {
  void Function() test = () {};

  test.foo();
}
```

**Comment by shinayser** [comment] 2019-11-07 15:15
> That's how it works already with extensions on functions, so likely.
> 
> ```dart
> typedef VoidCallback = void Function();
> 
> extension on VoidCallback {
>   void foo() {}
> }
> 
> void main() {
>   void Function() test = () {};
> 
>   test.foo();
> }
> ```

Wow thats bad to hear 😢
If it was not available, we could create fake class inheritance =/

**Comment by rrousselGit** [comment] 2019-11-07 15:19
But that's not a typedef anymore. That's a new type
Your request may be part of #546.

**Comment by LuisDev99** [comment] 2019-12-21 20:15
Hello! Any news on this feature? Also, Merry Christmas to everyone in advanced ;)

**Comment by TheMisir** [comment] 2019-12-26 08:45
I think lots of devs waiting for replacing `Map<String, dynamic>` with `JsonObject` 😄

```dart
typedef JsonObject = Map<String, dynamic>
```

**Comment by hepin1989** [comment] 2019-12-26 09:53
Just type list=List

**Comment by jodinathan** [comment] 2019-12-26 14:38
> I think lots of devs waiting for replacing `Map<String, dynamic>` with `JsonObject` 😄
> 
> ```dart
> typedef JsonObject = Map<String, dynamic>
> ```

true.
fully typing everytime ```Map<String, dynamic>``` is such a pain

**Comment by MrCreeper1008** [comment] 2019-12-27 04:07
Many devs are also waiting for union typedefs 😁

**Comment by eernstg** [comment] 2019-12-27 22:10
@LuisDev99 wrote:
> Any news on this feature?

Passing `--enable-experiment=nonfunction-type-aliases` on a bleeding-edge compiler (esp. dart2js) should allow you to verify that something is going on (most likely: it crashes). It's not working, but it's moving, which is an improvement over the situation a few months back. And Merry Holidays to all, of course! ;-)

**Comment by zl910627** [comment] 2020-01-24 05:15
How would i use ` --enable-experiment=nonfunction-type-aliases` on Flutter?

**Comment by eernstg** [comment] 2020-01-24 13:24
@zl910627 wrote:
> How would i use `--enable-experiment=nonfunction-type-aliases` on Flutter?

Flutter has its own version of each tool, so in general you may not be able to get the same features as you do with the plain Dart tool chain. It is probably not worth the trouble to try to cheat Flutter into working with the bleeding edge version of a tool.

**Comment by fzyzcjy** [comment] 2020-01-29 06:40
Also it would be great for use cases such as

```
typedef UserId = int;
```

**Comment by eernstg** [comment] 2020-01-29 14:41
You can do `typedef UserId = int;`, but it won't give you a new type, it gives yet another name to an existing type. We'd need some other mechanism if you want to make the new type distinct (e.g., such that `int x = 1; UserId id = x;` would be a compile-time error.

**Comment by porfirioribeiro** [comment] 2020-02-12 15:01
> Also it would be great for use cases such as
> 
> ```
> typedef UserId = int;
> ```

What you are asking is nothing related with typedef's but with inline classes
Kotlin does this: https://kotlinlang.org/docs/reference/inline-classes.html
At compile time you get a representation and UserId != int, but at run-time t disappears and only int exists

**Comment by eernstg** [comment] 2020-02-12 17:20
Right, Kotlin inline classes are similar to Haskell `newtype` in a couple of ways, and they are both intended to provide a new (assignment incompatible) type, with zero representation overhead at run time.

(Kotlin inline classes don't actually guarantee the zero cost property in all situations, because there will be a wrapper object at run time in the case where an expression whose type is an inline class is used where some other type is required, cf. lines where 'boxed' occurs [here](https://kotlinlang.org/docs/reference/inline-classes.html#representation).)

We have discussed similar mechanisms for Dart, under names like 'views' or 'view classes', or 'extension types'.

**Comment by fedotxxl** [comment] 2020-03-26 10:26
Hello. This feature was requested 8 years ago. I'm especially interested in `typedef Foo = int;` because it makes code much cleaner (practiced it in web development). Are you going to implement it and release it? Do you have any plans/timelines and so on?

**Comment by eernstg** [comment] 2020-03-26 11:16
Until December 2019 we did not work on it. I did some work on it before the holidays, and I just restarted working on it yesterday. (Most of the time is taken by null-safety issues these days.) So there's hope. ;-)

**Comment by Levi-Lesches** [comment] 2020-03-26 19:27
Nice! Any timelines for either of them (doesn't have to be official, just a general idea of what's going on)?

**Comment by eernstg** [comment] 2020-03-26 22:26
Wow! ;-)

Bleeding edge plus https://dart-review.googlesource.com/c/sdk/+/141240 runs 35 out of 37 test files (containing about 500 different usages). But one non-trivial one is still missing, e.g.:

```dart
typedef T<X, Y> = Map<Y, List<X>>;

void main() {
  Map<int, Iterable<String>> xs = T.fromIterables([], []);
}
```

Inference should complete this the initializing expression to `T<String, int>.fromIterables(<int>[], <List<String>>[])`, but that is currently not inferred (it just pretends that there is no context type, and uses default type arguments).

**Comment by eernstg** [comment] 2020-03-27 08:18
Important caveat: The ongoing work on non-function type aliases targets the common front end. A similar effort is needed with the analyzer, and then there are some additional targets like the IntelliJ plugin, github code highlighting, etc. Things take time..

**Comment by TheMisir** [comment] 2020-03-27 08:43
What if we could use C++ preprocessor inside dart.

```dart
#define JMap Map<String, dynamic>
#define UserId int
```

Using msbuild we can run preprocessor by: `cl /P file.dart`. But I don't know how to automate this.

**Comment by eernstg** [comment] 2020-03-27 10:04
Note that the preprocessor approach could allow for passing type arguments from one type alias to another (using a non-standard syntax for passing type arguments), but there would be no support for performing inference on terms using a type alias (it's just a preprocessing-time error to omit the type arguments).

**Comment by Levi-Lesches** [comment] 2020-03-27 15:54
I suppose all the work being done is to get Dart (and the analyzer) to recognize an alias as an official type, but honestly for now, I would settle for just a pre-processing script that copy-and-paste the new type _before_ passing it to the analyzer or compiler (even if the alias name won't show up).

**Comment by jodinathan** [comment] 2020-03-27 16:19
I needed this quite some time ago and now it just happened how good it would be if Dart had it back then.

I've figured out that ```Map<String, Object>``` suites better for my project instead of ```Map<String, dynamic>```. 
I may be wrong, but it seems to be less error prone and also ```Object``` can have extension methods.

This changing would be easier if I had a ```Pair``` typedef

**Comment by rhbrunetto** [comment] 2020-04-07 16:04
Any news on this feature? Any timelines?

I'd really appreciate being able to use it.
Is there anything we could do to help?

**Comment by DoubleHub** [comment] 2020-04-08 00:02
I prefer using typedef instead of #define, solely because the # looks ugly on a language that doesn't heavily use # besides C/C++. But also because it reminds me of how evil macros are

**Comment by eernstg** [comment] 2020-04-08 12:24
@rhbrunetto wrote:
> Any news on this feature? Any timelines?

Several bugs fixed since [this comment](https://github.com/dart-lang/language/issues/65#issuecomment-604719462), still missing: Inference.

**Comment by OBorce** [comment] 2020-04-09 18:25
@eernstg are you implementing the whole thing by yourself?

**Comment by eernstg** [comment] 2020-04-14 19:32
Yes. Everybody (including me) is mainly working on null-safety, but we wanted to get non-function type aliases moving as well, so I started working on it. Hope to make some progress this week again. ;)

**Comment by brianschardt** [comment] 2020-04-18 06:47
Thanks @eernstg! We all appreciate this work!

**Comment by artob** [comment] 2020-05-21 08:22
@eernstg Glad to see this is being implemented!

I'll mention a use case that nobody noted as yet: since Dart's FFI doesn't (https://github.com/dart-lang/sdk/issues/36140) have any support for C's standard variable-sized integer types (`int`, `long`, `size_t`, etc.), it would be tremendously helpful to be able to conditionally (at compile time) define type aliases to the effect of, for example, `CLong` being a typedef for either `Int32` or `Int64`.

From the discussion here so far, I understand that the right-hand side of a typedef probably won't support a conditional expression in the initial implementation. Perhaps that might be possible to work around with using [conditional imports](https://dart.dev/guides/libraries/create-library-packages#conditionally-importing-and-exporting-library-files) to enable the FFI use case?

**Comment by AKushWarrior** [comment] 2020-06-18 04:13
Now that NNBD is in technical previews, is this at the top of the figurative to-do list?

**Comment by mateusfccp** [comment] 2020-06-18 09:39
> Now that NNBD is in technical previews, is this at the top of the figurative to-do list?

This is already being implemented, just be patient.

**Comment by AKushWarrior** [comment] 2020-06-18 14:00
> > Now that NNBD is in technical previews, is this at the top of the figurative to-do list?
> 
> This is already being implemented, just be patient.

I understand, but @eernstg had noted earlier in the issue that the main priority of the Dart team was NNBD and related work. I was just asking if that time has been freed up now.

**Comment by mateusfccp** [comment] 2020-06-18 14:41
> > > Now that NNBD is in technical previews, is this at the top of the figurative to-do list?
> > 
> > 
> > This is already being implemented, just be patient.
> 
> I understand, but @eernstg had noted earlier in the issue that the main priority of the Dart team was NNBD and related work. I was just asking if some of that time has been freed up now.

Well, NNBD is at an advanced stage, IIRC its expected to be released in a few months. I don't know if this feature will be ready until then, but I'm sure that if not, as soon as NNBD is release @eernstg will have more time to work on this, so I don't expect this to delay.

**Comment by leafpetersen** [comment] 2020-06-18 21:06
Great to see enthusiasm for this feature, it's picked up quite a few upvotes since I last checked it!  We're definitely on the downhill track for null safety but we're still pretty heavily in the thick of rolling that out.  I don't think we can make any promises about timeline for this feature, but we are still cautiously optimistic that we'll be able to get back to it soon.  Thanks for the patience.

**Comment by konkontos** [comment] 2020-09-03 06:59
Newcomer to Dart & Flutter here, still learning the ropes.
I was pretty amazed when I found out I could not do something as simple (and essential) as :

`typedef JSONObj = Map<String, dynamic>;`

I'm using this sort of thing regularly e.g., in my Swift code.

Just upvoted this - let's hope it gets implemented soon.

**Comment by tomasdev** [comment] 2020-09-13 22:19
> Great to see enthusiasm for this feature, it's picked up quite a few upvotes since I last checked it! We're definitely on the downhill track for null safety but we're still pretty heavily in the thick of rolling that out. I don't think we can make any promises about timeline for this feature, but we are still cautiously optimistic that we'll be able to get back to it soon. Thanks for the patience.

Any more updates @leafpetersen ?

**Comment by leafpetersen** [comment] 2020-09-15 02:06
I hate to be vague, but I also hate to dangle promises that I'm not sure I can keep.  Sorry! :}  This is still pretty much the top of the queue of small features that we'd like to ship soon, but we don't have a concrete ship date yet.

**Comment by eernstg** [comment] 2021-02-08 15:44
Still no concrete shipping date, but the analyzer implementation is complete (thanks, @scheglov!). Still missing is support in IntelliJ, `dartfmt`, and several other tools. But we're definitely getting closer.

**Comment by awkj** [comment] 2021-03-07 03:52
If I had this, then I would write `typedef string = String `in the first place

**Comment by ragokan** [comment] 2021-03-12 17:34
It is an amazing feature, and usages are really a lot.

```dart
typedef IntList = List<int>;
IntList il = [1,2,3];
```

Usages like this and more complex usages will help a lot, do we know anything about its release date?

**Comment by creativecreatorormaybenot** [comment] 2021-03-12 19:07
```dart
typedef IntList = List<int>;
IntList il = [1,2,3];
```

To be honest, I think that is the worst possible example 😂

**Comment by Levi-Lesches** [comment] 2021-03-12 19:54
One of the more popular examples would be Json: 
```dart
typedef Json = Map<String, dynamic>;

class User {
  final String name;
  final int age;

  User.fromJson(Json json) : 
    name = json ["name"],
    age = json ["age"];
  
  Json get json => {
    "name": name, 
    "age": age,
  };
}
```

**Comment by Levi-Lesches** [comment] 2021-03-12 19:57
@eernstg 
> Still no concrete shipping date, but the analyzer implementation is complete

Wait, if the compiler and analyzer both support this, can it theoretically be partially released now with proper tooling later?

**Comment by TheMisir** [comment] 2021-03-12 20:18
> ```dart
> typedef IntList = List<int>;
> IntList il = [1,2,3];
> ```
> 
> To be honest, I think that is the worst possible example 😂

I remember when I write pascal I had to use `StringList` because it doesn't supported templates (aka: generics).

**Comment by TheMisir** [comment] 2021-03-12 20:24
> One of the more popular examples would be JSON:
> 
> ```dart
> typedef Json = Map<String, dynamic>;
> 
> class User {
>   final String name;
>   final int age;
> 
>   User.fromJson(Json json) : 
>     name = json ["name"],
>     age = json ["age"];
>   
>   Json get json => {
>     "name": name, 
>     "age": age,
>   };
> }
> ```

Since json objects can be also arrays and dart doesn't supports union types like List<dynamic> | Map<string, dynamic> why we're not using dynamic for storing json data? Don't take it serious, i'm myself using Map<String, dynamic> and using DTOs on higher level layers.

**Comment by Levi-Lesches** [comment] 2021-03-12 20:28
You're right, in other instances I do use Lists. But the way I tend to structure my data, everything is a class in a Map, or a list of such maps. So when I have a list, it usually ends up being passed into `User.fromJson` one by one, hence the Maps everywhere. Personally, I feel that types are not a big issue when it comes to JSON, since it's either `Map<String, dynamic>` or `List<dynamic>`. Once you determine if it's a list or a map, you're pretty much done. 

Also, am I the only one who does 
```dart
Json get json => { };
```
instead of 
```dart
Json toJson() => { };
```
It feels like every example I see has the latter, but I find getters to be so much cleaner.

**Comment by jodinathan** [comment] 2021-03-12 20:47
> You're right, in other instances I do use Lists. But the way I tend to structure my data, everything is a class in a Map, or a list of such maps. So when I have a list, it usually ends up being passed into `User.fromJson` one by one, hence the Maps everywhere. Personally, I feel that types are not a big issue when it comes to JSON, since it's either `Map<String, dynamic>` or `List<dynamic>`. Once you determine if it's a list or a map, you're pretty much done.
> 
> Also, am I the only one who does
> 
> ```dart
> Json get json => { };
> ```
> 
> instead of
> 
> ```dart
> Json toJson() => { };
> ```
> 
> It feels like every example I see has the latter, but I find getters to be so much cleaner.

I guess it is common to set a local var to function calls while a getter is often called multiple times.

**Comment by TheMisir** [comment] 2021-03-12 20:55
You can also write something like that if you want to sacrifice code cleaniness for 1ms preformance improvement:

```dart
Json _json;
Json get json => json ??= <String, dynamic>{
  ...
};
```

It will cache json value in `_json` field which will not require rebuilding Map on each usage.

**Comment by eernstg** [comment] 2021-03-12 21:38
This feature is really near to completion now. A useful example could be a type alias that encapsulates a certain regularity in the use of an existing type:

```dart
typedef MapToList<X> = Map<X, List<X>>;

void main() {
  MapToList<int> m = {};
  m[7] = [7];
  m[8] = [2, 2, 2];
  for (var x in m.keys) {
    print('$x --> ${m[x]}');
  }
}
```

The point is that `MapToList<X>` allows us to specify `int` just once, and then the standard form `Map<int, List<int>>` is implied, and that will compute the second type argument to the map literal `{}` implicitly.

**Comment by Levi-Lesches** [comment] 2021-03-14 06:39
Thanks for all your hard work on this feature! Dart is special in that it pays so much attention to the little things.

**Comment by bernaferrari** [comment] 2021-03-26 17:34
A wild commit appeared yesterday! It seems this will be released with Dart 2.13!

https://dart-review.googlesource.com/c/sdk/+/192948

**Comment by Levi-Lesches** [comment] 2021-03-26 19:04
Thanks for that! 

There's a great example in the CHANGELOG that is probably worth repeating -- deprecating classes. 

Let's say you have this: 
```dart
class BadName { /* some methods */ }
class OtherLibraries extends BadName { }
```
So you want to rename `BadName`, but that's a breaking change since other people depend on them. Well, you can safely deprecate it by doing this: 
```dart
class BetterName { /* some methods */ }  // changed the original

@Deprecated("Use BetterName instead")
typedef BadName = BetterName;
```
Now, all classes that extend `BadName` will cotinue to work, but will show a warning. When it's time for the breaking change, simply remove the `typedef` and keep everything else the same.

**Comment by leafpetersen** [comment] 2021-03-30 04:33
> A wild commit appeared yesterday! It seems this will be released with Dart 2.13!
> 
> https://dart-review.googlesource.com/c/sdk/+/192948

Heh - can't keep anything from you guys.  :)  Just to manage expectations a bit... I haven't landed that patch yet, and there's still a non-zero (but hopefully small) chance that we won't make the branch cut date for 2.13.

**Comment by creativecreatorormaybenot** [comment] 2021-03-30 06:29
It does not change a lot when it will be released in the new future in my mind @leafpetersen 

In my mind, considering that the feature has been finished in most places (according to https://github.com/dart-lang/sdk/issues/44951) and the fact that we should be aware of the standard release cycle, we should not have any different expectations in the first place ;)

**Comment by shinayser** [comment] 2021-05-19 19:19
Why this issue stills open? 😁😁😁

**Comment by eernstg** [comment] 2021-05-19 19:21
You're right, done!

**Closed by eernstg** 2021-05-19 19:21 UTC
Labels: feature

**Comment by Levi-Lesches** [comment] 2021-07-22 02:38
Now that I actually want to use this feature (with JSON types, surprise surprise), I came across a problem: Where do I actually _put_ the typedef?

In my Flutter app, I have this file structure: 
```
|- lib
   |- data.dart -- exports everything in src/data
   |- src 
      |- data
         |- a.dart
         |- b.dart
         |- c.dart
```

If I want classes `A`, `B`, and `C`, each in their respective files, where should I put the `Json` alias? Seems like a lot of overhead to add a `json_alias.dart` file just for that.

**Comment by munificent** [comment] 2021-07-22 22:57
> Seems like a lot of overhead to add a `json_alias.dart` file just for that.

I would probably do this.

**Comment by Levi-Lesches** [comment] 2021-07-23 01:22
Okay, thanks for the recommendation, I'll do that.

**Comment by Zabadam** [comment] 2021-07-24 06:34
> @Levi-Lesches 
> Now that I actually want to use this feature (with JSON types, surprise surprise), I came across a problem: Where do I actually _put_ the typedef?

If you will be using more typedefs, a suggestion would be an encompassing root-level `typedefs.dart`; it doesn't need to be exported. 

I have seen a lot of packages that would, in your scenario, have a `src/data/common.dart` solution as well, importing `common`into each `a`, `b`, and `c`.

**Comment by creativecreatorormaybenot** [comment] 2021-07-24 11:23
> If you will be using more typedefs, a suggestion would be an encompassing root-level typedefs.dart; it doesn't need to be exported.

I would disagree here. If you do this, you completely lose separation of concerns for different layers.

Take Flutter as an example, see https://github.com/flutter/flutter/tree/master/packages/flutter/lib/src. Here you can see the different libraries Flutter has to separate between different layers. It would be the worst option to put all typedefs into a root-level file. And since I expect most large-scale projects to be structured similarly in one way or the other, I think this is not good advice.

**Comment by lalomartins** [comment] 2021-07-24 12:28
Folks, this is all very interesting but Github bug comments are not the right space for it.

**Comment by fanthus** [comment] 2021-08-03 08:53
I tried this feature in IntelliJ dart plugin , like it still not support.

**Comment by eernstg** [comment] 2021-08-03 09:05
@fanthus, if you wish to report an issue with the IntelliJ plugin and non-function type aliases, please create an issue with 'area-intellij' and give more details.

**Comment by esenmx** [comment] 2021-08-28 12:02
Can it be possible to get the name of typedef instead the underlying runtimeType in future?
```dart
typedef Meaning = int;

final Meaning life = 42;

void main() {
  print(life.runtimeType); // could print 'Meaning' instead 'int'
}
```

**Comment by creativecreatorormaybenot** [comment] 2021-08-28 12:41
@esenmx The way you describe it, it is a new type rather than alias. I guess the problem is that `extends String` does not work, but it is not an alias if you can switch on it.

**Comment by esenmx** [comment] 2021-08-28 13:42
@creativecreatorormaybenot yea, I just mimicked typedef-switch case, it looks kinda unreasonable, a new type creation stands inevitable.
