### ISSUE TITLE
Promote to non-null based on null-checking a conditional member access

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/language#1602] opened 2021-04-15 18:23 UTC
* Dart SDK 2.12.2
* Reproducible in DartPad on Chrome

Consider the following snippet:

```dart
abstract class Identifier {  
  Uri? get moduleUri;
}

void f(Identifier? id) {
  if (id?.moduleUri != null) {
    print(id.moduleUri);
  }
}
```

Currently the `id.moduleUrl` within the body of the if statement produces an error:

```
line 7 • The property 'moduleUri' can't be unconditionally accessed because the receiver can be 'null'.
Try making the access conditional (using '?.') or adding a null check to the target ('!').
```

The expression `id?.moduleUri != null` can only be true if `id` is non-null. Could the compiler/analyzer perform this type flow analysis in order to promote `id` to a non-null type within the if statement?

**Comment by eernstg** [comment] 2021-04-26 16:39
You'd need the getter `moduleUri` to be stable (a feature proposed in #1518), otherwise the second evaluation of `id.moduleUri` could return null. But if `moduleUri` is stable then `id.moduleUri` could also be a stable expression, and it would work.

**Comment by leonsenft** [comment] 2021-04-26 18:00
> You'd need the getter `moduleUr`i to be stable (a feature proposed in #1518), otherwise the second evaluation of `id.moduleUri` could return null.

Right, I guess this isn't a great example since it would still fail to compile even if `id` were promoted. Consider this change:

```dart
abstract class Identifier {  
  Uri? get moduleUri;
}

void f(Identifier? id) {
  if (id?.moduleUri != null) {
    print(id.moduleUri!);
  }
}
```

This better highlights my point as it still doesn't compile. Again, for the body of the `if` statement to be entered, `id` must be non-null, yet you get a compile error that `id` could be null.

**Comment by leafpetersen** [comment] 2021-04-27 00:21
I believe this is a duplicate of https://github.com/dart-lang/language/issues/1224 .

**Closed by leafpetersen** 2021-04-27 00:21 UTC
