### ISSUE TITLE
derived type is not a subtype of base type

### ISSUE THREAD

**Issue by MinuteReversal** [dart-lang/language#2233] opened 2022-05-12 01:09 UTC
function cast input parameter type to base type error
```dart
import 'package:flutter_test/flutter_test.dart';

class A {} //base type

class B extends A {} //derived type

typedef FNI<T extends A> = void Function(T); //input parameter function
typedef FNR<T extends A> = T Function(); //return value function

void main() {
  ///derived type is not a subtype of base type
  testWidgets('function cast (input parameter/return value) type to base type',
      (WidgetTester tester) async {
    A a1 = A();
    A a2 = B(); // OK
    // B b1 = A(); // error
    B b2 = B();

    ///input type cast
    FNI<A> fn1 = (A a) {};
    FNI<A> fn2 = (B b) {} as FNI<A>; // error! why?
    FNI<B> fn3 = (A a) {}; // success! why?
    FNI<B> fn4 = (B b) {};

    ///return type cast
    FNR<A> fn5 = () => A();
    FNR<A> fn6 = () => B();
    // FN2<B> fn7 = () => A(); // error
    FNR<B> fn8 = () => B();

    expect(a1, isA<A>());
    expect(a2, isA<A>());
    // expect(b1, isA<A>());
    expect(b2, isA<A>());

    expect(fn1, isA<FNI<A>>());
    expect(fn2, isA<FNI<A>>());
    expect(fn3, isA<FNI<A>>());
    expect(fn4, isA<FNI<A>>());

    expect(fn5, isA<FNR<A>>());
    expect(fn6, isA<FNR<A>>());
    // expect(fn7, isA<FN2<A>>());
    expect(fn8, isA<FNR<A>>());
  });
}
```

**Comment by eernstg** [comment] 2022-05-12 09:19
This is working as intended. The important point to note is that function types contain types of parameters, and they are contravariant (that is, when checking a subtype relation, they must have the opposite relation). For example:

```dart
// From the given example.
FNI<A> fn2 = (B b) {} as FNI<A>; // error! why?

// This is what it means:
void Function(A) fn2 = (B b) {} as void Function(A);
```

The problem is that `void Function(B)` is _not_ a subtype of `void Function(A)`, so the dynamic cast fails.

The reason why parameter types are contravariant is that this is what we must have in order to ensure soundness. In particular, if the static analysis says that a given function has type `void Function(A)` then you can pass an instance of `A` as an argument to that function, but if it is actually a function of type `void Function(B)` then it must raise a type error at run time because it needs a `B` but received an `A` (and an `A` is not a `B`).

So we can't allow an expression of type `void Function(A)` to have a value of type `void Function(B)`, so we can't allow that subtype relationship to exist.

Swap `A` and `B`, and the whole thing works out&mdash;so the opposite subtype relationship _does_ exist.

**Comment by mraleph** [comment] 2022-05-12 10:55
To expand on what @eernstg has written: it is sometimes helpful to think about these things using some real-world category, e.g. instead of `A` and `B` you could use `Animal` and `Cat`. 

In such terms it should become clear why a `void Function(Cat)` is not assignable to `void Function(Animal)`.  The second signature implies that the function can deal with any type of an animal (e.g. passing a `Dog` into it is a valid thing to do), but the first function can only deal with cats - so it's an error to try using it in such a context.

Similarly it becomes clear that `Animal Function()` is not assignable to `Cat Function()` because the second signature promises that the function would produce only `Cat`s, but the first function can produce any animal (e.g. a `Dog`).

**Comment by eernstg** [comment] 2022-05-12 11:27
Thanks, @mraleph! I'll close the issue because everything discussed here is working as intended.

**Closed by eernstg** 2022-05-12 11:27 UTC
Labels: request

**Comment by MinuteReversal** [comment] 2022-05-13 02:25
OK I see, thanks a lot.
