### ISSUE TITLE
Inference Enhancements - Generic Class Functions 

### ISSUE THREAD

**Issue by D10100111001** [dart-lang/language#888] opened 2020-03-19 02:46 UTC
It is really annoying to work with some limitations on the inference related to the dart language. Coming from C# and TypeScript and other typed languages it has always been easy to get good inference. This is related to #731. 

Here is an example:

```dart
import 'package:flutter/material.dart';

class TreeView<T> extends StatelessWidget {
  const TreeView(
      {Key key,
      @required this.items,
      @required this.childFn,
      this.childSelector})
      : super(key: key);

  final List<T> items;
  final Widget Function(T item) childFn;
  final List<T> Function(T item) childSelector;

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Column(
        children: items.expand((item) => _buildItem(item)).toList(),
      ),
    );
  }

  List<Widget> _buildItem(T item) {
    return [
      childFn(item),
      if (childSelector != null)
        ...childSelector(item)
            .expand((childItem) => _buildItem(childItem))
            .toList()
    ];
  }
}

```

![image](https://user-images.githubusercontent.com/25810618/77026486-c10fbe00-6961-11ea-9e35-5fe5986eeea1.png)

> (new) TreeView<AppComponent> TreeView({Key key, List<AppComponent> items, Widget Function(AppComponent) childFn, List<AppComponent> Function(AppComponent) childSelector})

The IDE is able to infer and show the correct tooltip regarding the component definition but the dart analyzer does not agree. If it isn't clear, essentially the analyzer is unable to infer to the type and it falls back to dynamic and I have implicit dynamic disabled.

![image](https://user-images.githubusercontent.com/25810618/77027525-79d6fc80-6964-11ea-9743-0453795807cc.png)

> Missing parameter type for 'item'.
> Try adding an explicit type like 'dynamic', or enable implicit-dynamic in your analysis options file.dart(implicit_dynamic_parameter)

Is there a timeline on when this will be implemented? I see the referenced issue was created in 2016.

**Comment by leafpetersen** [comment] 2020-03-19 04:55
Sorry, can you elaborate a bit?  There are certainly known limitations to the inference we currently do, including the one you reference, but I don't see anything in the code that you included above that we shouldn't be able to infer, and if I test it out I haven't been able to find any dynamic code in it (I may be missing something).  The IDE snippets you included seem to refer to different code?  There is something odd in the error message you listed:

> `(new) TreeView TreeView({Key key, List items, Widget Function(AppComponent) childFn, List Function(AppComponent) childSelector})`

That suggests that `childSelector` is returning `List<dynamic>` which is not the case in the snippet you sent: in that code, it is returning `List<T>`.

Can you verify that the issue you are seeing does in fact occur in your reproduction, and point out exactly where in the code you're seeing dynamic?  Also, can you include the sdk version that you're seeing this in?

**Comment by D10100111001** [comment] 2020-03-19 15:54
@leafpetersen I have created a minimal reproducible example (MRE): https://dartpad.dartlang.org/c8b6d45927b383810bfeef7151416ca0

**Comment by leafpetersen** [comment] 2020-03-19 21:03
Thanks, yes your MRE is exactly an instance of #731 .  I do hope to address this in a future language update, but since it is breaking to change inference (even if to improve it) it's not a trivial thing to do.  I don't have an ETA on when this will bubble to the top of the queue, sorry!

**Comment by mraleph** [comment] 2020-03-20 10:56
@leafpetersen should this just marked as duplicate of #731?

**Comment by leafpetersen** [comment] 2020-03-20 16:18
@mraleph I believe so, yes.  @D10100111001 if there are any issues here not covered by #731 feel free to re-open.

Duplicate of #731

**Closed by leafpetersen** 2020-03-20 16:18 UTC
Labels: request
