### ISSUE TITLE
proposal: immutable types - take 1

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/language#225] opened 2019-02-15 17:34 UTC
This is the sketch of the proposal to introduce immutable types.
This material is based on discussion in https://github.com/dart-lang/sdk/issues/27755
I tried to integrate the ideas from different contributors into a (hopefully) coherent whole, without inventing much of my own.
This design is supposed to be applicable to any type, but to sound less abstract, I will use List as an example.

The idea: introduce 2 operators with the following pseudocode:

```
operator ^(list) => list is immutable ? list : createImmutableCopy(list)
operator ^^(list) {
  if (list is mutable) {
    render list immutable (by sealing or somehow);
  }
  return list;
} 
```
In addition, we define View\<T> to target use cases not covered by ^. The conjecture is that 3 operations: (^, ^^ and creating a View), used as "building blocks", are enough to cover most (or all?) scenarios and expectations of who can modify what and who can see what changes. (I can't prove the "all" part, it might be even wrong, but I believe we will be closer to the general solution regardless). 

Operator ^^ is unusual, it changes the operand, but it's not unprecedented: operator ++x does the same, hence the choice of 2 symbols ^^ to emphasize the analogy. 

Immutable type is denoted as ^List.
Let 
  - someList - the list compiler knows nothing about,
  - listKnownToBeImmutable - statically proved to be immutable
  - listKnownToBeMutable - statically proved to be mutable

Then
```
^List im1 = someList; // statically OK, but may fail in runtime if someList is mutable (see \*)
^List im2 = ^someList; // OK, may create an immutable copy if someList is mutable
^List im3 = ^^someList; // always succeeds, no copies necessary, but someList also becomes immutable
^List im4 = listKnownToBeImmutable; // OK, no copies
^List im5 = ^listKnownToBeImmutable; // OK, no copies, ^ is redundant (warning?)
^List im6 = ^^listKnownToBeImmutable; // OK, no copies, ^^ is redundant (warning?)
^List lm7 = listKnownToBeMutable; // static error (see \*)
^List im8 = ^listKnownToBeMutable; // creates immutable copy
^List im9 = ^^listKnownToBeMutable; // renders operand immutable and assigns to im9

List l1 = someList; // always OK
List l2 = ^someList // like im2 above
List l3 = ^^someList; // like im3 above
// the rest is obvious
```

(\*) to make transition of existing code base easier, the rule has to be relaxed: TBD.

Class View\<T> is a generalization of UnmodifiableListView, applicable to all classes; view has the same interface as ^T. Used in cases where the callee agrees to not modify the list, but is ready to correctly take into account the changes made by the owner dynamically. The distinction is important enough to warrant a different class. This class is viral, but the use cases for it must be rare.

The design is 1) not viral 2) not breaking

EDIT: interesting math trivia here: 
- ^View\<T> = ^T. That is, operation "^"  applied to a view can be defined as "copy a snapshot of a View, and get a real ^T".
- View\<^T> = ^T (obviously)

**Comment by eernstg** [comment] 2019-02-15 17:47
Note the potential overlap with #125 and #117.

**Comment by tatumizer** [comment] 2019-02-15 17:59
@eernstg : please advice how to proceed. On one hand, when there are 2 proposals already, the third one doesn't look as defiant: it's just the N-th proposal where N happened to be equal to 3. On the other hand, some consolidation would be helpful to prevent N from growing uncontrollably. :)

**Comment by tatumizer** [comment] 2019-02-15 19:27
IMO, #125 is rather complicated, targets different use case, does not necessarily solve the problem in Flutter (the only massive motivating environment we have), viral - in other words, it's not apples-to-apples comparison.
#117 *asks* for a method to simplify the creation of immutable objects, which is exactly what the above is trying to achieve.

I think the road starting from Flutter and leading to generalizations (which we did collectively in the discussion) is more practical. But again - it may, or may not, be an answer to all possible problems.

**Comment by eernstg** [comment] 2019-02-18 15:36
@tatumizer wrote:
> .. how to proceed.

I just wanted to make sure that we don't have a lot of threads on similar topics without creating some connections between them. The point is that we should avoid too much redundancy, and we should be aware of possible synergies, but I wasn't implying that these particular topics would necessarily be merged in any specific manner! ;-)

**Comment by yjbanov** [comment] 2019-02-19 05:54
> IMO, #125 is rather complicated, targets different use case, does not necessarily solve the problem in Flutter (the only massive motivating environment we have), viral - in other words, it's not apples-to-apples comparison.

I'm afraid if we add language features to satisfy one use-case at a time we will quickly find ourselves with a very big language with features doing same things slightly differently, i.e. a very confusing one.

I think #125 is a good starting point to discuss how it can cover as many use-cases as possible without making the proposal unwieldy. BTW, sharing data across isolates is not as different from the Flutter mutation issue (https://github.com/dart-lang/sdk/issues/27755) as it may seem. In both cases the fundamental issue is concurrent modification of shared data.

**Comment by tatumizer** [comment] 2019-02-19 14:42
This is not "one use case". You can cover many use cases by using ^T and ^^T and View as building blocks. Everything around us is built from simpler parts after all.
The problem, as I see it after many years of participating in these online discussions, is that you guys have a chance to discuss everything IRL. The personal presence and rhetorical skills play a large role in these discussions. If you want to convince somebody, you need to *talk*. If you want to better understand somebody's arguments, you need to *listen* and ask questions. It works both ways. Writing doesn't cut it: short posts don't carry much information. Long posts won't be read by anyone. 
Ideas have an unfortunate property to be associated with personalities.
There's nothing can be done about it though.

**Comment by icatalud** [comment] 2020-01-03 20:18
The original post is missing an explanation of what is the problematic being addressed. As a newcomer I couldn't understand the proposal without referring to the linked issue.

If immutability is highly required in lists and maps, the problem could be addressed by adding a toImmutable() method. Its more transparent than adding a special operator.

Generalizing the solution to any object using a `Class View<T>` could be achieved with the request at #631 and generic implementations. There could be an `Immutable<T>` generic class that has a constructor that receives an object T and copies all the values from it.

**Comment by tatumizer** [comment] 2020-01-03 21:37
The idea is to be able to "seal" object dynamically thus making it immutable. It could be implemented by an extra bit in the object header. If someone tries to modify a sealed object - runtime exception is thrown. This is the minimum, and it might very well be the maximum that is worth addressing.
The syntactic form (operator `^^obj` or a method `seal(obj)`) is a secondary consideration.

Flutter is very sensitive to performance, so the main challenge is to avoid copying whenever possible.
If we just limit the scope by introducing a single method `seal(obj)`, which returns the same object with the "sealed" bit set, this feature alone is a good step forward IMO.

**Comment by icatalud** [comment] 2020-01-03 22:11
> if (list is mutable) {
    render list immutable (by sealing or somehow);
  }

That is the part that requires VM intromision. It only happens with ^^, ^ just copies.

It's a complex feature to seal in hot a non immutable object. It's inconsistent to have a basic native object that has and underneath special behavior depending on the operations applied to it previously. If the implications are important enough it can be justified. In this particular case I think it could be simpler to encourage developers to use immutable List as children which could be made direct with something like #117.

It must be clarified the performance impact that this would have for Flutter. What is the cost in performance to fix the problem they have by using the current language features? (copying the list might not be necessary)

**Comment by tatumizer** [comment] 2020-01-03 22:33
>  If the implications are important enough it can be justified

Yes, the implications are important enough.

This proposal is trying to go 1 step further and try to provide the generic solution to an issue of immutability (e.g. when the copying is in principle tolerable). Then you need to incorporate immutable types into the type system, and you absolutely need a coherent general idea for that. Sure, if all we wanted was a List, then we could be happy with just a single type UnmodifiableList, but in general, you can't introduce a parallel type UnmodifiableFoo for each Foo - you need some *concept*, plus corresponding notation.

**Comment by icatalud** [comment] 2020-01-03 23:53
> Yes, the implications are important enough.

Assertions need to be proven with evidence, in this case performance numbers (is this a bottleneck?).

> No, it's not that complex.

Complex is a subjective term. I meant complex in the sense that it adds uncommon behavior to a native type and it requires VM interference, particularly a special flag in list types. It also has a performance implication, because additional checks need to be done whenever writing in the list. If a secondary operation can be done, then it could be simpler to store a counter var in lists that adds one whenever there is a write operation (this value could take no space by using half of the bits of another field like length). That is even more versatile. But native basic types shouldn't have this kind of special behavior, advanced data structures should be used for that.

The Flutter issue could be an optimization on the lines of `const` that is suggested to the users. Other alternatives should also be tested, likes the one posted in [this comment](https://github.com/dart-lang/sdk/issues/27755#issuecomment-570726660).
Many people is creating lists on the fly inside the build methods, they do not store them in a variable, that is even more expensive. There is a number of stuff that people might be doing very inefficiently in their app but it's still no costly enough to be noticeable. There should be a list of suggested optimizations that users could follow and storing immutable lists of widgets should be one of them which can be performed easily with #117 which supplies the ^ feature.

**Comment by icatalud** [comment] 2020-01-04 02:52
Changing the mutability of the native List is wrong. It's not correct because it has implications that are too costly. It implies that modifying lists is no longer a safe operation and they should be try-catched if it is attempted to modify them after passing them to a function.

```dart
final x = [1,2,3]
foo(x);
x[0] = 2;    // analyzer warning
```

That is too much of special behavior, the inconvenience of it is too expensive. It's unfriendly specially to new developers who expect classic data structures to behave like classic data data structures. Lets say the analyzer treats this case specially and flags all functions that transform a list received as parameter into immutable, in which case it only warns when the function could set the immutability in the list. That is already a lot of special considerations and even then, the problem is still there for global scope lists. Global scope lists would always be warned to be try-catched, unless the analyzer followed the graph of the var usages and decided if it could have been set as immutable at some point. The logic for that truly becomes something absurd, if that kind of analysis is to be performed, then it should be performed first to infer final or const vars.

**Comment by tatumizer** [comment] 2020-01-04 03:08
Actually, the conventional name of this operation is not "seal", it's [freeze](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze)

**Comment by icatalud** [comment] 2020-01-04 05:04
Interesting feature, but there is an important considerations. JS is not static typed, it becomes naturally to do something like that, because in JS you can do anything with any object. For the same reason adding a feature to JS has no cost. Whatever comes to your mind is possible (all wishes become true). Static typed languages are constrained, the ideal would be to ensure correct functioning of the program straight from the static analysis. Of course in practice this is not possible, but the constraints attempt to approach that ideal. Concessions are made when its truly worth it. All the warnings from static analysis attempt to alert insecure operations. 

With that said, it's also true that any object can be hiding behind an interface, for example currently ImmutableList is passed as List and functions are clueless about this (unless they check), but functions are not clueless about the objects they generate themselves. Adding a frozen feature would truly be something novel, as it means that in Dart mutating an object that is passed to a function is no longer safe. Frozen-ability is severely impactful to the language and is it really worth it? This is supposed to be achievable through the means of interfaces and classes, which is exactly the case for immutable objects. Specialized classes can be created to achieve this and it is easily addressable by the receivers of the objects, they must simply define that they receive an object of such interface. By enabling default Frozen-ability to objects, all objects are inherently being constrained and not enhanced, what if it the wish is to have an object that cannot be frozen? The feature reverses that, a special non-frozenable object would need to be created. If the general most common usage benefits from fronzen-ability, then it becomes reasonable to revert this. In order for this to be worth it, classic data structures would need to benefit from this in the majority of the uses cases, but is there any evidence that supports that? It could be true, can't argue against that.

The case for flutter is that they should make widgets accept only ImmutableList, but instead they chose to accept any List. It's a design mistake, but ok not so much because in practice it would be inconvenient to be passing immutable lists. But that is why easy creation of immutable list should solve the problem. Flutter is also optimizing at the expense of reliability pushing for the creation of an unorthodox language feature to solve their design problem.

Even adding implicit frozen-ability only to default lists is something big, it must be proven worth it with facts (it must really be worth it, because there are plenty negative sides about it) and currently there is only one use case where the actual impact is unknown and there are reasonable alternative solutions which shouldn't be very expensive (which does not require accepting ImmutableList).

Implementing all the logic for frozen objects in the VM is interesting (not enabled by default, only special objects), but not even frozen interfaces currently exist, which suggests that is not a common pattern (patterns are sometimes created when the tools exists, that's true). In practice frozen-ability just like immutability only add to the readability and testing side, their are like implicit assertions, because the program would run equivalently without these types. Frozen types should exists first as special implementations and see how widely their usage becomes.

**Comment by icatalud** [comment] 2020-01-04 16:29
Frozen-ability is a useful feature, it could allow to convert any object that has non final members into a final one without requiring the creation of an additional special object. If this was incorporated in the VM as a flag, then they would be efficient. What I think is wrong is creating frozen-able objects by default.

Imagine objects can be declared like this:
```dart
var x = ^Foo()   // creates a frozenable object
x = ^^Foo()   // creates an already frozen object (immutable)
```

All objects by default can be declared in two versions, regular one and frozen-able ones. Then the feature becomes innocuous, whenever someone sees a declaration of an object with ^, they would go check the docs for the meaning of it. It must somehow be made easy to search, because it's non trivial to search for symbols in google or in the language tour (a word is direct to find).

Immutable would then become an extension of Fronzenable and Flutter could receive Frozenable objects. It's very easy then for the users to declare children lists, all that is requires is to prefix a ^ in the list declaration.

This is also useful for [this idea in #125](https://github.com/dart-lang/language/issues/125#issuecomment-570637286), it makes it easy to create sealed type var from any object where all their members are exposed instead of only the final members. By default if a reference is used in a sealed var `sealed x = y`, it automatically freezes the var (it must be of a frozen-able type or it's a runtime error).

If that feature existed and experience showed that in practice most people prefers frozen-able objects, then it could be decided to default objects to frozen-able types and create traditional object using a special notation (revert the situation).

**Comment by icatalud** [comment] 2020-01-06 15:03
It is always an enhancement to have frozenability in objects. But it must be a hidden interface from the default Object one, that’s why I couldn’t help but think it’s wrong.

**Skip this section until end skip mark, deliberation about the logic of wrong**

Types are the most important part of the documentation of a program. They express the interface that is going to be used for a given variable. This interface is specially relevant for mutation operations, but not so much for read-only which is innocuous. If a function receives a List, then it is expressing it can perform mutations on the list, because if it weren’t, then it would request for a ListView. It’s undeniable that this expressiveness is important information, it allows the user of the API to make assumptions about guaranteed behavior of the program without having to peek into the documentation or into the function body. If the program fails for any reason, it’s preemptively known that if a function received a ListView the problem could not be that the List was unexpectedly mutated inside the function. This is the great advantage of programming through interfaces, it is possible to infer a lot of behavior without reading a single line of documentation. On the same lines, if a function pretended to mutate an object by freezing it, then it’s undeniable that it would be beneficial that the function was explicit about this intention which means it should receive the frozen-able version of the type instead of the regular one. Under the context where it is accepted that static explicitness is the correct way to define functions when it comes to mutations, general frozenability in the standard object interface is wrong, because it is by default passing a mutation operation that is not being used. If most of the time frozenability was being used, then it would be correct to default it and ObjectView could exist to express that the mutable interface of an object is not going to be used. Under the context of dynamic typing where there are no interfaces general frozenability is correct.

If all objects are inherently freezable but this was hidden from the default interface, then it’s fine because analyzer warnings could catch whenever an object is being casted to their freezable type. A function that casts an object received as parameter to their freezable type would be a bad defined function in the same way it is wrong to define a Widget with mutable fields. This implies that it is always suggested against casting an object to its freezable type, so in practice a program that follows the instructions should only have freezable types that were defined from their origin to be freezable. But it is positive to leave the door open, because a subset of cases may call for a transgression of this ideal and besides it has the advantage of allowing to directly pass freezable types by using the regular constructor of a class. For example in Flutter placing children like `children: [w1, w2, ...]` is completely possible without adding any extra syntax if the framework received freezable List instead. Developers that defined a regular list and passed it to the children list would get analyzer warnings. That would be consistent.

How to make sense of this in the current Dart semantics? Ideas required here, `Object()` would have to be a factory constructor that actually instantiates a FrozenableObject, but that makes `super()` unviable in a class that extends Object unless a concession was made. Perhaps an option could be to transform the default Object constructor into an external constructor and assume that it is hiding the Frozenable interface.

**End skip**

Frozenability should be developed, it’s very useful that functions can declare that they are receiving objects that they pretend to own. These are the use cases of a parameter being passed to a function:

- Read and dropped (view)
- Read and kept (immutable)
- Mutated and kept (freezable)
- Mutated and dropped (classic)

Both cases in the middle are covered by freezable objects. With freezable objects, immutable types become simply an interface, because converting a freezable type into an immutable type is trivial. Freezable is an improvement over immutable because it allows creating immutable types by processing the data directly in the object and not creating a copy at the end. Sometimes the caller of the function might be fine with converting the existing instance into immutable. Freezable is a missing contract in function signatures that has existed in all static typed languages that at least I have used.

Perhaps you are right that it could generally be accepted that certain types like List or Map benefit in the majority of the cases from frozenablity. I cannot deny that many times functions receive native data structures as parameters and because it is unknown whether they will keep the reference (just like the Flutter case) I pass a copy just in case. Frozenability disambiguates this, if the function receives ClassicList it means it will mutate and drop the reference, if it receives List (freezable) it should be assumed it will be kept. That situation needs a deep examination.

**Closed** 2020-01-17 02:10 UTC
