### ISSUE TITLE
Allow referring to the type parameters of a generic class outside of the class scope

### ISSUE THREAD

**Issue by LongCatIsLooong** [dart-lang/language#3540] opened 2024-01-05 00:29 UTC
I have the following interface:
```dart
abstract class A<B extends Object> { }
```

I would like to be able to write:
```dart
class C implements A<int> { }

T.B someFunction<T extends A<num>>() { ... }

// `T` doesn't actually appear in the signature so it cannot be inferred.
final returnValue = someFunction<C>()
```
However currently one has to specify both type parameters, which makes calling the `someFunction` API a bit clumsy:
```dart

// `B` is used as the return type but otherwise redundant. 
B someFunction<T extends A<B>, B extends num>() { ... }

final returnValue = someFunction<C, int>();
// It gets worse when `A` has more than one type parameters, with long class names:
final returnValue' = someFunction'<C, SophisticatedClassName1, SophisticatedClassName2>();
```
### Proposal

Exposing the names of generic classes' type parameters, maybe as associated types:

```dart
abstract class A<B extends Object> {
  typedef B' = B;
}

T.B' someFunction<T extends A<num>>() { ... }
```

**Comment by lrhn** [comment] 2024-01-05 08:43
I'd suggest using type patterns (#170), preferably with a more actual-pattern-like syntax, to extract the type parameter of a generic type.

```dart
R someFunction<T extends A<final R>>() { ... }
```

It can use either the runtime type of the type `T`, and extract `R` on every runtime invocation, or use the static type of a single invocation point extracted (inferred) at compile-time (I'd prefer the former, that's what's currently impossible to do otherwise.)

I think this might just be a duplicate of #170, with slightly different syntax.

**Closed** 2024-01-05 08:55 UTC
Labels: request
