### ISSUE TITLE
Add static parse method for Enums

### ISSUE THREAD

**Issue by esDotDev** [dart-lang/language#1560] opened 2021-04-05 19:39 UTC
Currently it's repetitive and verbose when trying to accomplish simple tasks with Enum.

For example, I might have 
```
enum MenuType {
  home,
  search,
  trending,
  settings,
}
```

And I want to parse that into a query string so I have a link like "#/?menuType=search". 

If we look at Kotlin, C# or Swift, they both support this in a straight forward way:

Swift:
```
MenuType(rawValue: "search")
MenuType.search.rawValue // search
```

Kotlin:
```
MenuType.valueOf("search")
MenuType.search.toString() // search
```

C#
```
Enum.TryParse("Search", out MenuType enum);
nameof(MenuType.Search) // search
```

To do this in a highly readable way in dart we need to write boilerplate code for each Enum (and usually import a plugin).
```
extension MyEnumExt on MyEnum {
  String get name => describeEnum(this);
}
```

Parsing it the other way is something like: 
```
MenuType fromString(String value, List<MenuType> values, MenuType default) {
  try {
      return values.singleWhere((enumItem) => enumItem.name  == value);
  } on StateError catch (_) {
      return default;
  }
}
```

Ideally, this would be built into the language and just be as simple as: 
```
MenuType.parse("search") ?? MenuType.home;
MenuType.search.name
```
Adding `.name` addresses the toString use case (https://github.com/dart-lang/language/issues/1511) but fromString / parse is still cumbersome.

**Comment by esDotDev** [comment] 2021-04-06 05:03
Even with the help plugin we have to write this: 
```
enum SearchCategory {
  All,
  Popular,
}

extension on SearchCategory {
  String get value => describeEnum(this);
}

SearchCategory searchCategoryFromString(String? value) {
  return EnumToString.fromString(SearchCategory.values, value ?? "") ?? SearchCategory.All;
}
```

When we really just should need to write: 
```
enum SearchCategory {
  All,
  Popular,
}
```
The concrete downside to this are:
* Increased learning curve for new developers. Every single developer needs to memorize this boilerplate code at some pt. This feels like minutia to some degree. Would be nice if we could all just erase these workarounds from our mind / not teach them in the first place. 
* `searchCategoryFromString` does not support refactoring well, the enum class can easily get renamed without the fromString getting updated
* More verbose code examples everywhere enums are used, we can't discuss something simple like how to use an enum in the query string, without getting sidetracked into extension methods and external plugins.
* It contributes to the feeling that enums are a 2nd class citizen / afterthought in dart

**Comment by iamarnas** [comment] 2021-04-06 07:05
@esDotDev Hi,
I personally everywhere use Map they are so useful and flexible :)

```dart
enum UserStatus { online, offline }

var userStatus = <UserStatus, String>{
  UserStatus.online: "Online",
  UserStatus.offline: "Offline",
};

String userStatusToString(UserStatus status) {
  return userStatus[status];
}

UserStatus userStatusFromString(String status) {
  return userStatus.keys.firstWhere((key) => userStatus[key] == status);
}

// Status to String.
print(userStatusToString(UserStatus.online));
// Status from String.
print(userStatusFromString(userStatusToString(UserStatus.online)));

```

**Comment by esDotDev** [comment] 2021-04-06 08:10
Ah nice approach. But still lots of boilerplate, and if they would just give use proper value enums, you could write that like this!
```
enum UserStatus { online = "Online", offline = "Offline"}
...
print(UserStatus.online.value);  // -> Online
print(UserStatus.parse(UserStatus.online.value)); // -> UserStatus.online
```

Or even: 
```
enum UserStatus { online = 0, offline = 1}
...
print(UserStatus.online.value);  // -> 0
print(UserStatus.parse(UserStatus.online.value)); // -> UserStatus.online
```
But that is a bit off-topic maybe.

**Comment by cadaniel** [comment] 2021-04-06 15:08
I don't think a to/from string explictly are needed, but maybe enum values like Kotlin supports. 

https://kotlinlang.org/docs/enum-classes.html#implementing-interfaces-in-enum-classes

They can represent arbitrary types of data without needing to be string specific.

**Comment by esDotDev** [comment] 2021-04-06 15:48
Right, that would be great, something like:
```
MenuType.parse("all")
MenuType.all.value // all
```

It would still be nice to have implicit support for string based values, so we don't need to write: 
```
enum SearchCategory {
  all = "all",
  popular = "popular",
}
```

**Comment by cadaniel** [comment] 2021-04-06 15:50
> Right, that would be great, something like:
> 
> ```
> SearchCategory.parse("all")
> SearchCategory.all.value // all
> ```
> 
> It would still be nice to have implicit support for string based values, so we don't need to write:
> 
> ```
> enum SearchCategory {
>   all = "all",
>   popular = "popular",
> }
> ```

I see what you mean, and yes brining that feature over would be nice as well.

**Comment by srawlins** [comment] 2021-04-08 18:24
Duplicate of https://github.com/dart-lang/language/issues/1560.

**Comment by esDotDev** [comment] 2021-04-08 18:45
Closing since there is an existing issue for the same functionality.

**Closed** 2021-04-08 18:44 UTC
Labels: feature
