### ISSUE TITLE
Type not checked in case of using "if null"

### ISSUE THREAD

**Issue by rafaellop** [dart-lang/language#2718] opened 2022-12-13 13:10 UTC
The example below shows a case where the compiler doesn't complain about types while it IMHO should. Some may say that the `dynamic` variable `some` declared as non-nullable would fix that but the example is a simpler version of code which uses a Map and dynamic values coming from a json response so no way to know the type and there may be null as well.

The finding was possible due to my mistake where I used the incorrect default const `defValString` for the `if null` operator (`??`) instead of the `defValBool` and the compiler didn't message me as this seemed fine to it. If this is intentional then OK, but I think a warning should be emitted at least.

DartPad gist is here:
https://dartpad.dev/?id=0711afdbee583a59f5cd655af49c85ac
```
void main() {

const bool defValBool = false;
const String defValString = 'default';
  
bool useBool = defValBool;
dynamic some = true;
  
// defValString set by mistake but not recognized by compilator
useBool = some ?? defValString; 
print(useBool);

some = 'unknown';

useBool = some ?? defValString;
print(useBool); // <--- crash with TypeError
 
}
```

**Comment by eernstg** [comment] 2022-12-13 14:29
This is working as intended. The main point to note is that the type `dynamic` is used in order to assert that "I know what I'm doing, so the compiler should just let me do it". Here is a variant of the program with some other comments:

```dart
void main() {
  const bool defValBool = false;
  const String defValString = 'default';

  bool useBool = defValBool;
  dynamic some = true;

  useBool = some ?? defValString; // (1) Dynamic type check, succeeds at run time.
  print(useBool); // 'true'.
  some = 'unknown';
  useBool = some ?? defValString; // (2) Dynamic type check fails.
  // useBool = (some as Object?) ?? defValString; // (3) Compile-time error.
}
```

The assignment at (1) is subject to a dynamic type check (that we are actually assigning a `bool` to `useBool`), and it succeeds (because `some` has the value `true`). The reason why the type of `some ?? ...` is `dynamic` is that the type of an `??` expression is obtained by taking the non-null type corresponding to the left operand type (which is `dynamic`, and the non-null type corresponding to `dynamic` is also `dynamic`), and then taking the upper bound of that and the right operand type, which is again `dynamic`.

We could have defined that the non-null type for `dynamic` is `Object`, but that would have been massively breaking (especially back when this decision was taken, because Dart was less strictly type checked statically at that time).

The assignment at (3) uses `Object?` as the left operand type (which is the same set of objects as `dynamic`, the difference is that `Object?` is subject to normal static type checking). The non-null type for `Object?` is `Object`, and hence the type of `(some as Object?) ?? defValString` is `Object`, and it's a compile-time error to assign an `Object` to a variable of type `bool`.

I'll close the issue because it is all working as intended.

**Closed by eernstg** 2022-12-13 14:29 UTC

**Comment by rafaellop** [comment] 2022-12-13 14:41
I understand your point, but the problem is not with the `dynamic some` variable which of course has full right to crash at runtime if the `dynamic` is not `bool`. The problem is with the right side which is not verified against the `useBool` variable type and in a case when the `dynamic some` becomes `null` we have crash which the `if null` operator was expected to protect against. A warning during static analysis could help a lot in a case of mistake which I did and which happen.

```
void main() {
  const bool defValBool = false;
  const String defValString = 'default';

  bool useBool = defValBool;
  dynamic some = true;

  useBool = some ?? defValString; // (1) Dynamic type check, succeeds at run time.
  print(useBool); // 'true'.
  some = null;
  useBool = some ?? defValString; // (2) Crash
  print (some);
}
```

**Comment by rafaellop** [comment] 2022-12-13 14:43
> > uses a Map and dynamic values coming from a json response so no way to know the type and there may be null as well
> 
> You may still use `Map<String, Object?>` when parsing a JSON object. I do it always. It's a little more cumbersome to parse, but avoid these kind of problems.

Thanks but this happen in that case

![image](https://user-images.githubusercontent.com/8421184/207363637-5c85d53e-a08f-4956-9509-3098d94570ab.png)

**Comment by mateusfccp** [comment] 2022-12-13 14:47
> > > uses a Map and dynamic values coming from a json response so no way to know the type and there may be null as well
> > 
> > 
> > You may still use `Map<String, Object?>` when parsing a JSON object. I do it always. It's a little more cumbersome to parse, but avoid these kind of problems.
> 
> Thanks but this happen in that case
> 
> ![image](https://user-images.githubusercontent.com/8421184/207363637-5c85d53e-a08f-4956-9509-3098d94570ab.png)

Yeah, this is expected. You may either cast the value (which is unsafe anyway) or promote it using `if (runCounter is int)`...

**Comment by rafaellop** [comment] 2022-12-13 15:52
Thanks guys but still hoping that a warning will light up some day in such case.

**Comment by eernstg** [comment] 2022-12-13 17:47
@rafaellop, my take on dynamic type errors (or dynamic errors in general) caused by having one or more expressions of type `dynamic` is that it should be easy to apply certain disciplines: For example, it should be easy to enforce that no expressions of type dynamic occur in a library at all, or no expressions have type `dynamic` except for the case where this type is obtained as an explicitly declared return type of a getter/method/function/operator, or dynamic invocations can only occur when preceded by `// ignore:avoid_dynamic_calls`, or some other well-defined property.

We do have some features targeting this kind of discipline, cf. https://dart.dev/guides/language/analysis-options#enabling-additional-type-checks. An 'analysis_options.yaml' like this one is the strictest one I can come up with right now, and it gives rise to two errors on the example I gave:

```yaml
analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
linter:
  rules:
    - avoid_dynamic_calls
```
