### ISSUE TITLE
Null safety feedback: What this means for asserts

### ISSUE THREAD

**Issue by thedejifab** [dart-lang/language#1019] opened 2020-06-10 21:38 UTC
The sound null safety is solid work as far as I've played around with.
 I'm pretty curious as to what this means for `assert` statements that check for nulls.

In Snippet 6:Promotion, 
```
int getLength(String? str) { 
 if(str == null){
    return 1;
  }
  assert(str != null);
  
  return str.length;  
}

void main() {
  print(getLength('This is a string!'));
}
```

By replacing the if-check for null with an assert as in `assert(str != null);`, the compiler flags the return statement as having a null value which I find somewhat unexpected since going past the assert means the string value is not null.

Is this an intended behaviour, and what are the implications?

**Comment by eernstg** [comment] 2020-06-11 07:57
As @julemand101 mentioned, an `assert` cannot be relied upon for promotion of types (here: `String?` to `String`) because it may not be executed, so I'll close this noting that it is working as intended.

**Closed by eernstg** 2020-06-11 07:57 UTC

**Comment by thedejifab** [comment] 2020-06-11 11:47
Got it! Thanks!

**Comment by leafpetersen** [comment] 2020-06-12 00:18
Additional small comment: if you really want to, you can use a cast to promote inline:

```dart
void test(String? str) {
  str as String;
  str.length; // str has been promoted to String, since the cast will fail otherwise
}
```
