### ISSUE TITLE
Static const class can't be used in a const constructor 

### ISSUE THREAD

**Issue by feinstein** [dart-lang/language#1454] opened 2021-02-16 00:35 UTC
This code illustrates the problem:

```dart
class C {
  const C({this.s});

  final String? s;
}

class B extends C {
  const B({String? s} : super(s: s ?? TestStatic.a.s); // error here
} 

class A {
  const A({this.s});

  final String? s;
}

class TestStatic {
  static const A a = A(s: 'a');
}
```
The compiler says "invalid constant value" for `TestStatic.a.s`.

Am I missing something here or the compiler should be able to see that `s` is a constant value as `A` was constructed as a `const` inside `TestStatic`?

**Comment by eernstg** [comment] 2021-02-16 09:17
This is working as intended. The set of constant expressions in Dart is quite restricted, and a member access like `someExpression.s` is never a constant expression, so it's not allowed in the superinitializer `super(s: s ?? TestStatic.a.s)`.

The rules about constant expressions ensure that no constant expression evaluation will run arbitrary code: They only allow function invocations for specific instance members that are defined by the platform (so the compiler can know what they do).

**Comment by eernstg** [comment] 2021-02-16 09:35
I'll close this as a duplicate of https://github.com/dart-lang/language/issues/299: The implied language design proposal would be to allow some getter invocations (other than `String.length`) as constant expressions.

**Closed by eernstg** 2021-02-16 09:35 UTC
Labels: request, state-duplicate

**Comment by feinstein** [comment] 2021-02-16 13:32
Thank you for taking the time to explain it :)
