### ISSUE TITLE
Allow switch expression branches to have bodies

### ISSUE THREAD

**Issue by ktkk** [dart-lang/language#3297] opened 2023-08-21 14:02 UTC
Sometimes I want to do just a little bit more in one branch of a switch expression compared to another.
Let's say I want to log something when a Success branch is reached.

Currently I have 2 options:

1. Convert the switch expression to a switch statement:
```dart
final String message;
switch (result) {
    case Success(success: final success):
        developer.log(success);
        message = success;
    case Error(error: final error):
        throw error;
}
```

2. Write a separate function for the Success branch
```dart
final message = switch (result) {
    Success(success: final success) => _logAndReturn(success),
    Error(error: final error) => throw error,
};

String _logAndReturn(String message) {
    developer.log(message);
    return message;
}
```

I find the first option a bit too verbose and the second option difficult to read because it requires you to navigate to the function to know what's going on.

So why not allow switch expressions to have bodies?
```dart
final message = switch (result) {
    Success(success: final success) => {
        developer.log(success);
        success
    },
    Error(error: final error) => throw error,
};
```
This would make Dart's switch expression more similar to Rust's `match` or Kotlin's `when`.
Additionally, it could introduce implicit returns from functions like Rust or just from lambdas like Kotlin, because currently the syntax looks a bit out of place in Dart.

**Comment by elliotPopina** [comment] 2023-08-21 14:07
Hi @ktkk i have the same problem, to overcome this I do like this
```dart
final message = switch (result) {
    Success(success: final success) =>  () {
        developer.log(success);
        success
    }.call(),
    Error(error: final error) => throw error,
};
```

Hope this help you

**Comment by ktkk** [comment] 2023-08-21 14:11
Hi @elliotPopina,
That's indeed a good solution.
Would still be nice if this was a native language feature instead of a workaround like this :)

**Comment by mateusfccp** [comment] 2023-08-21 15:41
Duplicate of #3117.

**Comment by mateusfccp** [comment] 2023-08-21 15:43
> Hi @ktkk i have the same problem, to overcome this I do like this
> ```dart
> final message = switch (result) {
>     Success(success: final success) =>  () {
>         developer.log(success);
>         return success
>     }.call(),
>     Error(error: final error) => throw error,
> };
> ```
> 
> Hope this help you

You don't need to use `.call()`:

```dart
final message = switch (result) {
    Success(success: final success) =>  () {
        developer.log(success);
        return success
    }(),
    Error(error: final error) => throw error,
};
```

**Closed** 2023-08-24 09:03 UTC
Labels: feature
