### ISSUE TITLE
Create library and hide implementation

### ISSUE THREAD

**Issue by frelei** [dart-lang/language#3440] opened 2023-11-01 14:43 UTC
Hello everyone!

We have several modules that we need to share with other teams. However, we would like to hide the implementation of the code. 

The idea is to provide a `.framework` or `.aar` like any software development such as iOS or Android. 
I know Flutter can generate a `.framewok` or `.aar`, however isn't possible to get the widgets and logic develop without exposing the code. The method channel can only transfer primitive types and load widget components from those format seems complicated.

The idea is to create a way to export a module and share it with others hiding the implementation that was made it.

**Comment by mraleph** [comment] 2023-11-01 19:01
This is not a language issue but an SDK issue. 

It's a duplicate of https://github.com/dart-lang/sdk/issues/42863

Currently we have no plans to develop something like this. 

Note that you can't really truly _hide_ the implementation - you can at best _obscure_ it. If you develop in Java and you provide other teams with a `jar` for your library they can decompile class files and look into how things are working under the hood... You are just making it a tiny bit harder.

**Closed by mraleph** 2023-11-01 19:01 UTC
Labels: request

**Comment by trapeye** [comment] 2023-12-21 01:28
why no plans to develop something like this? is it hard?
