### ISSUE TITLE
`is` operator should be applicable to `void` type

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/language#2041] opened 2021-12-26 00:14 UTC
```dart
main() {
  void x;
  print (x is Null);
}  
```
What is the reason for the compiler to reject this program? ("This expression has a type of void so its value cannot be used")
Why can I say "x as Null", but not "x is Null"?

Nitpick: the error message is confusing. It should at least give a hint that the value actually CAN be used, but you need to cast it to a "more concrete" type.

**Comment by Levi-Lesches** [comment] 2021-12-26 00:31
You're using `void` like `dynamic` or `Object?` that can be any type, but `void` is different: it means `x` should never be used. Using `void` is a signal to the _reader_ that you never intend to use that value, and no one else should either. Casting `x` to a different type using `as` means it's no longer `void`, so now it can be used. That doesn't mean it's encouraged, though, because the value was explicitly marked as `void` -- don't use! Also, like any use of `as`, it's unsafe and can lead to a runtime error. Asking if `x is Null` is essentially doing work on `x`, meaning you're using its value, which isn't allowed. Moreover, if this were the condition of an `if` statement, the type system would have to do analysis on `x` (say, to check for the `invariant_booleans` lint or promotion), which it refuses to do.

> It should at least give a hint that the value actually CAN be used, but you need to cast it to a "more concrete" type.

As I said above, marking a value as `void` means you're signaling to the reader that it should not be used. Dart shouldn't be going behind your back and showing others how to extract a value from it. Keep in mind this is less of a "soundness" issue (where unsound workarounds are allowed and well-documented) and more of a correctness issue, where the original intent should be enforced unless you want to take certain risks.

**Comment by tatumizer** [comment] 2021-12-26 00:55
Have you ever written a "void check" containing the bank account info? 
Imagine someone takes your void check and writes $10000 on it and then proceeds to make a point that the check is not void any longer, and now it's *his* money. Your argument is equivalent to this. 😄

**Comment by Levi-Lesches** [comment] 2021-12-26 01:08
> and then proceeds to make a point that the check is not void any longer

Actually, I think this is from _your_ earlier comment: 

> It should at least give a hint that the value actually CAN be used, but you need to cast it to a "more concrete" type.


So long as you don't touch `void` values, you're fine. But when you start messing with them, removing the `void` restriction from them, and using them in "concrete" circumstances, you're walking into trouble.

**Comment by tatumizer** [comment] 2021-12-26 01:51
This simply shows that "void" in dart has a meaning that is not consistent with the normal meaning of "void".
Had dart prohibited the use of void altogether (no "as"!) - it would be a different matter. But allowing "as" and not allowing "is" is just bizarre. 
Probably the issue was discussed at some point and this strange decision was made based on some scholastic arguments akin to those you are trying to advance, but it all sounds totally surreal to me.

**Comment by Levi-Lesches** [comment] 2021-12-26 01:57
`as` is hardly a language feature you can describe as "allowed". It's like `!`, where you're telling the compiler "I know you think you understand what this is, but trust me it's not", and Dart just has to trust you. `is` is different. You're asking the compiler to tell you what it knows. In the case of `void`, it knows nothing, and therefore has nothing to tell you.

**Comment by tatumizer** [comment] 2021-12-26 02:22
> You're asking the compiler to tell you what it knows. In the case of void, it knows nothing, and therefore has nothing to tell you.

You totally misunderstand how the compiler works, and that's a bit of a problem. This makes the discussion very difficult.
"is" and "as" are both runtime operations. They are totally equivalent in this regard. 

You could learn something from the exchange (you have A LOT to learn), but you are refusing to ask questions. That makes the discussion pointless.

**Comment by eernstg** [comment] 2021-12-27 19:31
@tatumizer, you can find the set of contexts where an expression of type `void` can occur [here](https://github.com/dart-lang/language/blob/9daaad1d2103dcb7ad91f3ebf27a878c13fca985/specification/dartLangSpec.tex#L21683).

In general, an expression of type `void` can evaluate to any object (_every_ object has a run-time type which is a subtype of `void`), so in that sense `void` is just another name for `Object?` (and `dynamic` is yet another name for that same set of objects). However, an expression of type `void` _should_ be discarded, because the developer who gave it that type indicated that this object is of no interest (that's the purpose of `void` in Dart). @Levi-Lesches already mentioned this:

> it means `x` should never be used.

If you happen to know more than the type checker then you can force-use the result of evaluating an expression of type `void` by means of a cast: `var o = expressionOfTypeVoid as Object?;`. A type cast (`as`) is included as an acceptable context for an expression of type `void` exactly because there must be an escape hatch.

There is no need for an escape hatch with a type test (`is`), so that's an error. You can always do things like `(x as Object?) is int`.

I'll close this issue because it is all working as intended. @tatumizer, if you wish to promote an alternative design for this whole area of the language then please create a new issue for the proposal.

**Closed by eernstg** 2021-12-27 19:31 UTC

**Comment by tatumizer** [comment] 2021-12-27 20:51
> (x as Object?) is int.

I didn't know this.

**Comment by eernstg** [comment] 2022-01-04 12:44
> I find it strange.

If you accept the conceptual model where the type `void` in Dart means "this could be any object whatsoever, but you're supposed to discard it" then it makes sense to basically make it impossible to use such an object. Any interpretation of what it means would be a misunderstanding.

Nevertheless, we all know that software evolution and less-than-perfect designs will give rise to situations where some expression has type `void` even though it is _actually_ not intended, perhaps just in one very special location in the code, to have that meaning. So we included the escape hatch which is a cast. We could also have provided some other mechanism, e.g., we could have given `void` a single getter `weReallyNeedToSeeThisObjectAnyway` which returns `this` with the type `Object?`, and then we could use `x.weReallyNeedToSeeThisObjectAnyway is int`, and `x as T` could then also be an error.

Note that the protection against using the result of an expression whose type is `void` is not strict: Any type variable `X` with no bound could have the actual value `void`, but we make no attempt to prevent usages of the value of an expression of type `X` (this would presumably be prohibitively expensive).

There is no soundness problem, it is purely a mechanism that allows developers to inform each other that a specific expression may have useful side effects, but the resulting value should be ignored. So we made the choice to avoid the performance hit, and made the `void` protection "best effort" rather than strict and complete.

> If by "whole new area" you mean the `VoidOr` idea

I wasn't talking about a new area, I was talking about the treatment of the type `void` as an "area" of the language. We could have a completely different conceptual model, and (consequently) we could have different rules for the treatment of `void` anywhere it occurs, but this would then be a proposal for the treatment of `void` in Dart as a whole area. If we don't do that then I think that the current treatment of `e is void` and `e as void` is consistent and reasonable.

`VoidOr` would be a new union type, and I haven't considered that in detail. It may or may not require a complete redesign of the treatment of `void`.

In any case, such a complete redesign would have to, somehow, end up having a huge amount of common behavior with the current treatment of `void`. Otherwise it would be a massively breaking change (because `void` occurs in many places), and I don't think it's reasonable to go into a complex update of all the existing Dart software for this purpose.

**Comment by tatumizer** [comment] 2022-01-04 13:07
My complaint about void was indeed related to the VoidOr idea.
Operator "is" is very convenient for VoidOr. But, as I realize now, this doesn't imply that `void` itself should be equipped with this operator. It doesn't. So the argument about "void" just boils down to this: "as" operator is a "twin" of "is" operator, but in case of "void", this twin is not there. I thought it could be a bug, but if there's some philosophical theory behind the effect - fine.

VoidOr type can be useful regardless, and it shouldn't necessarily be named VoidOr - it could have a completely different name, reflecting the fact that it applies to parameters only. The only reason I'm talking about it at all is that it provides a parsimonious solution to a practical and common problem (that is, it solves the problem, but doesn't create a whole lot of other problems while doing so).
