### ISSUE TITLE
Dart 3 when statement with switch doesn't work after continue newCase;

### ISSUE THREAD

**Issue by meetimran** [dart-lang/language#3077] opened 2023-05-16 11:42 UTC
if a case has any statement, dart3 puts `break;` by default,
but I don't want that, I want to continue checking for other cases

So, Here's the code I wrote:
```dart
void main() {
  String greetings = "Hello";
  bool check = true;
  switch (greetings) {
    case "Hi" || "Hello" when check:
      print("Hello Imran");
      continue newcase;
    newcase:
    case "Hello" when check == false:
      print("Hello Hello");
    default:
      print("Didn't work");
  }
}
``` 

**Expected output:**
Hello Imran (as the `check == true` is actually True)
Didn't work (as for the `case "Hello" when check == false:` , `check == false` is actually False

**Given output:**
Hello Imran
Hello hello (Problem: Dart is ignoring the second when statement)

So, when the first when statement at line 5 is checked True,
Dart 3 is ignoring the second when statement at line 9

**Comment by eernstg** [comment] 2023-05-16 12:08
> Problem: Dart is ignoring the second when statement

This is working as intended: The statement `continue newcase` causes the execution to continue by executing the body of the set of cases (we can have one or more) which is labeled `newcase`. In other words, we won't start running the code which is associated with all the `case` constructs, we're jumping directly to the labeled body.

One consequence of this is that a set of cases with a label does not support variable declarations: The variable could not have been initialized when the body is entered because of a `continue someLabel;` statement, and hence the variable cannot be used in the body.

```dart
void main() {
  switch (1) {
    case 1:
      continue positive;
    positive:
    case var i when i > 0:
      print(i); // Error: 'i' is not available.
  }
}
```

**Comment by eernstg** [comment] 2023-05-16 12:38
This particular behavior is working as intended, so I'll close the issue.

It would be possible to create a more detailed proposal such that `continue newcase;` would actually jump to the case group labeled as `newcase` and then proceed to match the cases and introduce variables etc. It would presumably skip the case group entirely if no match was found, and it would then continue the matching process with the next case group, if any.

This would be a substantial change to the semantics of the feature, and it would certainly be a difficult case to make, now that patterns etc. have already been released.

@meetimran, if you wish to put forward a more detailed proposal for how to do this then please create a new issue.

**Closed by eernstg** 2023-05-16 12:38 UTC
Labels: request

**Comment by meetimran** [comment] 2023-05-20 16:51
Hi @eernstg,apologies for the late reply,
> One consequence of this is that a set of cases with a label does not support variable declarations
This is exactly what I meant, that it isn't working in case of cases with a new label as it do not support variable declarations but it should support variable declarations.

**Comment by eernstg** [comment] 2023-05-22 15:14
The existing semantics of Dart switch statements does not match up with an approach where `continue` gives rise to any matching steps at the target case:

```dart
void main() {
  var i = 1;
  switch (i) {
    case 1:
      print('Got 1!');
      continue L;
    L:
    case 2:
      print('Got 2! (or came here by `continue`)');
      break;
  }
}
```

As you can see, no matching step is taken when `continue L` is executed, we just jump directly to the body of `case 2` without checking the value of `i` against `2`. A proposal which would imply that we change this behavior is a dead end.

However, you can use a new switch statement if you wish to perform pattern matching after `continue`. For example:

```dart
void main() {
  void f(String greetings, bool check) {
    switch (greetings) {
      case "Hi" || "Hello" when check:
        print("We should execute this when check is true");
        continue DoRemainingWork;

      case "Hello" when check == false:
        print("We should execute this when check is false");
        continue DoRemainingWork;

      DoRemainingWork:
      case Never(): // We _only_ reach this point via `continue`.
        switch (greetings) {
          // ... cases with patterns/guards as needed
          case String(length: > 0):
            print("The greeting isn't empty!");
          default:
            print("(Keep the compiler/analyzer happy)");
        }

      default:
        print("No match");
    }
  }

  f("Hello", true);
  f("Hello", false);
}
```
