### ISSUE TITLE
Kotlin `when {}` equivalent in Dart code?

### ISSUE THREAD

**Issue by topex-psy** [dart-lang/language#918] opened 2020-04-08 08:22 UTC
## Use case
I want elegant solution for if, else if, and else with replacement like `when` syntax in Kotlin.

## Proposal
For example:

```
if (_purchase.isDone) {
    return _successAlert();
} else if (_purchase.customerID == null) {
    return _warningAlert();
} else if (_purchase.amount < 5000) {
    return _errorAlert();
}
```

to be (maybe like):

```
return when(_purchase) {
    isDone: _successAlert(),
    customerID == null: _warningAlert(),
    amount < 5000: _errorAlert(),
}
```

or:

```
return when() {
    _purchase.isDone: _successAlert(),
    _purchase.customerID == null: _warningAlert(),
    _purchase.amount < 5000: _errorAlert(),
}
```

**Comment by munificent** [comment] 2020-04-10 22:21
I'm going to close this as a duplicate of #546. As I understand it, you're asking for a generally better notation for matching on values based on predicates, which is one of the things pattern matching would give you.

Let me know if there are specifics of your request that I missed and if so I can reopen this.

**Closed by munificent** 2020-04-10 22:21 UTC
Labels: feature, state-duplicate
