### ISSUE TITLE
“reveal”, a concrete private member access proposal

### ISSUE THREAD

**Issue by icatalud** [dart-lang/language#759] opened 2019-12-20 16:16 UTC
The `reveal` keyword can only be used over classes and packages. It reveals the private scope of them in the local scope where it is used. Revealing a package does not reveal the private members of the classes.
When reveal is used in a class, it's private var context superimposes over the default scope.

```dart
Library lib;

int _counter = 0;

class _Foo() {
  int _id = _counter++;
}

///
import .... as lib;
reveal lib;

var count = lib._counter; 

class A extends lib._Foo {
  final _id = 'id';
  int id() {
    print(_id);       // 'id'
    reveal lib._Foo;     // places _Foo var context on top
    return _id++;
  }

  String strId() {
    return _id;
  }
}

class B extends lib._Foo {
  reveal lib._PrivateClass; 
  String _id;      // invalid
}
```

**Comment by tatumizer** [comment] 2019-12-20 17:31
Basically, your suggestion is equivalent to an idea of re-defining the meaning of the word "private". Currently, according to Webster, "private" means: "belonging to or for the use of one particular person or group of people only". Your idea, if I understand it correctly, is equivalent to the following reformulation:  "(the thing) belonging to or for the use of one particular person or group of people only, **unless somebody else wants it very much**". My issue with this proposal is that sometimes there are circumstances where I'd like to be certain that my private life stays as private as possible and cannot be exposed as easily as somebody else's saying "reveal" unbeknownst to me. Such a redefinition of "private" would tremendously complicate not only my personal life but also the lives of many other persons involved. 
Having said that, I respect your right to campaign for the re-definition of the notion of privacy as we know it, The English language keeps evolving along with the society, and who knows, maybe at some point in the future, your proposal will gain better traction.

**Comment by icatalud** [comment] 2019-12-20 18:18
I agree with your definition of privacy, but when it's absolute. If the language intended purposely to protect source codes from being acceded by distributing protected or compiled source then it becomes obvious what private means. In the case of Dart, private member access simply provides a convenient shortcut, because the source code is public. It's inconvenient to manually change source code because of all the steps it takes and because the changes have to be repeated when updating the library.

You can imagine what is being asked for as if someone was asking for a shortcut for conditional statement pattern in assembly. I propose an `if(condition)` statement, but then someone comes and tells me, why don't you just use test(val1, val2); jmp(z, val); instruccionA; instruccionB. The feature is being asked not to redefine what a conditional statement is, it's simply asking for a shortcut for a pattern that is common for some people.
It seems that you decide what is practical or not subjectively under your use cases, because by not listening the community about their use cases you will not be able to gather objective data about what are the most required shortcuts for the language. If you were frequently accessing private members of libraries, or you build a library on top of another one by tweaking it, you would like to have a feature like this.

Objectively your statement about your private life does not apply, because it is intended that a protected scope exists for our lifes, so I would disagree if someone asked for a "reveal" feature that allowed to expose personal lifes. This is not that case.

**Comment by matanlurey** [comment] 2019-12-20 19:02
Duplicate of https://github.com/dart-lang/language/issues/693.

**Closed by matanlurey** 2019-12-20 19:02 UTC
Labels: feature, state-duplicate

**Comment by icatalud** [comment] 2019-12-30 03:15
I reply to your comment here, because the other conversation was locked (I'm not commenting on that):

@tatumizer wrote:
> What if you write a script reveal.sh libraryName identifier, which goes into the library subdirectory under packages and finds and replaces all occurrences of the _counter (whole word only) to, say, revealed_counter thus making the variable public.
The script doesn't need to really parse anything, just do a text replacement - if the library has two or more _counter vars, the replacement won't hurt (what worked before, will work after).

Thank you for the idea, it does fulfill some use cases. When publishing there is a lot of details that need to be considered to make it 100% consistent, but yes, I think it is possible to automate all the work with some scripts, making the external libraries part of the source (would that require some licensing considerations?). But if this was common enough, wouldn't it be better if it came bundled in with the language?

I summarize what I think are the main considerations when deciding about member privacy:
1. Create a minimalist public API (makes it friendlier and easier to use), in the same way the settings options of an app are tailored to address most of the common adaptation. Many apps have an advanced settings for the options that didn't make the cut.
2. Minimize the amount of API exposure such there are less edge case interactions that need to be taken into account.
3. Having more degrees of freedom to adapt the library.
4. Prevent incorrect utilization of the library to protect users from unexpected behavior.
5. Hide internals for copyright or whatever reasons. (Does not apply to Dart)

The rating of each of the points and how to address them is obviously subjective, but the only reason to fully obscure variables is number (4). The options that currently exist are too extreme, it's either black or white, there is no intermediate point. Either you make something completely public or you make it completely private and obfuscate any chance to access the variables from the users through pure Dart. Making something intermediate requires more work, like defining a variable protected, but then the IDE still display the method as a valid option. I use private members mainly because of (1) and I feel guilty about it, because I don't want to make something completely invisible, but there is no alternative convenient way of doing this.

Imagine there was an intermediate point, like [this one](https://github.com/dart-lang/language/issues/409#issuecomment-503724466). Let's say $ makes the variables invisible unless the source file is directly imported, for example 'package:lib/src/file.dart'. We call _ full private and $ partial private. So there are two flavors of privacy which fit different personalities traits that define how people deal with (4). The preferences are:

**a.** Prevent (4) under the right barriers and guidelines, but still leave the options alive and passing the responsibility to the users (more like Android)

**b.** Prevent (4) under all circumstances and not waste time giving explanations or having to deal with complaints caused by bad utilization (more like iPhone).

Both approaches and personalities are valid, but the question is, if $ existed, what would be the trend? Personally I would use only $, what would you use? My perception is that people from the Dart team tend to prefer full privacy, but that doesn't make $ invalid, it would be ideal that both options existed. Imagine if partial private existed and the majority of Dart users preferred partial over full privacy (there is no way to know it).

The proposal here is an alternative, instead of defining a new private type $, give an option to revert privacy and satisfy (a). This would conflict with (b) but this is solved by forcing a fix library version in the pubspec in order to use it. This is 100% reasonable, I don't see any argument that disables this idea. And if someone from the Dart community or even a minority from the Dart team would like to have partial privacy or privacy revert, are they forbidden to develop it, or to to even like the idea?

**Comment by tatumizer** [comment] 2019-12-30 17:14
> When publishing there is a lot of details that need to be considered to make it 100% consistent

For publishing, you have to fork somebody else's library, rename it and publish separately (to comply with a typical license), and from this point on, it will have a life of its own. Plus, you have to look into the details of the original license to make sure you are allowed to do that.

But it seems you are moving the goalposts a bit.  Your original rationale for the feature was primarily: learning, debugging etc - the things that are "legally safe". The script would allow you to do that. But publishing is a different matter entirely. You have to agree that for the language to provide the feature you are asking would be equivalent to inviting legal trouble. Please think about this. There are other reasons, of course, as you acknowledge yourself (e.g. it is very difficult to design the library without firm assurances from the language that private stuff stays private, or else you can't even reason about the behavior of your library clearly), but the point is: potential legal issues alone are bad enough.

**Comment by icatalud** [comment] 2019-12-31 01:39
> You have to agree that for the language to provide the feature you are asking would be equivalent to inviting legal trouble

There is no legal trouble if it is part of the language.

> There are other reasons

They are all addressed. There is no difficulty to design when considering what was explained, the discussion is summarized at the points (a) and (b).

How about creating weak privacy, like the $. Take a careful look at was was explained in the previous post. If you had full privacy and weak privacy, don't you think that would cover a wider spectrum of preferences? What if the majority preferred to use weak privacy (it's unknown)? What would you use (out of curiosity, it doesn't matter from the rational perspective)?
