### ISSUE TITLE
Alternative for enabling experiments post language-versioning.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#554] opened 2019-08-30 14:23 UTC
The current [specification of language versioning](https://github.com/dart-lang/language/blob/master/accepted/future-releases/language-versioning/feature-specification.md#experiment-flags) states that the `--enable-experiments` flags will only affect libraries which are using the most recent SDK language. Not enabling experiments for the wrong libraries is important for *breaking change* experiments. The program would fail to run if unprepared libraries enable the experiment, which would foil the intent of experiments, which is to allow authors to start migrating and testing their library prior to the release of a new language feature.

Before language versioning, there was no way to enable experiments for only some libraries or packages. There were also no breaking changes, so that was not an issue.
The upcoming NNBD feature *is* breaking, which is the reason for introducing per-library language versioning to beging with, and the experiment flag `--enable-experiment=nnbd` needs to be more selective

The specification says that an experiment flag only affects libraries that have a default SDK version, as defined by being in a package where the `.packages` file does not provide an SDK version (like `...#dart=2.5.0-whatever`) or it has an SDK version which is exactly the current SDK version, and the library does not have a language version override (like `// @dart=2.5`).

This design makes it very cumbersome to enable experiments, especially if you want to do it for more than one package at the same time. 
It doesn't actually work if you are working with a released SDK, say the 2.5.0 SDK. If any of your supporting packages have already changed their SDK dependency to `^2.5.0`, then there is no way to opt those *out* of being affected by the experiment flag.

More importantly, some of our tools do not know the "SDK version". The Common Front-End is released as a stand-alone package, independent of any SDK versions. 
So, rather than inventing some more complicated way to pass SDK versions around, it might be better to just be explicit.

I propose to change the rules such that:
* The `.packages` file URIs can also contain an `enable-experiments` marker in the URI metadata, like `foo:file://.../file/#dart=2.5.0&enable-experiments`.
* An `--enable-experiment` flag has no effect on a library unless it is in a package with `enable-experiments` in the package metadata in `.packages`
* An `--enable-experiment` flag on a tool has no effect unless the library's *language version* (major.minor) is the most recent language version understood by the tool. Each Dart tool should know their maximally supported *language level*, even if they don't know their exact SDK version.
* Non-package libraries are treated as being part of the default package, if any, for this.

The `.packages` file can be edited manually if necessary, but we may prefer to have `pub` generate the marker from an entry in `pubspec.yaml`. That is *preferable* because we can then prevent publishing a package with experiments enabled. You can still work on multiple packages at the same time, as long as you use path/github references in the pub dependencies, and the pub tool can mark all of them as experimental in `.packages`.

**Comment by stereotype441** [comment] 2019-08-30 17:56
@nshahan FYI

**Comment by nshahan** [comment] 2019-08-30 20:22
I can't tell if this would break the following workflow:

Write a simple dart script file (only a single file, not part of a package, no pubspec.yaml etc) and run one of our tools with an experiment flag to see the results. For example:
`$dartanalyzer --enable-experiment=non-nullable foo.dart`

This might not be a common workflow outside of the dart team but I know it is very useful for us during development to quickly reproduce some behavior and test it locally without creating all of the boilerplate of a fully fledged package.

Could you elaborate on if the tool should ignore the experimental feature flag in this case?

**Comment by leafpetersen** [comment] 2019-08-30 22:14
> The program would fail to run if unprepared libraries enable the experiment, which would foil the intent of experiments, which is to allow authors to start migrating and testing their library prior to the release of a new language feature.

I'm not sure I agree that this is the intent of the experiments flag.  The experiments flag is to keep features from being used in shipping code before they are stabilized.  Part of that is, indeed, validating on packages, but actual package migration is more likely to be done after the experiment flag is flipped, using dev versions.

> This design makes it very cumbersome to enable experiments, especially if you want to do it for more than one package at the same time.

I don't understand how this proposal makes this less cumbersome (it seems like it makes it more cumbersome to me).  Can you elaborate on what you see the proposed workflow looking like?

> It doesn't actually work if you are working with a released SDK, say the 2.5.0 SDK. If any of your supporting packages have already changed their SDK dependency to `^2.5.0`, then there is no way to opt those _out_ of being affected by the experiment flag.

I'm not that concerned with experiments flags working in released SDKs.  In fact, I had proposed at one point that they be hardwired in the "off" position in stable SDKs.  If you want to mess with an experiment, you should at least be on dev, and probably on bleeding edge.

> More importantly, some of our tools do not know the "SDK version". The Common Front-End is released as a stand-alone package, independent of any SDK versions.

Can you elaborate on what use case you're concerned about here?

**Comment by lrhn** [comment] 2019-09-02 11:25
If we say that experiments are not enabled for stable releases, then we only need to consider pre-releases (version number includes a `-`) for the *next* version.

So, if we have an SDK which supports language level 2.5 out of the box as its latest language version, then it's either a stable release (2.5.0, 2.5.1, ...) or it is a pre-release of something later (2.6.0-dev.99.9).
In the former case, we don't care about experiments because they are not there.
For the latter case, we an enable experiments for any library with a language version of 2.6, which means a `//@dart=2.6` or a package default SDK version of `2.6.xx-whatever`.

Is there any situation *not* covered by that approach?

**Comment by jensjoha** [comment] 2019-09-02 11:34
The feature spec - as it is now - requires the .packages file to contain something like "#dart=2.6-edge-sha1hash" where that particular version string matches something that exists in a file located somewhere in the sdk directory.

That doesn't really work for (at least) the CFE as we don't have that exact string and thus cannot match against it.
One could argue that the embedder could provide us this string, but short of running "dart --version" and parsing it they at least currently (to my knowledge) does not. Changing that seems like a lot of trouble and specifically more trouble than this is worth.

If we DON'T force people wanting to use this to be on tip-of-tree or some dev-release or something (i.e. allow stable) published packages that they could rely on could already be on the same version as the current stable and thus the same version that the new thing trying to enable the experiment would have to be on. Enabling the experiment by that version alone could thus cause trouble as it would also change the behavior in packages the user has no control over.
We thus - on Friday - came up with the solution of the .packages file specifying which package(s) would want experiments enabled as a "good easy solution".

If we DO force people wanting to use this to be on tip-of-tree or some dev-release or something (i.e. don't allow stable) published packages that they could rely on could _not_ be on the same version, and just relying on the version (say 2.6) should be sufficient. One could try updating several packages by updating the .packages file. Another "good easy solution".

I for one am good with either, with the latter one having an edge because it requires no work on my part (and better "supports" @nshahan concern)

**Comment by leafpetersen** [comment] 2019-09-04 22:17
> If we DO force people wanting to use this to be on tip-of-tree or some dev-release or something (i.e. don't allow stable) published packages that they could rely on could _not_ be on the same version, and just relying on the version (say 2.6) should be sufficient.

@jensjoha I'm not sure if I followed you correctly.  Can you elaborate on what changes this solution implies to the feature spec, and how it addressed your concerns about having access to the necessary information in the front end?

**Comment by jensjoha** [comment] 2019-09-05 06:44
I'll try:

- The currently released stable version is 2.4 and dev-version is 2.5.
- I (maybe naively) assume that the highest minimum sdk version of any pub package is therefore 2.4, and that that is enforced somehow.
- The front-end knows that we're (currently, at tip-of-tree) on version 2.6.
- If `--enable-experiments` is only available on tip-of-tree (i.e. the current 2.6) (or potentially also for dev-releases so that when there's a dev-release of 2.6 it's still available --- assuming that published packages cannot have a minimum sdk version of a dev-release).
- If we then say that whenever anyone uses the `--enable-experiments` flag, it only applies to libraries on the latest language version (i.e. currently 2.6), we'll get that:
  - any developer can use `--enable-experiments` by setting the library version to 2.6.
  - any published packages they rely on is on a lower language version, and the experiments thus does not apply to those.
  - if they themselves have several packages they want to test with `--enable-experiments` they do a path-override (or whatever it's called) to the not-published version of that, which also has library version 2.6.
  - in total: any developer can enable experiments on anything they own as they wish without effecting anything else they rely on (published packages etc). One can also use it without being in a package. The "cost" is that it's only available on tip-of-tree (and potentially dev-releases) and that they need to mark the library as being on version 2.6.

The feature-spec currently says that to enable experiments we:
- have to be in a package because the minimum sdk version has to be exactly the build-version, e.g. (say) "2.6.0-edge.8fb0152af8fd5707dfafd8eb68a8d3d412cdea7e"
- this implies that the front-end would have to know this build version (which it does not) to enable the experiment
- (and btw for tip-of-tree-builds the version changes for every commit)

The idea behind this - as I understood it - was that one would allow any developer to enable experiments on _their_ package only (though, potentially several of their packages) without effecting any packages they relied on.

My suggestion is that it instead becomes something like

- experiments are only available on tip-of-tree (potentially also on dev-releases).
- experiments are only available for libraries has has the latest language version (major and minor) as of the dart-version the user is on.

I *think* that this is also basically what @leafpetersen is hinting at and that it is what @lrhn says in comment ~5. It is *very different* though, from both this issue-text _and_ the feature specification.

**Comment by lrhn** [comment] 2019-09-05 08:06
I'd assume that the Dart formatter has a similar issue if it needs to support the experiments flag.
It knows which language level it understands, but it does not know what exact SDK version it has been shipped with. It's a stand-alone package.

So, if it knows that the stable language version supported is 2.5, then it can enable any experiment for any library with a version of at least `2.6.0-` when the experiments flag is passed, and reject the library if no experiment flag is passed, because then it only understands up to language level 2.5.

I think that's simpler than relying on an exact version number which needs to be propagated from the SDK build system to all tools accepting experiments flags.

**Comment by jensjoha** [comment] 2019-09-05 08:11
> [...] and reject the library if no experiment flag is passed, because then it only understands up to language level 2.5.

why? (or is this specifically for the formatter?)

**Comment by lrhn** [comment] 2019-09-05 11:32
If a library requires Dart 2.6 and the most recent released language version known by the SDK is 2.5, then there is probably an issue and I'd expect a compiler to reject the program. After all, it doesn't know which semantics (or even grammar) to apply to the library source.

If there is an `--enable-experiments=...` flag, and the tool recognizes it, then the tool might know which grammar and semantics to experimentally use, and it can allow the program.

**Comment by jensjoha** [comment] 2019-09-05 11:45
If the tool (e.g. the compiler) knows about the experiment doesn't it also think the sdk is higher than the current stable?

**Comment by lrhn** [comment] 2019-09-05 13:04
That's actually an interesting question :)

The compiler knows, deep in its electronic guts, which *language* versions it understands. It knows, say, what Dart 2.5 *is*, completely independently of the SDK it is part of. It also knows that it *doesn't* know what Dart 2.6 is yet, so out of the box, with no extra flags, it cannot compiler "Dart 2.6" because there is no such language, it has neither syntax nor semantics.

At some point during the 2.6.0 development cycle, we start enabling the new language features, so we can test them properly. At that point, the compiler might actually think it knows what Dart 2.6 is (and it does, but perhaps only partly). So, if Dart 2.6 has two features, "cromulance" and "fluxitive", and in `2.6.0-dev.42.3` we enable "cromulance" by default, then `--enable-experiment=fluxitive` should still work. What language does the compiler think it's actually running now? The answer is ... probably `2.6`.

So I guess that the compiler needs to "know" two things: What is the language version I understand as-is, the maximal version I accept inputs written in, and what is the language version I will allow enabling experiments on.

A freshly released stable SDK 2.5.0 compiler will say that its native language version is 2.5, and its experiment language version is 2.6. There likely are no experiments yet, but you never know.

A 2.6.0-dev.1.0 SDK compiler will likely say that both versions are 2.6, or maybe keep the native language version is still 2.5 until we actually enable any new feature. In the former case, it will accept libraries with `//@dart=2.6` comments, and it will also allow enabling experiments for those libraries. Since it is not a released version, *preferably* no published package should be using 2.6 as their language version.

Would that make sense?

**Comment by jensjoha** [comment] 2019-09-06 06:56
I suppose it _does_ make sense, but I'm not sure it actually gives any value to have that distinction.

From my perspective it makes just as much sense, that once tip-of-tree is bumped to, say, 2.6 in it's version file (so that the vm reports `2.6-edge-whatever`) the compiler allows 2.6 too (and allow - but don't require - enabling any experiments on that).
I don't see that having the added complexity of there being an amount of time where the max is 2.5 but where - if enable experiments is active - it also allows 2.6. If nothing else its more confusing to everyone and will add (seemingly unneeded) complexity to the code.

**Comment by leafpetersen** [comment] 2019-09-17 05:00
Where is this discussion? I'm still a little in the weeds about parts of it.  From my perspective, my expectation would be something like this:

- You can always turn on an experiment flag.  When you turn on an experiment flag, the language versioning support for that feature may, or may not be implemented.  It can be in any state whatsoever - it's under development.  For example, we're preparing the "variance" experiment flag.  There will be no language versioning support for this initially - if you turn on the flag, it will work, otherwise it won't.
- When language versioning support for a feature is added, the feature, and the language versioning, is still behind an experiment flag.  In this state:
  - If you run a compiler that claims to be version 2.6 or 2.6-dev, or whatever, then 2.6 (2.6-dev respectively) is treated as the level in which the feature is released, and you can enable the feature in a package by:
    - turning on the experiment flag
    - setting the min sdk constraint to 2.6 (or 2.6-dev respectively)
  - For non-package files, just running with the experiment flag turns on the feature, since the file is treated as being in the default package.

So where does this go wrong?  Does the CFE not have enough information to know what min sdk constraint above should be treated by the language versioning as "on"?

Stepping up a level, I think my main point here is that **experiment flags + language versioning** is not a user facing feature.  An experiment flag is for us.  The feature can behave any way we want behind the flag.  How the language versioning for it behaves is purely for our convenience no?

**Comment by leafpetersen** [comment] 2020-01-08 23:50
Where is the discussion on this?  cc @MichaelRFairhurst

**Comment by mit-mit** [comment] 2021-08-16 12:11
Closing as unplanned

**Closed by mit-mit** 2021-08-16 12:11 UTC
