### ISSUE TITLE
shortened enum parameter

### ISSUE THREAD

**Issue by leslmosnk** [dart-lang/language#3543] opened 2024-01-05 12:56 UTC
I want to be able to leave out the enum name when passing it as a parameter.

To call a function with an enum parameter currently have to:
```dart
enum FooBar {
     foo,
     bar,
}
void enumFunc(FooBar param) {}
enumFunc(FooBar.foo);
```
However; isn't the enum type already defined in the parameter?
This would be easier to write, and in some cases even more readable:
```dart
enum FooBar {
     foo,
     bar,
}
void enumFunc(FooBar param) {}
enumFunc(.foo);
```

The only downside I can think of is conflicts between variables that are named the same as the enum value. But in that case we could still write `FooBar.foo`

**Comment by mraleph** [comment] 2024-01-05 13:03
Duplicate of https://github.com/dart-lang/language/issues/357

**Closed by mraleph** 2024-01-05 13:03 UTC
Labels: feature
