### ISSUE TITLE
Enable CFA / exhaustiveness-checking for exhaustive switch statements

### ISSUE THREAD

**Issue by mattrberry** [dart-lang/language#3891] opened 2024-06-09 22:36 UTC
The compiler complains about `switchStatement`, reporting that the switch statement doesn't exhaustively cover the cases.

```dart
String switchStatement() {
  switch ([]) {
    case [_, ...]:
      return 'at least 1';
    case []:
      return 'none';
  }
}

String switchExpression() => switch ([]) {
      [_, ...] => 'at least 1',
      [] => 'none',
    };
```

```
main.dart:1:8: Error: A non-null value must be returned since the return type 'String' doesn't allow null.
String switchStatement() {
       ^
```

This is obviously a fairly contrived case, but I've seen similar patterns come up a few times now. Every problem I've had is solvable, but not always in the nicest of ways.

It seems that the type-checker only does the full exhaustiveness checking for switch expressions or for switch statements with very obvious cases, e.g. if `[...]` was a case in the above example. I find this to be confusing. Some more discussion [here](https://github.com/dart-lang/sdk/issues/55934).

What are the thoughts from the language team? Is this possible to support?

**Comment by srawlins** [comment] 2024-06-10 03:14
Good question. Looks like a duplicate of https://github.com/dart-lang/language/issues/2977

**Comment by mattrberry** [comment] 2024-06-10 04:20
I haven't had a chance to read all of the comments there, but that issue definitely seems to be a match. Sorry for the duplicate, I swear I tried to search the issues first 😅

**Comment by shayanzare-dev** [comment] 2024-06-15 14:03
Good

**Closed** 2024-06-16 00:36 UTC
Labels: request

**Comment by srawlins** [comment] 2024-06-17 14:54
Yeah it took me a bit to find the issue too 😅
