### ISSUE TITLE
Allow extension monkey patching

### ISSUE THREAD

**Issue by cedvdb** [dart-lang/language#2169] opened 2022-03-27 03:20 UTC
Overwriting behavior via extension can be handy to sneak in added behaviors / fixes without changing the API

```dart
void main() {
  't-e-s-t'.split('-');
  print('done');
}

extension MonkeyPatch on String {
  split(Pattern pattern) {
    print('splitting');
    this.split(pattern); // maybe not "this"
  }
}
```

**Comment by lrhn** [comment] 2022-03-27 09:45
Dart extension methods cannot displace existing instance methods. That was a design choice which means that adding an extension method on a superclass won't accidentally break uses of a subclass that has added an instance member with the same name. You don't always know all the subclasses of an interface, so this was the safer approach. Well, safer for existing code when extensions were added to the language. You can now displace an extension method by adding an instance method.

There are no plans to change this design. It would be potentially hugely breaking.

If you want to use t he monkey patch code above, you can write:
```dart
MonkeyPatch('t-e-s-t').split('-');
```
to explicitly invoke the extension method, not the instance method.

With views (#1474) you may be able to introduce a new type alias where the original `split` is hidden.

**Comment by munificent** [comment] 2022-03-28 22:28
What Lasse said. I'm going to close this issue because allowing extension methods to override instance methods would fundamentally be the *opposite* of their intended behavior.

**Closed by munificent** 2022-03-28 22:28 UTC
Labels: feature
