### ISSUE TITLE
labmda expression is not consistent

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/language#1176] opened 2020-08-26 10:41 UTC
such as following code:
void set mapY(mapY) => {this._mapY = mapY};  // this is ok, (this._mapY = mapY) return void value?
void set mapY(mapY) {return (this._mapY = mapY);}  // this is ok
int get mapX => {this._mapX};  // this is error

and following code:
int k = 0;
  var sss = () => {k};
  var s8 = (m) => {k = m};

why sss is Set< int> Function() not int Function() ?
and s8 is Set< dynamic> Function()?

**Comment by eernstg** [comment] 2020-08-26 10:51
A setter has a return type of `void` because the invocations don't evaluate to the returned value, they evaluate to the assigned value (that is, the actual argument passed to the setter). It is an error to specify any other return type for a setter.

A getter returns the returned expression, so that expression must have a type which is assignable to the specified return type. So `int get mapX => {this._mapX}` is an error (the returned expression has type `Set<T>` where `T` is the static type of `this._mapX`), and that's not a subtype of `int`.

`sss` has type `Set<int> Function()` because `{k}` is a set literal whose element type is `int`, so you probably meant

```dart
var sss = () => k;
```

`s8` has type `Set<dynamic> Function()` because `{k = m}` is a set literal whose element type is `dynamic`. We can't see the declaration of `m`, but presumably it has type `dynamic`.

**Comment by eernstg** [comment] 2020-08-26 10:56
This is all working as intended, so I'll close the issue.

**Closed by eernstg** 2020-08-26 10:56 UTC
