### ISSUE TITLE
Class inherit from generic parameter type?

### ISSUE THREAD

**Issue by hqakva** [dart-lang/language#3833] opened 2024-05-24 01:58 UTC
Does Dart allow to create a class like this?

```dart
class GenericBased<T extends Object> extends T {
    final bool myProperties;

    const GenericBased({required this.myProperties})
}
```

**Comment by jakemac53** [comment] 2024-05-24 14:17
No, Dart does not allow this.

**Comment by lrhn** [comment] 2024-05-24 16:31
The closest thing is a mixin, but mixins cannot have the constructor you need. 
```dart
mixing My properties {
  bool my property = false;
}
```

Without a constructor, it cannot add a final variable that is initialized to different values in different places.

**Comment by mateusfccp** [comment] 2024-05-25 18:13
Seems like this is a duplicate of #3552.

**Closed** 2024-08-21 22:03 UTC
Labels: request
