### ISSUE TITLE
"@required this.field" in a constructor

### ISSUE THREAD

**Issue by kaby76** [dart-lang/language#1341] opened 2020-11-28 21:51 UTC
In Flutter, there are files with `@  required` modifiers for constructors, e.g., [bench_simple_lazy_text_scroll.dart](https://github.com/flutter/flutter/blob/423459da1846379ae3b5add32e2af07a7e8cdd14/dev/benchmarks/macrobenchmarks/lib/src/web/bench_simple_lazy_text_scroll.dart#L59). I assume Flutter compiles with Dart2 and the current [spec](https://github.com/dart-lang/language/blob/d0c52b7fcda16bc20d12b363ba1d92e6bb6ad8b3/specification/dartLangSpec.tex) applies. However, the grammar that I scrape from the spec does not parse this construct. One alternative is that this is a [defaultNamedParameter](https://github.com/dart-lang/language/blob/d0c52b7fcda16bc20d12b363ba1d92e6bb6ad8b3/specification/dartLangSpec.tex#L1701) with "required" and the "@" superfluous (i.e., `<defaultNamedParameter> ::= ('@'? 'required')? <normalFormalParameter> (('=' | ':') <expression>)?`). Another explanation is that this is a [metadata](https://github.com/dart-lang/language/blob/d0c52b7fcda16bc20d12b363ba1d92e6bb6ad8b3/specification/dartLangSpec.tex#L6190), but unclear what the derivation of the string would be. I'm trying to understand how this is supposed to be parsed and adjust my grammar rules in order to continue to parse all 2682 files in Flutter correctly. Please advise. (And, yes, I have looked at the Dart.g file.)

**Comment by eernstg** [comment] 2020-11-30 09:42
> assume ... the current [spec](https://github.com/dart-lang/language/blob/d0c52b7fcda16bc20d12b363ba1d92e6bb6ad8b3/specification/dartLangSpec.tex) applies.

It's a bit more complex than that: The language specification is supplemented by stand-alone documents ('feature specifications') covering the newest features. The feature specifications are integrated into the language specification when they are sufficiently stable and mature. For instance, extension methods are specified in https://github.com/dart-lang/language/blob/master/accepted/2.7/static-extension-methods/feature-specification.md, which is currently being integrated into the language specification. Similarly, null safety is specified [here](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md).

The grammar in the bleeding-edge language specification contains some elements that are specific to null safety (the `late` and `required` modifiers, and `?` on types), but no other parts of null safety have yet been integrated.

The notation `@required` is [metadata](https://github.com/dart-lang/language/blob/d0c52b7fcda16bc20d12b363ba1d92e6bb6ad8b3/specification/dartLangSpec.tex#L6190), and `@required this.initialScrollOffset` derives from `<normalFormalParameter>` and `<fieldFormalParameter>`.

The `@required` construct will continue to be correct syntax, but with null safety it will be less useful: The intention is that a `@required` named parameter should be passed at every call site, but this mechanism is not integrated into the type system and it is quite easy to create a sample program where such a parameter is omitted an there is no diagnostic message flagging it.

The `required` modifier is only available in code that enables null safety. This modifier is fully integrated into the language (in particular: into the type system), and the associated discipline is maintained strictly and soundly with fully null safe programs.

So for parsing you'd recognize `@required` as `<metadata>`, which will succeed when `@` is followed by `<qualifiedName>` or `<constructorDesignation> <arguments>`.

You would need to know for each library whether it's opted in to use null safety, in order to know whether to allow types of the form `T?` and in order to know what a type like `int` _means_.

If you wish to treat metadata like `@required` in a special way (making that parameter required, rather than just being metadata which could mean different things to different tools, or nothing at all) then you would presumably do that after parsing has completed, in some semantic analysis phase.

**Comment by lrhn** [comment] 2020-12-01 08:57
So this is not a bug. The declaration `@required this.foo` is derivable from `<normalFormalParameter>` with `@required` being derivable from `<metadata>` and `this.foo` from `<normalFormalParameterNoMetadata>` &mapsto; `<fieldFormalParameter>`.

This is in the [currently committed spec](https://github.com/dart-lang/language/blob/master/specification/dartLangSpec.tex#L1637) without any later additions needed.

**Comment by kaby76** [comment] 2020-12-01 13:21
Verifying the expected derivation completely explicitly, because I cannot assume anything:

    metadata =>
    '@' metadatum =>
    '@' qualifiedName =>
    '@' typeIdentifier =>
    '@' 'required'

If that is so, then there is a bug here: https://github.com/dart-lang/sdk/blob/67c703063d5b68c9e132edbaf34dfe375851f5a6/tools/spec_parser/Dart.g#L913 because it does not contain 'required'.

**Comment by lrhn** [comment] 2020-12-01 13:35
There *is* a bug there, just further down than I looked. Good catch.

The rules for a qualified name should be:
```ebnf
qualifiedName
    :    identifier        /// *not* typeIdentifier!
    |    typeIdentifier '.' identifier
    |    typeIdentifier '.' typeIdentifier '.' identifier
    ;
```
Built-in identifiers (and `typeIdentifier` is identifiers minus built-in identifiers, possibly plus `dynamic`) cannot be used as import prefix names or class/mixin/extension names. That's why they cannot be used before a `.` in a "qualified name" position because the part before the `.` is always a prefix or class/mixin/extension (or both for the three-parter).

The `identifier` production includes built-in identifiers, but not reserved words. 
That bug is also in the most recent spec.

**Comment by eernstg** [comment] 2020-12-01 17:04
Good catch indeed, @kaby76! The non-terminal `<qualifiedName>` (recently renamed from `<qualified>` that you may encounter via git blame), doesn't have an obvious and precise interpretation, and that's probably a major reason why we have this discrepancy.

When `qualifiedName` is used to define `<constructorDesignation>` it must denote a class, and that justifies `<typeIdentifier>` as the first alternative. The alternative `<typeIdentifier> '.' <identifier>` covers both "`myImportPrefix.SomeClass`" and the constructor name "`SomeClass.someName`", and `<typeIdentifier> '.' <identifier>` is the tightest sentential form that covers both of those (hence, the one that yields the strongest reduction of parsing ambiguity). Finally, `<typeIdentifier> '.' <typeIdentifier> '.' <identifier>` is precisely what we need in order to cover "`myImportPrefix.SomeClass.someName`". So `<qualifiedName>` is actually a good match for the usage in `<constructorDesignation>`.

However, it doesn't match the usage in `<metadata>`: It must definitely allow `'@' <identifier>` such that we can use `@myConstVariable`.

So I'm adjusting `<qualifiedName>` to cover the cases with a period only, and adding the `<identifier>` respectively `<typeIdentifier>` to the two locations where it is used.

Cf. https://dart-review.googlesource.com/c/sdk/+/174540, https://github.com/dart-lang/language/pull/1344.

**Comment by eernstg** [comment] 2020-12-01 17:08
@kaby76 wrote:
> Dart.g should really be named Dart.g4

I did not rename the file, because it has been mentioned in various contexts over a period of several years, and a rename will break existing bookmarks/links. But do note that the comment at the beginning of the file says

> Updated to use ANTLR v4 rather than antlr3

**Comment by kaby76** [comment] 2020-12-01 17:12
Good. I have more issues and will raise those soon (expressions). I have some very very minor changes to the spec also so it's more consistent for scraping. Do you all have a regression test library for the parser? I'm using the Flutter source, but I assume there is more.

**Comment by eernstg** [comment] 2020-12-01 17:30
I'm running the spec parser on the SDK [test directories, especially language and language_2](https://github.com/dart-lang/sdk/tree/master/tests), in order to keep Dart.g in sync with the actual language. We should run it continuously, but that hasn't been sufficiently high on the priority list yet.

**Comment by modulovalue** [comment] 2023-12-10 17:38
@eernstg it seems like this issue was fixed in https://github.com/dart-lang/language/pull/1344 and so it can be closed?

**Comment by eernstg** [comment] 2023-12-10 22:08
Right, thanks!

**Closed by eernstg** 2023-12-10 22:08 UTC
Labels: bug, specification
