### ISSUE TITLE
Type inference for parameters with default value

### ISSUE THREAD

**Issue by hugocbpassos** [dart-lang/language#843] opened 2020-02-17 15:10 UTC
When declaring a function parameter with default value, the parameter's type is not inferred. E.g.:

```dart
void main() {
  final foo = 0; // Inferred as int.
  bar('Hey'); // This works. Why can't `qux` be inferred as int as well?
}

void bar([final qux = 0]) {}
```

For the sake of consistency, I'd expect `qux` to be inferred as int.

I'm not sure whether this behavior is intended or someone just accidentally missed this point.

**Comment by eernstg** [comment] 2020-02-18 10:22
This is already requested in #605. Closing this as a duplicate of #605, please follow up there.

**Closed by eernstg** 2020-02-18 10:22 UTC
Labels: feature, state-duplicate

**Comment by hugocbpassos** [comment] 2020-02-18 13:42
Sorry, I failed find it in my researches.

**Comment by eernstg** [comment] 2020-02-18 13:47
No problem, it's not always easy to find. ;-)
