### ISSUE TITLE
abstract class with factory

### ISSUE THREAD

**Issue by tbm98** [dart-lang/language#1027] opened 2020-06-13 03:19 UTC
Hi.
I have problem
```
Future<List<DBParseable>> getAllData(String tableName) async {
    final List<Map<String, dynamic>> maps = await _db.query(tableName);

    switch (tableName) {
      case Schedule.table:
        return List.generate(maps.length, (i) {
          return Schedule.fromJson(maps[i]);
        });
      case Mark.table:
        return List.generate(maps.length, (i) {
          return Mark.fromJson(maps[i]);
        });
      case Profile.table:
        return List.generate(maps.length, (i) {
          return Profile.fromJson(maps[i]);
        });
    }

    return null;
  }
```
as above function. If I want to parse object by factory `.fromJson` I can't use generic type because abstract class don't support factory without body.
If abstract class support factory I can do as below
```
abstract class DBParseable {
  String get tableName;
  Map<String, dynamic> toJson();
  factory fromJson(Map<String,dynamic> json);
}

Future<List<T>> getAllData<T extends DBParseable>(String tableName) async {
    final List<Map<String, dynamic>> maps = await _db.query(tableName);

    return List.generate(maps.length, (i) {
          return T.fromJson(maps[i]);
        });

    return null;
  }
```

**Comment by eernstg** [comment] 2020-06-13 10:33
This topic may be a duplicate of https://github.com/dart-lang/language/issues/356, or at least closely related.

**Closed** 2020-06-20 09:33 UTC
Labels: feature, state-duplicate
