### ISSUE TITLE
Deconstructing lambda parameters

### ISSUE THREAD

**Issue by spkersten** [dart-lang/language#3107] opened 2023-05-24 14:04 UTC
I would like to be able to do deconstruct parameters to lambdas like:
```dart
someMap.entries.where((MapEntry(key: id, value: name)) => ...)
```
similarly to how it's already possible to do so for for-loops:
```dart
for (final MapEntry(key: id, value: name) in someMap.entries) {
  ...
}
```

**Comment by mraleph** [comment] 2023-08-08 21:21
Duplicate of https://github.com/dart-lang/language/issues/3001

**Closed by mraleph** 2023-08-08 21:21 UTC
Labels: feature
