### ISSUE TITLE
`if case` should be negatable

### ISSUE THREAD

**Issue by feinstein** [dart-lang/language#3865] opened 2024-06-01 10:44 UTC
Sorry if this issue already exists, but I couldn't find anything about this is the search.

I think it would be very useful if we could negate a `if-case` statement. In my code I wanted to execute something only if a pattern match happened, but I couldn't, so the only other option was using an `else` with an empty `if-case` body, which looked very ugly.

What I wanted:

```dart
// test case for when a particular go_router route is not the current route:
final matches = router.routerDelegate.currentConfiguration.matches;
if (matches case! [RouteMatchBase(matchedLocation: '/home'), ImperativeRouteMatch(matchedLocation: '/details')]) {
  fail('No route found');
}
```

What I can do now:

```dart
final matches = router.routerDelegate.currentConfiguration.matches;
if (matches case [RouteMatchBase(matchedLocation: '/home'), ImperativeRouteMatch(matchedLocation: '/details')]) {
  // Empty body because I can't negate the if-case
} else {
  fail('No route found');
}
```

**Comment by lrhn** [comment] 2024-06-01 12:29
The main reason there is no negation of a pattern match, is that most pattern matches include capture variables, which are only available on the positive branch.
You have a pattern with no captures, which is why it makes sense to only care about the false branch.

I'm not sure that comes up often enough that it warrants specialized syntax.
You can also use a switch:
```dart
  switch (matches) {
    case [RouteMatchBase(matchedLocation: '/home'), ImperativeRouteMatch(matchedLocation: '/details')]: break
    default: fail('No route found');
  }
```

I'd consider it more likely (not highly likely, but more) that we'd allow `(expression case pattern)` and `(expression case pattern when expression)` as an *expression*, fully parenthesized, and not just as an entire `if` *condition*, #3062. That would allow you to write:
```dart
  if (!(matches case [RouteMatchBase(matchedLocation: '/home'), ImperativeRouteMatch(matchedLocation: '/details')])) {
    default: fail('No route found');
  } 
```

**Comment by feinstein** [comment] 2024-06-01 12:59
Wouldn't it run into the same issue?

I think we would expect a runtime exception or a compile time warning, if we tried to access a variable inside a pattern that was not matched.... Or a limitation that `case!` can't define variables for pattern matching.

**Comment by tatumizer** [comment] 2024-06-01 15:04
See #1548

**Comment by mmcdon20** [comment] 2024-06-01 15:58
C# has similar pattern matching features to dart, except they also have a `not` pattern:

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/patterns#logical-patterns

```c#
if (input is not null)
{
    // ...
}
```

And pattern matches are also expressions:

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/is

```c#
static bool IsFirstFridayOfOctober(DateTime date) =>
    date is { Month: 10, Day: <=7, DayOfWeek: DayOfWeek.Friday };
```

**Comment by Wdestroier** [comment] 2024-06-01 19:03
You can find this syntax suggestion in issue #2537.

The scoping rules of `case!` would be similar to Java patterns:
![image](https://github.com/dart-lang/language/assets/14764307/e6d3a661-0d8d-4378-8ebd-06abb56b93ac)

Java doesn't have an instanceof! / is not / is! operator, I belive most people would prefer `if (shape instanceof! Rectangle)` over `if (!(shape instanceof Rectangle))`, the same idea applies to `if (shape case! Rectangle(final x, final y))` over `if (!(shape case Rectangle(final x, final y)))`. Thus, `if (a case! b)` and `if (!(a case b))` need to coexist.

**Comment by tatumizer** [comment] 2024-06-01 22:30
@Wdestroier : java doesn't allow shadowing. If you replace "Rectangle r" by "Rectangle s", the compiler will complain. In dart, shadowing is quite common in "case" conditions.

**Comment by munificent** [comment] 2024-07-11 23:43
Thanks @tatumizer. Yes, I think this request is essentially a duplicate of #1548, or at least close enough that merging the issues is more helpful than not.

**Closed by munificent** 2024-07-11 23:43 UTC
Labels: feature, patterns
