### ISSUE TITLE
Why can not infer type by argument

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/language#1743] opened 2021-07-15 10:27 UTC
the code:
```dart
void main(List<String> args) {
  var foo = Foo('aaaaa');
  test(foo, (a) {
    // flag, error, can not infer a is Foo, i must use Foo a
    print(a.name);
  });
}

typedef DisposingFunc<T> = void Function(T);

class Foo {
  String name;
  Foo(this.name);
}

void test<T extends Object>(T instance, DisposingFunc<T> dispose) {
  dispose(instance);
}
```

**Comment by eernstg** [comment] 2021-07-15 11:55
The inference failure occurs for the same reasons as the ones that are discussed in https://github.com/dart-lang/language/issues/731.

The main point is that type inference involving subtyping and unification is intractable, so Dart type inference can't use unification. A major difference between unification based type inference and the given type inference in Dart is that the latter won't transfer information from one actual argument to another one during inference of a function invocation. So the fact that instance is a `Foo` won't provide information to the inference on the 2nd argument, and hence it doesn't infer that its parameter should have type `Foo`.

I'll close this issue as a duplicate of https://github.com/dart-lang/language/issues/731, please refer to that one if you wish to keep an eye on this topic.

**Closed by eernstg** 2021-07-15 11:55 UTC
Labels: request
