### ISSUE TITLE
Functional Interfaces

### ISSUE THREAD

**Issue by Vorkytaka** [dart-lang/language#4187] opened 2024-12-01 00:01 UTC
**Description**:

I would like to propose a new feature for the Dart programming language to introduce functional interfaces (fun interface). This feature would enhance Dart's type system and interoperability, especially in scenarios involving lambda expressions and functional programming patterns.

**Motivation**:

- **Simplification**: By allowing functional interfaces, developers can simplify single-method interface implementations, encouraging more concise and readable code.
  
- **Interoperability**: Functional interfaces are a common concept in other languages (like Kotlin), which would make Dart more appealing to developers familiar with these paradigms.

- **Expressiveness**: It provides developers with the ability to enforce single-method contracts in a more formalized manner. This can increase code expressiveness and intent clarity.

**Proposal**:

Introduce a new keyword `fun interface` that allows defining functional interfaces in Dart. This would allow a class to implement a single abstract function defined by the interface. The concept is similar to function typedefs but with enforced interface constraints.

**Example**:
```dart
typedef MyFunction = String Function(int number);

fun interface class MyClass implements MyFunction {
  String myFunction(int number);
}
```

**Details**:

- The fun interface construct would ensure that the implementing class has exactly one abstract method corresponding to the signature defined in the typedef.
- Enforces compile-time checks to ensure no additional abstract methods are present, similar to single-method interfaces in other programming languages.
- This pattern allows for cleaner integration with Dart's existing function types and lambda expressions.

**Comment by tatumizer** [comment] 2024-12-01 00:51
I tried to wrap my head around Kotlin's `fun interfaces` - the use case for them is unclear (after all, you can just pass a function, like in any method of Iterable). Found [this thread](https://stackoverflow.com/questions/69845785/why-is-the-purpose-of-functional-interfaces-in-kotlin) - it seems no one knows why they need `fun interfaces` other than for java interoperability (which is not a goal for dart). Could you provide a real non-trivial example - e.g. by re-imagining any method of Iterable (e.g. `where`) in terms of fun interfaces and demonstrating the advantages?

**Comment by mateusfccp** [comment] 2024-12-01 01:15
Seems like a duplicate of #3889?

Honestly, I don't see what they can achieve that a regular type definition/high-order function can't.

**Comment by Vorkytaka** [comment] 2024-12-01 10:46
The idea I see is to be able to pass instances of classes to wherever a function is needed.

So, with:
```
// Our function type
typedef MyType = String Function(int a);

// Fun interface
fun interface class MyInterface {
  String method(int a);
}

// Our implementation
final class MyClass implements MyInterface {
  String method(int a) => '$a';
}

// Some place where we use our function
void someFun(MyType function) {}
```

Instead of `someFun(MyClass().method` we can do `someFun(MyClass())`.

**Comment by mateusfccp** [comment] 2024-12-01 11:07
What are the benefits of doing it this way instead of using what we have today?

```dart
void main () {
  final myClass = MyClass();
  
  someFun(myClass);
}

// Our function type
typedef MyType = String Function(int a);

// Fun interface
abstract interface class MyInterface {
  String call(int a);
}

// Our implementation
final class MyClass implements MyInterface {
  String call(int a) => '$a';
}

// Some place where we use our function
void someFun(MyType function) {}
```

**Comment by mateusfccp** [comment] 2024-12-01 15:04
I don't know how valuable it is to force the implementation to be single-method, but this can be better solved with a linter.

I don't think they would want to add this to Dart's default lints, though, so you would have to write a custom linter for this.

**Comment by lrhn** [comment] 2024-12-01 20:38
Dart moved away from allowing interfaces to implement function types in Dart 2.0 because it didn't interact well with generics and sound typing.
If you could have:
```dart
class C<T> implements int Function(T) {
  int call(T value) => "$value".length;
}
```
then the class is both covariant and contravariant in `T`, depending on whether you look at the class generics or the function type.
That's bad for sound subtyping.
```dart
void main() {
  var c = C<int>();
  C<Object> o = c; // Generic up-cast
  void Function(Object) f = o; // Function type up-cast.
  f("not an int"); // Where should this call fail?
}
```

This proposal has the same issue, so it's unlikely that Dart will do something like that.
(Even with variance annotations, it's safer to just rely on tear-offs than passing non-function objects around typed as function types. And easier to optimize.)

**Closed by lrhn** 2024-12-01 20:38 UTC
Labels: feature
