### ISSUE TITLE
Cannot have a const constructor even if members are const-constructible?

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/language#819] opened 2020-02-06 00:35 UTC
We'd like to have code like:

```dart
class Foo {
  const Foo(this.value);

  final int value;
}

class FooDelegate implements Foo {
  final Foo _foo;

  const FooDelegate(int value) : _foo = Foo(value); // Line 10

  @override
  int get value => _foo.value;
}
```
but this fails with:

> error • Invalid constant value. • const_delegate.dart:10:41 • invalid_constant

We could remove `const` from the `FooDelegate` constructor, but without it `FooDelegate` is no longer perfectly substitutable for `Foo` (`const foo = FooDelegate(1);` would fail).

It would be nice if there were some way for a `const` constructor to `const`-construct members if possible.

**Comment by eernstg** [comment] 2020-02-06 15:20
Cf. https://github.com/dart-lang/sdk/issues/20962.

**Comment by eernstg** [comment] 2020-02-07 10:13
dart-lang/sdk#20962 was moved to this repo, where it should be; marking this as duplicate of #819, and closing.

**Closed by eernstg** 2020-02-07 10:13 UTC
Labels: request, state-duplicate
