### ISSUE TITLE
Add a mechanism to check if a late variable is initialised

### ISSUE THREAD

**Issue by hrajwade96** [dart-lang/language#4196] opened 2024-12-06 08:15 UTC
At present there is no way to check if a late variable is actually initialised or not, 
Can we add a way to check this?
for example in Kotlin we can check if a lateinit variable is initialised :
[Kotlin lateinit variables](https://www.geeksforgeeks.org/lateinit-variable-in-kotlin/)

If someone can point to where this code needs to be modified I can also work on this PR.

**Comment by julemand101** [comment] 2024-12-06 11:05
Sounds like a duplicate of: https://github.com/dart-lang/language/issues/1028

**Comment by mateusfccp** [comment] 2024-12-06 11:18
> Sounds like a duplicate of: https://github.com/dart-lang/language/issues/1028

This one is closed, I think #3680 is equivalent and is still open.

**Comment by lrhn** [comment] 2024-12-06 14:40
I think #1028 is the best fit (and it being closed is a big hint that this is an unlikely feature to happen, at least by itself).

The #3680 does include a `??` operator for late variables, but I'd not expect that operator to be added alone, only if it's part of the change that also adds late *parameters*. For late variables, you're expected to know whether they're initialized.

But definitely a duplicate of one or the other.

**Closed by lrhn** 2024-12-06 14:40 UTC
Labels: feature
