### ISSUE TITLE
really need to 'required' keyword?!

### ISSUE THREAD

**Issue by hpn33** [dart-lang/language#1591] opened 2021-04-17 13:26 UTC
dart 2.12.0

``` dart
void a(String title, {required String description, String? body}) {}
```

not need to required
if is not null so by default is required and not need to write required keyword
``` dart
void a(String title, {String description, String? body}) {}
```

why have it, now?

**Comment by hpn33** [comment] 2021-04-17 13:29
maybe is a short solution for code analyzer to understand code
And will be improved in the future

**Comment by mateusfccp** [comment] 2021-04-17 13:59
Duplicate of #878.

**Closed** 2021-04-18 09:57 UTC
Labels: feature, state-duplicate
