### ISSUE TITLE
Allow `case` condition in return statement

### ISSUE THREAD

**Issue by RepliedSage11** [dart-lang/language#4092] opened 2024-09-12 16:49 UTC
Trying to refactor a simple function that validates a `Uri`:
```dart
bool _validateUri(Uri uri) {
      return uri.path == '/path' &&
          uri.queryParameters['param1'] == 'param1' &&
          uri.queryParameters['param2'] == 'param2' &&
          uri.queryParameters['param3'] != null &&
          uri.queryParameters['param4'] != null;
}
```

 I have followed my instincts and wrote this code using patters:
 ```dart
 bool _validateUri(Uri uri) {
      return uri.path == '/path' && uri.queryParameters case {
          'param1': 'param1',
          'param2': 'param2',
          'param3': String _,
          'param4': String _,
      };
}
 ```
and found out that I can't use `case` conditions anywhere outside an `if`. Furthermore, when I changed the code to use an `if` condition I found out that I can only use a single `case` condition in the `if`.

I got this to work with a `switch` and a single pattern:
```dart
bool _validateUrl(Uri uri) {
    return switch (uri) {
      Uri(
        path: '/path',
        queryParameters: {
         'param1': 'param1',
          'param2': 'param2',
          'param3': String _,
          'param4': String _,
        },
      ) => true,
      _ => false,
   };
}
```

But this approach requires me to explicitly return true and have a default false case, when all I want is to just return a bool result of "this variable did(n't) match this pattern".

In my opinion it would be useful and intuitive to be able to use `case` conditions outside of `if` and to chain multiple conditions with `case`. This might be two separate issues, but this was my thought process when trying to refactor this function.

**Comment by mateusfccp** [comment] 2024-09-12 17:02
Seems like a duplicate of (or redirectly related to) #3059. If we have `case` expressions that evaluate to `bool`, you can achieve this (and much more, like using them in ternary, `while`, `for`, negating etc.)

**Comment by RepliedSage11** [comment] 2024-09-12 17:29
Sorry, I tried searching for already opened issues, but didn't stumble upon that one. There is a [comment](https://github.com/dart-lang/language/issues/3059#issuecomment-1847276046) describing exactly what I wanted to do. So I guess this is a duplicate, but that issue didn't have any activity for some time.

**Comment by mateusfccp** [comment] 2024-09-12 17:39
If you feel like #3059 solves your problem, please, close this issue. Any relevant discussion can be kept in there.

**Closed** 2024-09-12 18:01 UTC
Labels: request
