### ISSUE TITLE
Testing an assignment against `null` does not promote the assigned variable (unchecked_use_of_nullable_value)

### ISSUE THREAD

**Issue by Hixie** [dart-lang/language#2583] opened 2022-10-20 23:01 UTC
```dart
int? test() => null;

void main() {
  int? foo;
  while ((foo = test()) != null) {
    foo.toDouble(); // error • The method 'toDouble' can't be unconditionally invoked because the receiver can be 'null'
  }
}
```

**Comment by srawlins** [comment] 2022-10-21 14:21
I think this is essentially https://github.com/dart-lang/language/issues/1420?

**Comment by stereotype441** [comment] 2022-10-21 15:16
@srawlins good catch.  It looks like #1420 covers multiple suggestions, and #1844 specifically covers this request, so I'll mark as a duplicate of #1844.

**Comment by stereotype441** [comment] 2022-10-21 15:16
Duplicate of #1844.

**Closed by stereotype441** 2022-10-21 15:16 UTC
Labels: small-feature, flow-analysis
