### ISSUE TITLE
Allow "let" instead of "final"

### ISSUE THREAD

**Issue by cliftonlabrum** [dart-lang/language#3231] opened 2023-07-21 17:37 UTC
Currently we used `final` to declare an immutable variable. 

I think it would be great to use `let` for the same thing (similar to the Swift language). It would help reduce the number of keystrokes needed and help the code be slightly less verbose. 😊

Thanks for a great language!

**Comment by lrhn** [comment] 2023-07-21 18:22
Not a bad idea. Also not a new one 😁 
Duplicate of #136 (and #2868).

**Closed by lrhn** 2023-07-21 18:22 UTC
Labels: feature
