### ISSUE TITLE
Constructor tear-off with constant expressions

### ISSUE THREAD

**Issue by albertodev01** [dart-lang/language#2812] opened 2023-02-02 12:19 UTC
Consider this class

```dart
class Example {
  const Example();
}
```

I am able to compile and run this code with Dart 2.19.1:

```dart
void main() {
  final myClass = Example.new;
  print(identical(myClass, const Example())); // false
}
```

That is what I expect. However, I do **not** expect this to return `false`:

```dart
void main() {
  const myClass = Example.new;
  print(identical(myClass, const Example())); // false (but why??)
}
```

The `const` modifier cannot be assigned to something that is not a compile-time constant. As such, I assume that (somehow) the `Example.new` is treated as a compile-time constant. The code prints `false` but I would expect `true` because I've created an object using `const`.

Is this working as intended?

---

In this case, I would expect to either:

  1. Get an error, because `.new` does not return a constant when using `const`
  2. Use a different constructor, such as `Example.const`

Thank you 🙂

**Comment by ykmnkmi** [comment] 2023-02-02 12:47
I think your example should look like this:
```dart
void main() {
  const myClass = Example.new; // is a function
  print(myClass is Function); // true, unnecessary_type_check
  print(identical(myClass(), const Example())); // false (but why??)
}
```

**Comment by mateusfccp** [comment] 2023-02-02 12:50
@albertodev01 

In the expression `const myClass = Example.new`, `myClass` is the constant functions that create the `Example`. Thus, a it's different to the constant instance of `Example`.

Using `const myClass = Example.new()` will get you the expected result.

**Comment by eernstg** [comment] 2023-02-02 13:10
Closing&mdash;I think this issue has been resolved, and everything is working as intended:

```dart
class Example {
  const Example();
}

void main() {
  // A function creating new instances of `Example`.
  const myClass = Example.new;

  // 'false', the function and the `Example` are not the same object.
  print(identical(myClass, const Example()));

  // 'false', `myClass()` is a dynamically created `Example`, not the canonical instance.
  print(identical(myClass(), const Example()));

  // Error, `myClass()` is not a constant expression, so `myClass` can never deliver a constant instance.
  // const myInstance = myClass();
}
```

The precise rules about constant expressions and constructor tear-offs are listed here: https://github.com/dart-lang/language/blob/master/accepted/2.15/constructor-tearoffs/feature-specification.md#constant-expressions.

**Closed by eernstg** 2023-02-02 13:10 UTC
Labels: request
