### ISSUE TITLE
"this" should respect null-aware flow analysis

### ISSUE THREAD

**Issue by nex3** [dart-lang/language#1520] opened 2021-03-13 23:16 UTC
If I'm writing an extension method on a nullable type, checking `this == null` or `this != null` should have the same effect on the inferred type of `this` in a local scope as assigning it to a variable would, since there's no way for the nullability of the current object to change in that scope. For example, the following should be valid but currently is not:

```dart
extension NullableExtension<T> on T? {
  V? andThen<V>(V Function(T value) fn) {
    return this == null ? null : fn(this);
  }
}
```

**Comment by tatumizer** [comment] 2021-03-14 01:21
Isn't it a special case of a more general issue? https://github.com/dart-lang/language/issues/1397

**Comment by lrhn** [comment] 2021-03-15 11:17
This is a duplicate of #1397.

**Closed by lrhn** 2021-03-15 11:17 UTC
Labels: bug
