### ISSUE TITLE
local variable looses promoted type in closure, in the presence of a re-assignment

### ISSUE THREAD

**Issue by srawlins** [dart-lang/language#1675] opened 2021-06-09 16:03 UTC
(Note I have a very amateur understanding of flow analysis)

Take this code:

```dart
void f(String? s, List<int> lengths) {
  for (;;) {
    if (s == null) return;
    
    if (1==2) break;
    s = "not null";
  }
  s.length; // OK
  
  // The property 'length' can't be unconditionally accessed because the receiver can be null.
  lengths.any((e) => e == s.length);
}
```

So after the for loop, `s` is promoted to `String`. `s.length` is then OK. But later on, in a closure, `s.length` is not OK; analyzer and CFE say that `s` is a `String?`.

I know that there is not a lot of flow analysis or promotion going on within closures, but there is _some_. In this simpler example, which contains zero re-assignments, we get no errors:

```dart
void f2(String? s, List<int> lengths) {
  if (s == null) return;
  
  lengths.any((e) => e == s.length);
}
```

So I'm guess something about the re-assignment (with a `String` value, note) throws a lot of flow analysis or promotion out the window.

Bug? Feature? I perused for other promotion bugs but didn't find anything like this.

**Comment by srawlins** [comment] 2021-06-09 16:05
cc @jeffkwoh @stereotype441

**Comment by srawlins** [comment] 2021-06-09 16:07
(I'm looking at this in DartPad, by the way, using Dart 2.13.1)

**Comment by jeffkwoh** [comment] 2021-06-10 13:33
Thank you for reproducing and filing this here :)

**Comment by leafpetersen** [comment] 2021-06-10 18:27
Duplicate of https://github.com/dart-lang/language/issues/1536 .

**Closed by leafpetersen** 2021-06-10 18:27 UTC
Labels: request
