### ISSUE TITLE
multiple return

### ISSUE THREAD

**Issue by sleepreading** [dart-lang/language#1384] opened 2020-12-24 02:27 UTC
Sorry for my poor English!

golang:
`a, b = GetTwoThings()`

It's easy to process err:

We like this feature so much!!

It would be great if you put this feature into dart.
It **must be a language feature**, rather than implemented by a package, like tuple or something else.

I think we all prefer to write code like this:
```
rsp, errmsg = await HttpUtil.Get('...');
if (errmsg.isNotEmpty) {
 ...
 return;
}
process(rsp);
```

**Comment by mateusfccp** [comment] 2020-12-24 17:18
This is a duplicate of #68, and is going to be solved with the [patterns](https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md) feature.

**Closed** 2020-12-27 12:16 UTC
Labels: feature
