### ISSUE TITLE
Using generic type as Type

### ISSUE THREAD

**Issue by CareF** [dart-lang/language#1010] opened 2020-06-06 17:26 UTC
Currently we cannot use generic types as Type argument. For example if I have a function `foo(Type t)`, `foo(int)` and `foo(Object)` are valid, but `foo(List<int>)` is not, with error message 
> Error: A comparison expression can't be an operand of another comparison expression.

I don't know if there's any reason to parse`<` in `(List<int>)` as comparison. 

I am told that one workaround is: 
```
class TypeOf<T> {
  Type get type => T;
}

TypeOf<List<int>>().type
```
or 
```
Type typeOf<T> () => T;

typeOf<List<int>>()
```

Another way I did is using `<int>[].runtimeType`. 

One problem with all these solutions are it cannot generate a `const Type`. 

But I'm thinking maybe including such parser would be more elegant in the language.

**Comment by lrhn** [comment] 2020-06-08 09:56
Duplicate of #123 

(So we are aware of the issue, but there is currently no solution).

**Closed by lrhn** 2020-06-08 09:56 UTC
Labels: request, state-duplicate
