### ISSUE TITLE
Abstract private getter...

### ISSUE THREAD

**Issue by luiges90** [dart-lang/language#3573] opened 2024-01-18 07:13 UTC
...should not be allowed, since it makes no sense to create a field that has no implementation but cannot be overriden. But apparently one can actually create such a thing which guarantees a runtime error when executed.

I would expect at least a warning if not an error from the compiler or linter if such a code is written. But currently there are no guard against it.

I suppose this should also apply to setters, methods and so on.

*m.dart*
```
mixin M {
  int get _x; // This line declares an abstract private getter, since it starts with an underscore but no implementation is provided.

  int get2X() {
    return 2 * _x;
  }
}
```

*c.dart*
```
import 'm.dart';

class C with M {
  // This does not override _x in M! adding @override here do get a warning from lint however
  int get _x => 12;

  int getX() {
    return _x;
  }
}
```

*main.dart*
```
import 'c.dart';

void main() {
  final c = C();
  print(c.getX()); // this print 12, as expected.
  print(c.get2X()); // this line crashes.
}
```

when main is run, you get:
```
NoSuchMethodError: Class 'C' has no instance getter '_x'.
Receiver: Instance of 'C'
Tried calling: _x
```

**Comment by julemand101** [comment] 2024-01-18 07:38
> ...should not be allowed, since it makes no sense to create a field that has no implementation but cannot be overriden. But apparently one can actually create such a thing which guarantees a runtime error when executed.

You can override it if the mixin and class are part of the same library. E.g. do this in the same file and it works:
```dart
mixin M {
  int get _x;

  int get2X() {
    return 2 * _x;
  }
}

class C with M {
  @override
  int get _x => 12;

  int getX() {
    return _x;
  }
}

void main() {
  final c = C();
  print(c.getX()); // 12
  print(c.get2X()); // 24
}
```

**Comment by luiges90** [comment] 2024-01-18 12:12
> > ...should not be allowed, since it makes no sense to create a field that has no implementation but cannot be overriden. But apparently one can actually create such a thing which guarantees a runtime error when executed.
> 
> You can override it if the mixin and class are part of the same library. E.g. do this in the same file and it works:
> 
> ```dart
> mixin M {
>   int get _x;
> 
>   int get2X() {
>     return 2 * _x;
>   }
> }
> 
> class C with M {
>   @override
>   int get _x => 12;
> 
>   int getX() {
>     return _x;
>   }
> }
> 
> void main() {
>   final c = C();
>   print(c.getX()); // 12
>   print(c.get2X()); // 24
> }
> ```

Yes I am aware of this. But I think the linter should still warn about this issue.

**Comment by jakemac53** [comment] 2024-01-18 17:51
It seems to me that this can be allowed, but it should be an error to use that mixin without providing a real implementation of that private getter, just like it would if it was public?

**Comment by rubenferreira97** [comment] 2024-01-18 19:42
Cf. #3340.  Seems close to this issue.

**Comment by munificent** [comment] 2024-01-24 23:51
Yeah, I think this is close enough to be a duplicate of #3340.

**Closed by munificent** 2024-01-24 23:51 UTC
Labels: feature
