### ISSUE TITLE
I cannot Combining various classes to create a new composite class well.

### ISSUE THREAD

**Issue by Stitch-Taotao** [dart-lang/language#3542] opened 2024-01-05 08:49 UTC
I wish for easy composition between my classes，I aim to achieve this through the use of mixins，later I will show why must mixin.

Assuming, there is an animation library available, and its behavior can be entirely encapsulated using the classes I have written

 Suppose I currently have the following class inheritance diagram for a set of functional classes

![image](https://github.com/dart-lang/language/assets/26296915/c324cffe-949b-48e4-91d9-45df02b279b1)

I am breaking down all the functionalities into individual components and then assembling them into an aggregated class ，that is `Spirit`. （A sprite is a disabled one-eyed cat.）

If the animation lib expose a widget called `OhtersAnimationWidget`,we must extends `OhtersAnimationWidget` and change it's behavior, So my custom widget maybe like this:
```
class MyImpl extends OhtersAnimationWidget with  Spirit {}
```
That's why I must use mixin . this is just one example ,**Believe there will be many scenarios where it is necessary to inherit classes from other libraries and then add customizations to them.**

What I've done is break down some complex operations, allowing for flexible combinations during customization to reduce workload. This way, not every customization requires a complete rewrite of a class. It’s very convenient using composition .

Due to current limitations in Dart, to break down a sprite, I have to split each part into mixins.

```

mixin Animal {
  int get age;
}

mixin BiteableAnimal on Animal {}

mixin Disability {
  String get disabilityDesc;
}

mixin Cat on BiteableAnimal {
  @override
  late int age;
  init() {
    age = 4;
  }
}

mixin OneEyeCat on Cat, Disability {
  @override
  String get disabilityDesc => "just one eye";
}

mixin Creature {}

mixin Spirit on Creature, OneEyeCat {
  void useMagic() {
    print("use magic");
  }
}
```

This is quite weird, and when I want to implement MyImpl, I must do it this way：

`class MyImpl extends OhtersAnimationWidget with Animal, BiteableAnimal, Cat, Disability, OneEyeCat, Creature, Spirit {}
`
`class MyImpl2 extends OhtersAnimationWidget with Animal, BiteableAnimal, Cat, Disability, OneEyeCat, Creature , Spirit ,... , Ohter {}
`
If I impl a second class ,If inheritance chain becomes longer , eg if you need to inherit from Z,you need to list them one by one.
` MyImpl3 extends OhtersAnimationWidget with A, B, C, D, E, F, G,...,X,Y,Z{}`

For previous Dart versions, I can use abstract class working in conjunction with mixin.

I can use abstract class as intermediate layer :

`abstract class SpiritBase with Animal, BiteableAnimal, Cat, Disability, OneEyeCat, Creature{}`
`class MyImpl extends OhtersAnimationWidget with SpiritBase ,Spirit {}`
`class MyImpl2 extends OhtersAnimationWidget with SpiritBase ,Spirit ,... , Ohter{}`
`abstract class ZBase with A, B, C, D, E, F, G,...,X,Y{}`
`class MyImpl3 extends OhtersAnimationWidget with ZBase ,Z{}`

Can anyone tell me Why Dart  give limition on mixin and abstract class , now it's very inconvenient ，If abstract class can use like mixin ,I can write code more esaliy 

```
abstract class Animal {
  int get age;
}

abstract class BiteableAnimal extends Animal {}

abstract class Disability {
  String get disabilityDesc;
}

abstract class Cat extends BiteableAnimal {
  @override
  late int age;
  init() {
    age = 4;
  }
}

abstract class OneEyeCat with Cat, Disability {
  @override
  String get disabilityDesc => "just one eye";
}

abstract class Creature {}

abstract class Spirit with Creature, OneEyeCat {
  void useMagic() {
    print("use magic");
  }
}
```

Now MyImpl  is just written : `class MyImpl extends OhtersAnimationWidget with Spirit {}`
Using `abstract class extends` and `abstract class with` looks more readable than all `mixin on、mixin on ...`

**Question:**
   Can we revert to the previous implementation of abstract class or come up with a more flexible and composable solution?

**Comment by lrhn** [comment] 2024-01-05 16:06
What you want is composite mixins. #540 

It's a good idea, but it has never been a high enough priority to become a reality.

**Comment by munificent** [comment] 2024-01-09 21:50
Closing as a duplicate of #540. (I agree it's a good idea and I'd like it too.)

**Closed by munificent** 2024-01-09 21:50 UTC
Labels: request
