### ISSUE TITLE
Turn `throw` into an expression returning `Never`

### ISSUE THREAD

**Issue by derolf** [dart-lang/language#1443] opened 2021-02-08 09:38 UTC
The following construct allows writing `throw` as the right-side of the `??`-operator:

```Dart
Never throww(Object e) => throw e;

class Foo {
  String? bar;
  void doBar() {
    final bar = this.bar ?? throww(ArgumentError('bar not set'));
    print(bar);
  }
}
```

However, the `throww`-workaround would not be required if the built-in `throw` would be an expression returning `Never`.

**Comment by mraleph** [comment] 2021-02-08 09:47
This should already work, note the parenthesis:

```dart
final bar = this.bar ?? (throw ArgumentError('bar not set'));
```

**Comment by derolf** [comment] 2021-02-08 09:51
Ah, nice! Would it be possible to modify the language in order to allow that construct without parenthesis?

**Comment by leafpetersen** [comment] 2021-02-10 02:03
@lrhn @eernstg do you have any idea why `throw` wasn't made to bind more tightly?

**Comment by eernstg** [comment] 2021-02-10 10:32
I think the point is that we don't want `throw` to throw part of an expression: `throw a.b()` shouldn't mean `(throw a).b()`. So `<throwExpression>` is `'throw' <expressio>`, which allows the thrown thing to be any expression whatsoever. I think we might cause real breakage if we change this, e.g., because `throw b ? e1 : e2` would then mean `(throw b) ? e1 : e2`.

The next thing to consider is the fact that `<ifNullExpression>` is `<logicalOrExpression> ('??' <logicalOrExpression>)?`, which means that the part behind the `??` can't go above `<logicalOrExpression>`, i.e., it can't be an `<ifNullExpression>`, `<conditionalExpression>`, `<cascade>`, an assignment, or a `<throwExpression>`.

We could do as proposed [here](https://github.com/dart-lang/language/issues/644#issuecomment-546885658):

```ebnf
<ifNullExpression> ::= 
  <logicalOrExpression> ('??' <logicalOrExpression>)*
  ('??' 'throw' <logicalOrExpression>)?
```

**Comment by lrhn** [comment] 2021-02-10 11:02
The binding was my fault. I argued for the current behavior based on you never *needing* to do `(throw e) + 2`, so without parentheses it should mean `throw (e + 2)`, and it's hard to have different precedence on the left and right of an operator, so it generally binds weaker than binary operators.

In practice, you never need either, and it's just annoying that `throw Invocation()` isn't the prefix-expression it looks like.

(This issue is a duplicate of https://github.com/dart-lang/language/issues/644, and that issue already has more discussion, so closing this one).

**Closed by lrhn** 2021-02-10 11:02 UTC
Labels: feature

**Comment by derolf** [comment] 2021-02-10 11:30
Also consider “?? return” please.

**Comment by lrhn** [comment] 2021-02-10 13:25
@derolf Considered and rejected 😉 (- at least by itself).

A `return` is not an expression, so you can't place it after a `??` to begin with. We made `throw` an expression ... for some reason I can't remember, but being used in conditionals like `x > 0 ? sqrt(x) : throw "No!"` was the likely use-case, especially in initializer lists. (Too bad we didn't make it potentially constant).

We could make other control-flow statements into expressions too, including `return`, `break`, `continue` and `rethrow`. It would make just as much sense, but might make control flow analysis more complicated if you can `break`/`continue` in the middle of an expression. (You could always throw since any function-call could throw).
They *can* work as expressions because they never have to evaluate to a value. It's a simpler change than making `switch`/`while`/`for`-like statements into expressions, those will need to actually evaluate to a value.

I'm not sure it improves readability, though. It risks people writing things like `foo ?? return null;` a statement, rather than `if (foo == null) return foo;`. I do consider that bad for readability. (But I could also be wrong).

**Comment by derolf** [comment] 2021-02-10 15:06
It's commonly used in Kotlin, where you can write:

`val foo = bar ?: return`

**Comment by derolf** [comment] 2021-02-10 15:08
Btw, indeed I like expression blocks as well, like:

```
final val = {
  final foo = 42 * 3;
  foo;
};
```
