### ISSUE TITLE
Define the macro API for introspecting on metadata annotations (and enum values)

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#1930] opened 2021-10-21 23:24 UTC
The proposal has a section discussing this, but it's written like an open-ended design discussion. We should figure out what we actually want and then pin it down in the proposal. The key question is how arguments in metadata annotations are seen by the macro. Are they actual values, or unevaluated syntax? The former might not be possible (since it may refer to code produced by macros). The latter might not be useful.

**Comment by GregoryConrad** [comment] 2023-02-19 17:46
From a user's perspective, it would be very helpful to access annotations that depend on constant macro-produced types and declarations. 

Say I have:

```dart
class InfoAnnotation {
  const InfoAnnotation(Object obj);
}

@someFunctionDeclarationMacro
void fn(
  @InfoAnnotation(macroProducedObj) int someIntParameter,
) {}
```

In the above example, `someFunctionDeclarationMacro` could do something interesting with the `macroProducedObj` and I think that it is reasonable that it should be able to get a `Declaration` object from it.

I think I see why this would be problematic as-is: there is no way to know for certain whether this `macroProducedObj` has been declared yet in phase 2 (if I am wrong here, please do correct me).

Would it be possible to hint at the order in which some phase 2 macros are evaluated to allow for this? I would hate to have to resort to build_runner to handle something like this.

I have what I think is a good solution/compromise: a macro can directly specify what other macros it "depends on." I.e., In the example above, `someFunctionDeclarationMacro` "depends on" the macro that produces the `macroProducedObj`. For my particular use case, and I imagine most others, this would be sufficient.

Seeing as a macro that that depends on declarations produced by another macro would (in most cases) have access to the other macro, the above solution makes a lot of sense to me. It would act just like dependency resolution, giving a deterministic way to run macros in phase 2.

An _anti-solution_ would be for a macro class itself to ask to be run at a certain point in phase 2, perhaps even a "phase 2.5." Obviously, nothing like this should be supported.

**Comment by GregoryConrad** [comment] 2023-02-21 01:36
I actually just realized my own use case relies on having the macro depend on other instances where it was applied; which is an issue. But, I know exactly what I want to declare in phase 1 given the `FunctionDeclaration` the macro is applied to, so then in phase 2 my macro can use those previous declarations. Will it be possible to contribute more information in a phase than is required? That seems reasonable. I have some other ideas in which this would ease implementation.

**Comment by GregoryConrad** [comment] 2023-02-27 20:21
> Is the `macroProducedObj` generated from a macro in the same library, or a dependency?

Either is possible. It could be specified in the same library, or it could be specified in an imported library (which the user must `import`). Here's a concrete example:

```dart
// library a.dart

@myMacro
int someInt() => 0;

// generated: const someIntObject = ...;


// library b.dart

import 'a.dart';

@myMacro
int someIntPlusOne(
  @C(someIntObject) int i,
) => i + 1;

// generated: const someIntPlusOneObject = ...;

@myMacro
String someStr(
  @C(someIntPlusOneObject) int i,
) => i.toString();

// generated: const someStrObject = ...;

class C {
  const C(this.object);
  final MyCustomObject object;
}
```

In the above example, `myMacro` would need to access:
1. The class of the supplied metadata annotation, in this case `C`.
2. Be able to reproduce the contents of `@C(...)` in generated code, i.e.:
```dart
int _$generatedFunction() {
  final d1 = doSomething(contentsOfTheAnnotation);
  final d2 = doSomething(contentsOfAnotherParameterAnnotation);
  return _userDefinedFunction(d1, d2);
}
```

**Comment by jakemac53** [comment] 2023-02-27 21:07
If all you need is access to the code chunk representing the argument to the annotation, then yes this should be feasible, regardless of if its referencing generated identifiers or not. But note that annotations can only reference const objects, so that may be a limitation you run into as well.

**Comment by jakemac53** [comment] 2023-04-03 15:36
It looks like we don't talk about generic type parameters for macro classes in the proposal today, I can add a note. For now at least they are going to be disallowed, for the same reasons as not being able to run user defined functions. The program in which the macro is actually running will not have access to types from the users code.

**Comment by jakemac53** [comment] 2023-07-12 16:28
@johnniwinther As I start working on this, I am wondering if the lazy constant evaluation of some platforms might make it not possible to allow macro authors to get the actual const values of annotations?

**Comment by jakemac53** [comment] 2023-07-12 16:48
Also related, @johnniwinther @scheglov how would you feel about a general API for evaluating `ExpressionCode` instances? It would produce an error if the expression wasn't a valid const expression, or if there were any references to things which didn't yet exist (or didn't yet have a body).

**Comment by jakemac53** [comment] 2023-07-12 16:51
Yet another hiccup I just realized if we do allow const evaluation - const variables might actually be augmented? Or at least we don't block that today. That means the _value_ could change in phase 3 compared to the value previously.

I am somewhat leaning towards just blocking augmenting const variables at all? This would mean any const expression can always be evaluated in any phase safely, as long as all the references to variables within it have been defined (I would still allow generating new const variable declarations within augmentations).

**Comment by jakemac53** [comment] 2023-07-13 21:57
For anybody following along, I have the first PR of two sent out here https://dart-review.googlesource.com/c/sdk/+/313640. This just gives the very basic level of introspection, without const evaluation. I also chose not to try and give direct access to the arguments, because I think the _fields_ on the evaluated object are more useful.

**Comment by GregoryConrad** [comment] 2023-07-13 23:06
> I also chose not to try and give direct access to the arguments

> Const evaluation will be in a followup.

Just want to check on something based on what you said here; I recently filed https://github.com/dart-lang/language/issues/3210, and was wondering if that would be compatible with the work you're doing here. It'd be nice to be able to re-emit the const object (or in this case function) that is being used as the annotation:

```dart
void foo(){}

@myMacro
void bar(
  @func int foobar,
) {}

// myMacro will be able to re-emit the `func` from the `@func` in its generated code
``` 
Thanks.

**Comment by jakemac53** [comment] 2023-07-14 14:21
Yes - that would be somewhat supported already with the first PR I just sent out  yesterday. The `MetadataAnnotation` class has two subtypes, `IdentifierMetadataAnnotation` and `ConstructorMetadataAnnotation`, this would just be an `IdentifierMetadataAnnotation` so you would get an identifier for the referenced function and could emit that in `Code` objects (and invoke it, etc).

The main thing missing right now would be the ability to figure out what the type of that identifier is, (ie: make sure it's a function). This is a more general hole I think, we don't have the ability to go from an identifier to its declaration for anything except types. It will take a bit of thought just because we really don't want to allow doing that until phase 3 (not all declarations exist until then), but I will add an issue for it.

**Comment by johnniwinther** [comment] 2023-07-17 10:19
Supporting const evaluation of arbitrary metadata for the introspection is a can of worms that I'd rather that we avoided if possible. Yes, it does conflict with lazy evaluation of constants (for the `fromEnvironment` constants) but it'll probably also add (even more) complicated dependencies between declarations. 

For instance, is this a circular dependency?
```Dart
@patch
class Object {}
class Patch extends Object {
  const Patch();
}
const Patch patch = const Patch();
```

Or this?
```Dart
class Class {
  final int value;
  const Class(@Class(0) int value) : value = value + 42;
}
```

**Comment by jakemac53** [comment] 2023-07-17 14:27
@johnniwinther  What if we only allowed evaluating constants from libraries not in the current strongly connected component?

There are strong use cases for this, many Builders today use annotations to configure things. But almost always those annotations are defined in the same package as the Builder which should avoid most of these issues.

**Comment by jakemac53** [comment] 2023-10-26 16:01
See  https://github.com/dart-lang/language/pull/3408 which handles this by allowing general purpose const evaluation with the following constraints:

- No identifier in `code` may refer to a constant which refers to any
  system environment variable, Dart define, or other configuration which is not
  otherwise visible to macros.
- All identifiers in `code` must be defined outside of the current
  strongly connected component (that is, the strongly connected component
  which triggered the current macro expansion).
  
Hopefully the further restrictions on environment variables and Dart defines also helps here.

I need to do a bit more work for the enum values portion though.

**Comment by jakemac53** [comment] 2023-11-07 18:49
I looked at enum values a bit today, but given that we allow you to fill in the definition of an enum value in the definition phase,  I don't think we should give access to them.

However we still do need to add a way of getting the arguments for a metadata annotation.

**Comment by davidmorgan** [comment] 2024-05-29 16:27
Closing in favour of [#3847](https://github.com/dart-lang/language/issues/3847) as this falls into the broader topic of macro metadata.

**Closed by davidmorgan** 2024-05-29 16:27 UTC
Labels: static-metaprogramming
