### ISSUE TITLE
Allow `import` and `part` to have wildcard path to import every lib in specific directory

### ISSUE THREAD

**Issue by SPiercer** [dart-lang/language#3915] opened 2024-06-17 04:29 UTC
i was messing around and had been using `part of` imports and my main part lib has a massive amount of parts

```dart
part 'route/a.dart';
part 'route/b.dart';
part 'route/c.dart';
```

i guess it would be cool if we could've simply just.. 
```dart
part 'routes/*';

**Comment by lrhn** [comment] 2024-06-17 05:07
Duplicate of (at least) https://github.com/dart-lang/language/issues/1709

Same argument against: It's fragile. Even if it was `part 'routes/*.dart';`, it might include something you don't want.
If/when we get part files with imports and further parts, it becomes even less likely that all the files you need are the only files in a directory, and while using globs like `part 'banana_concept1_*.dart';`, `part 'banana_concept2_*.dart';` could work, I hope your editor doesn't write a `#banana_concept1_part1.part` temporary file.

**Closed** 2024-06-17 05:09 UTC
Labels: state-duplicate, feature
