### ISSUE TITLE
Static extension methods defined in an extension on Enum do not get added to ClassMirror.staticMembers. 

### ISSUE THREAD

**Issue by akasher** [dart-lang/language#1037] opened 2020-06-18 08:26 UTC
```dart
enum Roles{
owner,
admin,
user}

extension RolesParser on Roles{
static Roles parse(String value) {
    final Roles role = tryParse(value);
    if (role != null)
      return role;
  }
  static Roles tryParse(String input) {
    final String value = input.trim();
    return Roles.values.firstWhere((element) => element.toString().split('.')[1].toUpperCase() == value.toUpperCase());
  }
}
```

**Comment by leafpetersen** [comment] 2020-06-18 21:19
If I understand the request correctly, you are asking to be able to introspect on the set of extensions which extend a given enum using the ClassMirror for the enum? I think this is probably working as intended.  Extensions aren't really attached to the class they extend, and it feels surprising to me that someone in some completely unrelated library adding an extension would change the entries of a ClassMirror. 

But @rmacnak-google would probably be the right person to comment here.

**Comment by lrhn** [comment] 2020-06-22 08:36
There are two issues here.

First of all, the attempt to add static members to a class using static extensions. That simply does not work in the current Dart. There is no difference between the extension written here and a `class RolesParser` containing the same static methods. They can still only be called using `RolesParser.tryParse`/`RolesParser.parse`, not as `Roles.tryParse` or` Roles.parse`.

Second, extensions do not show up in reflection on the target class. There is nothing inherently preventing that, but I do not believe that is currently any easy way to access extension methods using mirrors. Extension methods are desugared into top-level functions, in this case named `RolesParser.tryParse` and `RolesParser.parse` (which are otherwise not valid declaration names), and you can find them using `dart:mirrors` using `LibraryMirror.declarations`.

**Comment by lrhn** [comment] 2020-08-18 09:42
Closing this for #723 and https://github.com/dart-lang/sdk/issues/43086.

**Closed by lrhn** 2020-08-18 09:42 UTC
Labels: request
