### ISSUE TITLE
Type inference compilation error on callable class

### ISSUE THREAD

**Issue by nank1ro** [dart-lang/language#3122] opened 2023-06-01 08:44 UTC
Code giving error visible at https://dartpad.dev/dfd112dd6e0be277c2d8f3c3f7c6577f

I put the code also here for an easy reference:
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final a = A("0");
    return MaterialApp(
      theme: ThemeData.dark(),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(
          fn: a,
           builder: (context, value, _) {
             return Text(value);
           }
          ),
        ),
      ),
    );
  }
}

class A<T> {
  A(T value): _value = value;
  
  final T _value;
  
  T call() => _value;
}

class MyWidget<T> extends StatelessWidget {
  const MyWidget({
    super.key,
    required this.fn,
    required this.builder,
  });
  
  final T Function() fn;
  final ValueWidgetBuilder<T> builder;

  @override
  Widget build(BuildContext context) {
    return builder(context, fn(), null);
  }
}
```

This code throws a compilation error like this:
```
Error: The argument type 'Object?' can't be assigned to the parameter type 'String'.
 - 'Object' is from 'dart:core'.
             return Text(value);
```

The interesting thing is that just by changing `fn: a` into ` fn: a.call` the error disappears and the code works as expected.
Also this `fn: () => a()` works.
Seems like the Type inference doesn't work correctly on callable functions when the function name is not explicitly set.

At the time of creating this issue these are the Dart and Flutter versions being used:
- Flutter 3.10.2
- Dart SDK 3.0.2

**Comment by eernstg** [comment] 2023-06-01 11:19
There is no information flow that will inform the choice of formal parameter types of a function literal based on code in the body of the function literal.

In other words, the type of `value` in `(context, value, _) { return Text(value); }` will never take into account that this parameter is passed to an invocation of a `Text` constructor. The type of function literal parameters (without a declared type, like all three parameters in this case) is obtained from the context type, if any.

In this case the context type is `ValueWidgetBuilder<T>`, which is the declared type of the instance variable `builder` and hence also the type of the parameter `this.builder` in the constructor.

The value of `T` in this case is `Object?` (the greatest closure of the empty context `_`), because no elements in the code contribute any constraints about `T`.

Hence, passing `value` as in `Text(value)` is a compile-time error.

I think the main thing to emphasize here is that there is no way to transfer information from the body of a function literal to the types of formal parameters, they get everything (if anything) from the context type of the function as a whole. So in the case where the formal parameter types aren't inferred as you would expect, please double check that there is some useful information in the context type.

I'll close the issue because it is all working as intended.

**Closed by eernstg** 2023-06-01 11:19 UTC
Labels: bug

**Comment by nank1ro** [comment] 2023-06-01 13:03
Sorry @eernstg but based in the informations you given I still don't understand why with this little change:
```diff
- fn: a,
+ fn: a.call,
```
everything works as expected without any compilation error.

Isn't `a` supposed to work exactly like `a.call` given that `a` has a callable function inside it?

**Comment by eernstg** [comment] 2023-06-01 13:31
By the way, you might want to use a more strict static analysis:

```
warning • n027.dart:69:34 • The type of value can't be inferred; a type must
          be explicitly provided. Try specifying the type of the parameter.
          • inference_failure_on_untyped_parameter
```

based on the following 'analysis_options.yaml':

```yaml
analyzer:
  language:
    strict-raw-types: true
    strict-inference: true
    strict-casts: true

linter:
  rules:
    - avoid_dynamic_calls
```
