### ISSUE TITLE
Switch on a Future has no subtype check when using a sealed class pattern.

### ISSUE THREAD

**Issue by a-vachasov** [dart-lang/language#3291] opened 2023-08-18 15:17 UTC
Found a very frustrating behavior of the type check in a switch statement in **Dart 3.1.0**.
I'm not sure if i can clearly describe the issue, so i created a code snippet which can be verified even in dartpad.
```
sealed class Foo {}
class Bar extends Foo {}

Future<Foo> createInstanceOfFoo() async {
  return Bar();
}

Future<void> futureSwitch() async {
  final foo = createInstanceOfFoo(); // Not awaited, thus a Future<Foo> is returned.
  
  switch(foo) {
    case int(): // A valid expected warning because int is not subtype of Future<Foo>.
      break;
    case Bar(): // !!! No warning, but expected a warning because Bar is not a subtype of Future<Foo>
      print("futureSwitch: It's Bar"); 
      break;
  }
}
```
Gist with an example and a couple of valid cases: https://gist.github.com/a-vachasov/1a7848a1332af49e069442c7b2847669

I find this behavior to be very prone to misbehavior in runtime because we normally rely on the dart's type-safe nature.
Please let me know if any additional information is required.

**Comment by eernstg** [comment] 2023-08-18 15:54
It might look like a bug, but it is actually working correctly. We cannot conclude that the `Bar()` case is unreachable:

```dart
class Bar2 extends Bar implements Future<Foo> {
   // We can implement all the methods, but this is sufficient to make the point.
  noSuchMethod(i) => throw 0;
}

Future<Foo> createInstanceOfFoo() {
  return Bar2();
}
```

In general, we cannot know for sure that an expression with static type `T` cannot yield an instance whose type is a subtype of some other unrelated type `S`, because it could be an instance of a class that implements both.

**Comment by eernstg** [comment] 2023-08-18 15:58
I'll remove the 'bug' label and close the issue because it's working as intended. However, @a-vachasov, do feel free to create new issues if you encounter something else that looks wrong.

**Closed by eernstg** 2023-08-18 15:58 UTC

**Comment by a-vachasov** [comment] 2023-08-18 16:41
@eernstg thank you for such a quick and clear response!

Considering your answer we found a solution which fits our needs.
Not a general solution, but since the behavior is somewhat unobvious it might be useful for other developers, so sharing it here:

`We can provide the type-check with an exhaustive information by making Bar class final:`

```
sealed class Foo {}
**final** class Bar extends Foo {}

Future<Foo> createInstanceOfFoo() async {
  return Bar();
}

Future<void> futureSwitch() async {
  final foo = createInstanceOfFoo(); // Not awaited, thus a Future<Foo> is returned.
  
  switch(foo) {
    case int(): // A valid expected warning because int is not subtype of Future<Foo>.
      break;
    case Bar(): // A valid expected warning because Future<Foo> can NEVER match the required type Bar since Bar is a final class.
      break;
  }
}
```
