### ISSUE TITLE
`final` is too long

### ISSUE THREAD

**Issue by mgenware** [dart-lang/language#2868] opened 2023-02-26 11:33 UTC
Of all the keywords a language introduces, declaring a local final variable could easily be the most frequently used one. `final` (5 letters) just seems too long compared to other languages (Rust -> `let`(3), Swfit -> `let`(3), Kotlin -> `val`(3)). I usually disable the lint rule `prefer_final_locals` and go all `var` in my projects just to type less cuz it's used so frequently, typing 2 less letters can really speed up coding.

One similar language is JavaScript. It uses `const` (5) for this purpose. JavaScript also has to type `function` (8) to declare a function. Other languages have much shorter keywoards for that: Rust -> `fn`(2), Swift -> `func`(4), Kotlin -> `fun`(3). You can see the difference here. It would be great if Dart introduces a shorter keyword (like `let` or `val`) to replace `final`.

**Comment by lrhn** [comment] 2023-02-26 11:43
Duplicate of #136

**Closed by lrhn** 2023-02-26 11:43 UTC
Labels: feature
