### ISSUE TITLE
Default constructor should have parameters for uninitialized final members.

### ISSUE THREAD

**Issue by adrianboyko** [dart-lang/language#1569] opened 2021-04-09 05:52 UTC
Dart provides a default constructor for any class that does not explicitly define a constructor and those default constructors always have zero parameters. But if a class does not define an explicit constructor *and* it has uninitialized final members, wouldn't it be safe to assume that the programmer intends that the initializing values should be provided to the default constructor?

Example:
``` dart
class Point<T extends num> {
  final T x;
  final T y;
}
```
Because `Point<T>` does not define a constructor *and* it has unitialized final members`x` and `y`, the default constructor provided by Dart would be:
``` dart
const Point(this.x, this.y)
```
In this example, the default constructor is const because *all* the members are final. In classes with non-final members, the default constructor would not be const.

The more uninitialized final members a class has, the more this proposal would help keep things succinct. An example from my current project:
``` dart
class StatusChangeReport {
  final bool dialFrequencyChanged;
  final bool modeChanged;
  final bool dxCallChanged;
  final bool reportChanged;
  final bool txModeChanged;
  final bool txEnabledChanged;
  final bool transmittingChanged;
  final bool decodingChanged;
  final bool rxDFChanged;
  final bool txDFChanged;
  final bool deCallChanged;
  final bool deGridChanged;
  final bool dxGridChanged;
  final bool txWatchdogChanged;
  final bool subModeChanged;
  final bool fastModeChanged;
  final bool specialOpModeChanged;
  final bool freqToleranceChanged;
  final bool txRxPeriodChanged;
  final bool configNameChanged;

  // The following long/redundant constructor would no longer be required:
  // StatusChangeReport(  
    // this.dialFrequencyChanged,
    // this.modeChanged,
    // this.dxCallChanged,
    // this.reportChanged,
    // this.txModeChanged,
    // this.txEnabledChanged,
    // this.transmittingChanged,
    // this.decodingChanged,
    // this.rxDFChanged,
    // this.txDFChanged,
    // this.deCallChanged,
    // this.deGridChanged,
    // this.dxGridChanged,
    // this.txWatchdogChanged,
    // this.subModeChanged,
    // this.fastModeChanged,
    // this.specialOpModeChanged,
    // this.freqToleranceChanged,
    // this.txRxPeriodChanged,
    // this.configNameChanged);
}
```

**Comment by mraleph** [comment] 2021-04-09 07:18
This is essentially a duplicate of https://github.com/dart-lang/language/issues/698 see the design there.

**Closed by mraleph** 2021-04-09 07:18 UTC
Labels: feature
