### ISSUE TITLE
Can anonymous classes be supported?

### ISSUE THREAD

**Issue by cnfczn** [dart-lang/language#1168] opened 2020-08-23 14:44 UTC
like:
var json = '{"count":12,"members":[{"name":"a"},{"name":"b"}],"data1":123,"data2":{"child1":456}}';
var obj = jsonDecode(json);
print(obj.data1);
//or
print(obj.data1?.data2);

**Comment by DenizAksimsek** [comment] 2020-08-23 18:22
This anonymous class idea seems like just a glorified Map. I think a shorthand like the one Visual Basic uses would be suitable for this use case (and a less drastic change): 

```vb
myJson!data1!data2 ' equivalent to myJson("data1")("data2")
' or in Dart, myJson["data1"]["data2"]
```

Of course, the ! operator is already used in Dart. I can't think of another operator to use.

**Comment by rrousselGit** [comment] 2020-08-23 18:37
Anonymous classes are not maps

Whether we are talking about records/structures or something like C# anonymous objects, in both cases this feature is type safe

Maps are by nature.
Their keys can be anything and the list of keys isn't known at compilation.
And their values are all of the same type


Anonymous objects are different.
Their keys are always a symbol/string, are known at compilation, and the value type is unique to the key. 


Which means we can have:

```dart
{ name: String, age: int } person;

person = { name: 'John', age: 42}; // valid

person = { name: 'Mona', age: 21, address: 'Paris' }; // valid

person = { name: 'John'}; // missing key 'age' 

person = { name: 'John', age: 42.0}; // age of type double cannot be assigned to int
```

**Comment by DenizAksimsek** [comment] 2020-08-23 18:58
Sorry, I know about anonymous types from C# but got confused.

With regards to your JSON example, how does the following code behave?

```dart
final json = '{ "${getRandomString()}": "foo" }';
final obj = jsonDecode(json);
// what is the type of obj?

**Comment by rrousselGit** [comment] 2020-08-23 19:08
Decoding json does not result in an anonymous object.
The result would be unchanged from what we currently have: Map<String, dynamic>

**Comment by lrhn** [comment] 2020-08-24 08:00
The requests here is vague on what is wanted:
* Either `Map` lookup by `.` notation. That won't happen.
* Or `jsonDecode` creating real objects of new synthetic classes instead of maps, which would then allow you to do `.`-lookups of properties. That's *unlikely* to happen, it requires synthesizing *interfaces* at run-time. I'd be ready to consider dynamic proxies for existing interfaces, because it works with V-table based implementations, but creating new interfaces at run-time, full dynamic meta-programming, is unlikely to happen any time soon. If we do it, it won't be to make JSON accesses more convenient.

That said, you can currently do things with `noSuchMethod` and converting member name Symbols to strings. Say:
```dart
import "dart:collection";
import "dart:convert";

dynamic jsonWrap(Object object) => 
    object is Map<String, dynamic> ? _JsonMap(object) : 
        object is List ? _JsonList(object) : object;

class _JsonMap {
  final Map<String, dynamic> _map;
  _JsonMap(this._map);
  noSuchMethod(i) {
    if (i.isGetter) {
      var n = i.memberName.toString();
      // Makes unwarrented assumption about Symbol.toString.
      // Doesn't hold for minimized JS code.
      assert(n.startsWith('Symbol("') && n.endsWith('")'));
      n = n.substring(8, n.length - 2);
      return jsonWrap(_map[n]);
    }
    return super.noSuchMethod(i);
  }
}

class _JsonList extends ListMixin<dynamic> {
  final List<dynamic> _list;
  _JsonList(this._list);
  int get length => _list.length;
  dynamic operator[](int index) => jsonWrap(_list[index]);
  void add(element) {
    throw UnsupportedError('Unmodifiable list');
  }
  operator[]=(int index, element) {
    throw UnsupportedError('Unmodifiable list');
  }
  set length(int newLength) {
    throw UnsupportedError('Unmodifiable list');
  }
}


main() {
  var json = jsonWrap(jsonDecode('{"foo": [{"bar": 42}]}'));
  print(json.foo[0].bar);
}
```
I cannot recommend this approach. It's horribly inefficient and it doesn't work well with minification.
All you save is turning `json["foo"][0]["bar"]` into `json.foo[0].bar`, which actually hides what's going on.

**Comment by subzero911** [comment] 2024-05-15 14:13
I don't understand why did you choose a json as an example.

I may imagine the following syntax:
```dart
authRepository.login(userId, class implements IAuthListener {
  @override
  void onError(String error) {
    showToast(context, error);
  }

  @override
  void onSuccess() {
    Navigator.pushNamed(context, 'my-screen');
  }
};
);
```

**Comment by rrousselGit** [comment] 2024-05-15 14:26
I think the issue is that it'd be difficult for anonymous classes to be truly effective without improving type-inference significantly.

In TS for instance, we don't have to specify the return value of a function. So a function that returns an anonymous class will have a correctly typed result.
But in Dart, we'd have to define an interface that the anonymous class will have to implement. So in many cases, we don't win in terms of boilerplate.

**Comment by munificent** [comment] 2024-08-21 22:27
I'm not convinced that anonymous classes are worth adding. I suspect they aren't. But I will say: 

> In TS for instance, we don't have to specify the return value of a function. So a function that returns an anonymous class will have a correctly typed result. But in Dart, we'd have to define an interface that the anonymous class will have to implement. So in many cases, we don't win in terms of boilerplate.

For what it's worth, C# does have anonymous classes and that is exactly how they operate. I don't think they're super common in practice—they were basically added to the language so that LINQ has a way to synthesize classes for tables if I remember right—but they are a thing.

**Comment by munificent** [comment] 2024-08-21 22:37
I'm going to go ahead and close this in favor of #2927. That issue is newer, but is more about actual anonymous classes, which is a feature that could fit better into Dart, than this issue where the suggestion is more around blurring the line between maps and objects. I don't see that happening.

**Closed by munificent** 2024-08-21 22:37 UTC
Labels: feature
