### ISSUE TITLE
Assignable expressions in pattern declaration contexts.

### ISSUE THREAD

**Issue by water-mizuu** [dart-lang/language#3187] opened 2023-07-02 05:42 UTC
As of now, the patterns only allow for declarations/replacements into identifiers. Since we require `var` or `final` keyword in variable declaration, non-declaring contexts should be able to do more than just assign to variables. So I propose that we allow this kind of syntax in pattern matching.

```dart
List<int> values = <int>[0, 1, 2, 3, 4];
List<int>(
    first: values.last,
    last: values.first,
) = values;
print(values); // [4, 1, 2, 3, 0]
```

Maybe we can extend this syntax to allow array indexing as well, so like:

```dart
List<int>(
  [0]: values[4],
  [4]: values[0],
) = values;
print(values); // [4, 1, 2, 3, 0]
```

If we want to do something more mixed like assigning and declaring, we can do something like:

```dart
List<int>(
  first: values.last,
  last: int last
) = values;
assert(values.first == last);
```

**Comment by lrhn** [comment] 2023-07-02 09:55
Related to #2855, possibly #3175

The fully general solution would be to combine assignment and declaration patterns.
The problem with that is that declaration patterns uses the leading `var` or `final` as a parsing hint, to express that it is a declaration, not just an assignment. 

But let's say we allow `(x, var y) = pair;` as a declaration/assignment pattern which assigns to the existing variable `x` and the new variable `y`. Then `var (x, y) = pair;` is just shorthand for `(var x, var y) = pair;`.

It's a compile-time error if an assignment pattern which introduces a new variable does not occur as an expression-statement/declaration. Assignment-patterns with no `var`/`final` introducing new variables can occur as any expression.

And then we can allow any assignable expression in assignment-patterns, not just identifiers. If they are grammatically distinguishable from patterns. A `var` prefix on a sub-pattern (or the entire pattern) switches to the current "new variables only" mode.

**Comment by munificent** [comment] 2023-08-15 23:09
I'm going to close this as a duplicate of #2855.

**Closed by munificent** 2023-08-15 23:09 UTC
Labels: feature, patterns-later
