### ISSUE TITLE
[flow analysis] promote variable in a function expression if potentially final

### ISSUE THREAD

**Issue by asashour** [dart-lang/language#2753] opened 2022-12-30 16:33 UTC
```dart
void g(void Function() x) {}

void f(int? i) {
  int? x;
  if (i == null) return;
  x = i; // here x is not-nullable
  g(() {
    x.isEven; // 🔥 x is nullable
  });
}
```

Current behavior: on entering the function, `x` promotion is discarded, so it is not promoted to be not-nullable, because `x` is assigned (written).

The current proposed implementation is that on entering the closure, variables which are:

1. not written/assigned in any closure, and
2.  not written after "entering" this closure

are considered final and so promotion is preserved.

**Comment by lrhn** [comment] 2023-01-02 22:01
Moving this to the language repo, since any change to inference is a language change.

**Comment by stereotype441** [comment] 2023-01-03 23:25
Duplicate of #1536.

**Closed by stereotype441** 2023-01-03 23:25 UTC
Labels: inference
