### ISSUE TITLE
Type inference

### ISSUE THREAD

**Issue by ErliSoares** [dart-lang/language#1515] opened 2021-03-12 02:12 UTC
Automatically detect generic types by parameters.

## Proposal
```dart
class Bloc<T> {
  Bloc(this.value);
  T value;
}

class ValueField {
  static T calc2<T, A, B>(Bloc<A> blocA, Bloc<B> blocB, T Function(A a, B b) calcule) {
    return calcule(blocA.value, blocB.value);
  }
}

void test() {
  final blocNum1 = Bloc<int>(1);
  final blocNum2 = Bloc<int>(2);

  // type of valueReturn is int
  final valueReturn = ValueField.calc2(blocNum1, blocNum2, (valueA, valueB) {
    // type of valueA is int
    // type of valueB is int
    return valueA + valueB;
  });
}
```

## Current
```dart
void test() {
  final blocNum1 = Bloc<int>(1);
  final blocNum2 = Bloc<int>(2);

  // type of valueReturn is int
  final valueReturn = ValueField.calc2<int, int, int>(blocNum1, blocNum2, (valueA, valueB) {
    // type of valueA is int
    // type of valueB is int
    return valueA + valueB;
  });
}
```

## Example C#

Below is a demonstration of how it works in C # and the type inference language reference link.

```C#
void main()
{
    var blocNum1 = new Bloc<int>(1);
    var blocNum2 = new Bloc<int>(2);

    // type of valueReturn is int
    var valueReturn = ValueField.calc2(blocNum1, blocNum2, (valueA, valueB) => {
        // type of valueA is int
        // type of valueB is int
        return valueA + valueB;
    });
}
```

[C# Language reference. Type inference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#type-inference)

**Comment by leafpetersen** [comment] 2021-03-12 03:22
Duplicate of https://github.com/dart-lang/language/issues/731 .

**Closed by leafpetersen** 2021-03-12 03:22 UTC
Labels: feature
