### ISSUE TITLE
Json new type

### ISSUE THREAD

**Issue by srgbrito** [dart-lang/language#1208] opened 2020-09-05 11:59 UTC
Hello.
Please create a new type on language:

**class Json extends Map<String, dynamic> {}**

I have tried do this, but stuck on a error "Json is not a subtype of _InternalLinkedHashMap"...
This new class will clean the code for networking.
Thanks.

**Comment by mnordine** [comment] 2020-09-05 12:49
Is this kind of what you want?

```dart
import 'dart:html';
import 'dart:convert';

typedef Json = Map<String, dynamic>;

Future<void> main() async {
  final response = await HttpRequest.read('https://example.com/file.json');
  final json = jsonDecode(response) as Json;

  final data = Json();
  data['id'] = 5;
  data['name'] = 'me';
}
```

If so, the line
```dart
typedef Json = Map<String, dynamic>;
```

is what you want. This is a planned experimental feature called non-function type aliases (`nonfunction-type-aliases`). However, it is *not* enabled, and has taken a backseat to work on `non-nullable`. Hopefully it is enabled in the future.

**Comment by srgbrito** [comment] 2020-09-05 13:00
Yes. Exactly that.
Can I enable this?

**Comment by mnordine** [comment] 2020-09-05 13:08
> However, it is not enabled

**Comment by srgbrito** [comment] 2020-09-05 13:10
OK. But can I enable it in my projects?

**Comment by mnordine** [comment] 2020-09-05 13:14
Not yet.

**Comment by mnordine** [comment] 2020-09-05 13:15
You can read about experiments here: https://dart.dev/tools/experiment-flags

**Comment by lrhn** [comment] 2020-09-06 07:54
Closing as a duplicate of #65.

**Closed by lrhn** 2020-09-06 07:54 UTC
Labels: feature
