### ISSUE TITLE
Introduce fix keyword as syntactic sugar for local, promotable, nullable field

### ISSUE THREAD

**Issue by weenzeel** [dart-lang/language#1980] opened 2021-11-21 23:15 UTC
I've been reading the comments about if-variables.

What if we introduced a "fix" keyword, so that we could do ...

```dart
class Coffee {
  String? temperature;

  void heat() { temperature = 'hot'; }
  void chill() { temperature = 'iced'; }

  void checkTemp() {
    
    fix temperature;
    
    if (temperature != null) {
       print('Ready to serve ' + temperature + '!');
    } else {
      temperature = 'UNKNOWN';
    }


    // If we want the unfixed value we can just refer to it via this.temperature
        
  }

  String serve() => temperature! + ' coffee';
}
```

The code above would be equal to ...

```dart
class Coffee {
  String? temperature;

  void heat() { temperature = 'hot'; }
  void chill() { temperature = 'iced'; }

  void checkTemp() {
    
    var fixedTemperature = temperature;
    
    if (fixedTemperature != null) {
       print('Ready to serve ' + fixedTemperature + '!');
    } else {
      fixedTemperature = 'UNKNOWN';
      temperature = 'UNKNOWN';
    }
  }

  String serve() => temperature! + ' coffee';
}
```

- Fixing a field is like creating a local copy at a fixed point in time. That copy persists until the end of the scope.
- Writing to a fixed field is like updating a local copy in sync with the original field.
- The unfixed field can always be fetched via this.field.
- A fixed field can be refixed to refresh the fixed value.

Just throwing it out there :)

**Comment by mateusfccp** [comment] 2021-11-22 00:55
This seems to be very similar to #1514.

**Comment by tatumizer** [comment] 2021-11-22 02:22
This proposal and all its variants (there are several) share a common property: they assume that shadowing is a good idea. But it's not. If we had an 2-clause if statement, we could write it as:
```dart
void checkTemp() {
    if (var t = temperature; t != null) {
       print('Ready to serve ' + t + '!');
    } else {
      t = 'UNKNOWN';
      //...
    }
  }
```
Please note the local variable is called `t` - short names for local variables are common, convenient, and don't cause any confusion.

**Comment by weenzeel** [comment] 2021-11-22 07:13
> This seems to be very similar to #1514.

@mateusfccp You're right. It's basically the same idea, just a different keyword. Thanks for making the connection!

**Comment by mit-mit** [comment] 2021-11-22 13:57
Closing as a duplicate of #1514

**Closed by mit-mit** 2021-11-22 13:57 UTC
Labels: feature
