### ISSUE TITLE
Is it possible to match a record to a map? Should it be?

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/language#2886] opened 2023-03-04 12:47 UTC
I am doing some tests and it seems that is currently not possible to match a `Record` against a `Map`

The following code produces `No` and `true`:

```dart
import 'dart:convert';

typedef FromMap = ({String foo, int bar});

void main() {
  final decoded = json.decode('{"foo": "yat", "bar": 123}');
  
  if (decoded case {'foo': String foo, 'bar': int bar}) { // matches
    final fromMap = (foo: foo, bar: bar);
    
    print(fromMap is FromMap); // Unnecessary type check, result always true
  }

  if (decoded case FromMap) { // nope, doesn't match
    print('Yes');
  } else {
    print('No'); // enters here
  }
}
```

Will it be possible to retrieve a `Record` from a `Map`?  

I can see packages exposing builders that do that and I was wondering if this should be possible from the core.  
If you think it through  `Map matching` is very close to it.

**Comment by jodinathan** [comment] 2023-03-05 21:47
yeah I understand that we shouldn't keep source names in production code and it makes sense.  

However, we _do need_ them when we do `if (decoded case {'foo': String foo, 'bar': int bar}) {}`.  

So I am wondering that when the compiler traverse the code and find a `Map` being matched to a `Record` like in `if (map case FromMap obj) {}` it would then retain the sources names as it would in a `map-matching`.

**Comment by lrhn** [comment] 2023-03-05 22:38
It's definitely possible, but again, matching source names to *string* values at runtime is two steps out of my comfort zone.
Had it been symbols instead of strings as map keys, it would only have been one step. 😉 

A much more direct match would be matching an *object* to a record type, like:
```dart
class Foo {
  int foo = 0;
  String bar = "";
}
typedef FooBar = ({int foo, String bar});
// ...
  if (aFoo case FooBar r) { ... destructure object and build record ... }
```

It's still mixin two concepts: Destructuring and re-structuring.
Patterns destructure. They allow you to access the individual values.
Combining those values back into a new object, whether a record or something else, is what you do in the case body.

Converting directly from one structure to another, through some *implicit* connection between their properties, is something I'd at least require an *explicit* declaration of, not something the compiler should just guess out of naming or types.

**Comment by jodinathan** [comment] 2023-03-06 00:21
> matching source names to string values at runtime is two steps out of my comfort zone

the point is that we are already doing it here: `if (decoded case {'foo': String foo, 'bar': int bar}) {}`

> Converting directly from one structure to another, through some implicit connection between their properties, is something I'd at least require an explicit declaration of, not something the compiler should just guess out of naming or types.

I seriously thought it was possible because the syntax between `Records` and `pattern matching` are very alike

**Comment by munificent** [comment] 2023-03-06 21:47
> So I am wondering that when the compiler traverse the code and find a `Map` being matched to a `Record` like in `if (map case FromMap obj) {}` it would then retain the sources names as it would in a `map-matching`.

The problem is that the compiler can't tell which records might flow into which map patterns (or vice versa). In general, this kind of dataflow analysis for dead code elimination is really fragile and hard to make work well.

Maps and records are *very* different constructs. They solve different problems and they have different trade-offs. That's why Dart has both map and record objects, and why it has map and record patterns.

> I seriously thought it was possible because the syntax between `Records` and `pattern matching` are very alike

The syntax for record types with named fields does look sort of like a map, which is unfortunate. But it's not because records are map-like. It's because we wanted record types to roughly mirror *parameter lists*, which use `{ ... }` for named fields. If parameter lists didn't use `{ ... }`, then record types wouldn't either.

**Comment by munificent** [comment] 2023-03-06 21:48
I'm going to close this because we don't have any plans to change this part of the language, but it's a good question. Thanks for asking.

**Closed by munificent** 2023-03-06 21:48 UTC
Labels: question, patterns
