### ISSUE TITLE
NNBD. An error for the type 'void?'

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/language#802] opened 2020-01-29 10:14 UTC
According to the NNBD [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#syntax)

> The grammar of types is extended to allow any type to be suffixed with a ? (e.g. int?) indicating the nullable version of that type.

But now it is a compile error to try to use type `void?` (in both analyzer and VM). According to the spec it must be allowed

dartanalyzer version 2.8.0-dev.6.0

**Comment by tatumizer** [comment] 2020-01-29 21:28
Related discussion: https://github.com/dart-lang/sdk/issues/39896

**Comment by eernstg** [comment] 2020-01-31 15:17
I think for this particular issue we can use the specification documents as follows: The NNBD spec indicates that

> The grammar of types is extended

but the specific grammar changes have already been introduced into the language specification, and most of them were never spelled out in the NNBD spec. So for detailed syntactic discussions, we should use the language specification. This means that `void?` is a syntax error.

@tatumizer mentioned dart-lang/sdk#39896, and the discussion there indicates that we might want to make changes in this area, in order to improve on the overall consistency if Dart syntax. But it is not obvious that this change is worthwhile.

So I think we should use the language specification grammar in this case and note that `void?` is a syntax error.

Then we can revisit tests and implementations in case we decide to make changes in this area at some point in the future.

**Comment by eernstg** [comment] 2020-04-21 08:42
I think we should close this issue: The null-safety related syntax was specified in the language specification from the very beginning, and it makes `void?` a syntax error. It is indeed a small anomaly in the syntax of Dart, but it doesn't cause any practical problems. So I'll mark the issue with "working as intended" (actually, the only label we have that is even remotely similar is 'state-rejected', so I'll have to use that) and close it.

**Closed by eernstg** 2020-04-21 08:42 UTC
Labels: state-rejected
