### ISSUE TITLE
Allow custom operators

### ISSUE THREAD

**Issue by Afsar-Pasha** [dart-lang/language#756] opened 2019-12-19 17:30 UTC
See [Swift custom operators](https://docs.swift.org/swift-book/LanguageGuide/AdvancedOperators.html#ID46).
This will be useful with #194, for example #131/#361(if not null operator) can be implemented in the core without much effort.

**Comment by lrhn** [comment] 2020-01-02 11:32
Duplicate of #607.

**Closed by lrhn** 2020-01-02 11:32 UTC
Labels: feature, state-duplicate
