### ISSUE TITLE
A syntax for type declarations with mixins

### ISSUE THREAD

**Issue by makoConstruct** [dart-lang/language#1481] opened 2021-02-28 06:23 UTC
It is sometimes desirable to require a parameter to implement a class and a mixin, for instance:

```dart
mixin Indented {
   int get indentLevel;
}

class IndentedLine{
   Widget with Indented child;
```

But the expression `Widget with Indented` is not legal. There is no way to refer to that type.

I have tried

```dart
abstract class IndentedWidget extends Widget with Indented;

class IndentedLine{
   IndentedWidget child;
```

But this wont do here. When you actually create an IndentedWidget, you generally can't do it by extending IndentedWidget. You do it by extending `StatelessWidget with Indented`, which despite implementing both Widget and Indented, is not castable to `IndentedWidget`.

**Comment by eernstg** [comment] 2021-03-01 09:30
You are asking for intersection types: If you could use a term like `Widget with Indented` as a type then it would have to mean "a maximal type `T` such that `T` is a subtype of `Widget` and `T` is a subtype of `Indented`". The word "maximal" just means that we can't choose a different value for `T` which is a supertype of the chosen one, so it gets "as close as possible to `Widget` and `Indented`". That's exactly how we'd define an intersection type. A typical syntax would use `&`, so you would then write this intersection type as `Widget & Indented`:

```dart
class IndentedLine {
   Widget & Indented child;
}
```

Intersection types could be added to Dart, but it is likely to be a major project. In particular, intersection types are directly related to union types (for instance, using `|` to specify union types, `Function(S | T) <: Function(S) & Function(T)` and `Function(S) | Function(T) <: Function(S & T)`), and this means that the addition of intersection types basically won't work unless we also add union types, and vice versa.

See https://github.com/dart-lang/language/issues/83 and https://github.com/dart-lang/language/issues/145 for further discussions about intersection and union types. Also note https://github.com/dart-lang/language/issues/1152 where the topic of intersection types is approached from a similar angle as in this issue.

I'll close this issue as a duplicate of those other discussions.

However, in the particular case where you wish to specify a subtype of `Widget` and `Indented`, it might be possible to simply eliminate the problem by making `abstract class Indented ... implements Widget`. The assumption is that you aren't actually going to work with any `Indented` objects that aren't also `Widgets`, and if this is true then you might as well just include `Widget` among the supertypes of `Indented` in the first place, and then you can simply do this:

```dart
class IndentedLine {
  Indented child;
}
```

**Closed by eernstg** 2021-03-01 09:30 UTC
Labels: feature, state-duplicate

**Comment by makoConstruct** [comment] 2021-03-01 19:25
Oh cool, I didn't know about `implements`, so many reasonable subtleties.

I ended up using dynamic type checking so that anything that doesn't implement Indented essentially defaults to indent:0, but it's nice to know that there's a way to do that.

**Comment by eernstg** [comment] 2021-03-01 19:47
Ah, makes sense! Thanks.
