### ISSUE TITLE
Allow using enum's member in a constant context

### ISSUE THREAD

**Issue by tomyeh** [dart-lang/language#2392] opened 2022-08-06 04:54 UTC
For example,

```
enum Help {
  foo('Foo');

  final String message;
  const Help(this.message);
}

const list = [Help.foo.message],
 map = {Help.foo.message: 12};
```

It can help the sharing of constants.
But, with Dart 2.17.6, it said:

```
  error • enum2.dart:9:3 • Const variables must be initialized with a constant value.
          Try changing the initializer to be a constant expression. •
          const_initialized_with_non_constant_value
  error • enum2.dart:9:3 • The keys in a const map literal must be constant. Try
          removing the keyword 'const' from the map literal. • non_constant_map_key
```

**Comment by lrhn** [comment] 2022-08-06 23:12
Duplicate of https://github.com/dart-lang/language/issues/2374

**Closed by lrhn** 2022-08-06 23:12 UTC
