### ISSUE TITLE
Specify how augmentation libraries can augment enhanced enum entries

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/language#2978] opened 2023-04-04 17:57 UTC
For new enum entries this isn't particularly difficult, but for augmenting existing enum entries the syntax isn't obvious.

We could allow a user to write:

```dart
enum A {
  b; // This isn't complete, but allow an augmentation to fill in the constructor call? 

  const A(this.value);

  final int value;
}
```

Consider that the constructor(s) and field(s) may also be added by an augmentation library.

**Comment by lrhn** [comment] 2023-04-04 18:59
I'd say they need to be specially marked as `external`. That's what that keyword is for: Valid non-abstract declaration where the implementation is supplied from somewhere else.

There is a very big difference between an abstract declaration and an external declaration. Supplying an implementation for an *abstract* member is *disagreeing* with the original declaration, which said that there was no implementation.
Supplying implementation for an `external` member is working as intended.

**Comment by jakemac53** [comment] 2023-04-05 16:15
I don't hate the idea of marking them as `external`, and that could also apply to static members. We would have to make that valid syntax but that should probably be doable?

**Comment by jakemac53** [comment] 2023-04-05 16:57
This issue is making me think that we should generally enforce this constraint that augmentations can only fill in the bodies of external declarations.

That makes lots of things in general more explicit and I think would be a benefit. It is also a restriction we could theoretically remove in the future. cc @munificent

**Comment by jakemac53** [comment] 2023-05-04 20:33
Spec updates sent out in https://github.com/dart-lang/language/pull/3042, I ended up not requiring `external` because it would be inconsistent with the rest of the proposal, and to make it consistent would end up meaning we would end up forcing a lot of boilerplate onto users.

I did file https://github.com/dart-lang/language/issues/3041 though to discuss what we should do regarding external generally.

**Closed** 2023-05-05 13:56 UTC
Labels: specification, augmentation-libraries
