### ISSUE TITLE
`throws` keyword for methods and constructors declarations

### ISSUE THREAD

**Issue by AAAbramenko** [dart-lang/language#2249] opened 2022-05-18 11:15 UTC
What is about to introduce `throws` keyword:
```dart
String readDataFromFile(String path) throws IOException, FormatException {
...
}
```
This will help to indicates that place of method/constructor calling must be wrapped in try-catch block.
You can find same language feature in Java (look spec [here](https://docs.oracle.com/javase/specs/jls/se18/html/jls-8.html#jls-8.4.6) and [here](https://docs.oracle.com/javase/specs/jls/se18/html/jls-8.html#jls-8.8.5))..

**Comment by mateusfccp** [comment] 2022-05-18 11:55
Isn't this the same as checked exceptions? If yes, duplicate of #984.

**Comment by munificent** [comment] 2022-05-18 18:43
Yes, what you're looking for is checked exceptions. We have discussed it at length but feel it's not an overall win for users.

**Closed** 2022-05-18 18:43 UTC
Labels: state-duplicate, feature
