### ISSUE TITLE
Add null-check With Creating a New Variable

### ISSUE THREAD

**Issue by EmreSURK** [dart-lang/language#1526] opened 2021-03-16 09:08 UTC
Dart is great, and null-safety is great too. It allows developers to eliminate null-related-crashes easily. 

I strongly believe we can move forward with syntax.

Currently, developers still need to check the variable if null like that:

```
var someVariable = data?.someMember;
if ( someVariable != null ) {
     // code..
}
```

These checks are so similar for non-optional values, so most developers get confused and can not see the beauty of the optional types. Most of the time the **someVariable** variable is not being used outside of the if block. 

I am suggesting null checking while defining a  non-optional variable inside if block:

```
if ( var someVariable = data?.someMember ) {
    // we have someVariable variable, it has data and it is not optional anymore.
} else {
   // we don't have someVariable variable, data or someMember is null. 
}

// someVariable variable is not defined here.

```

I inspired by other languages, of course. 

Let me know what you think.

Best.

**Comment by eernstg** [comment] 2021-03-16 09:29
This idea has been considered elsewhere already: #1201, #1210, #1420, so you may wish to contribute to the discussions there. Also, you may be interested in the topic [field-promotion](https://github.com/dart-lang/language/labels/field-promotion) in general.

I'll close this issue as a duplicate of those.

**Closed by eernstg** 2021-03-16 09:29 UTC
Labels: feature, state-duplicate
