### ISSUE TITLE
Switching over generic runtime type does not work

### ISSUE THREAD

**Issue by ltOgt** [dart-lang/language#1455] opened 2021-02-16 17:43 UTC
I have been using the `switch` statement to react to the specific implementation of an Object via its `runtimeType`.
This does not work for Objects with a generic type parameter:

```dart
main() {
  BaseClass c = GenericExtension<SubClass>();
  
  switch(c.runtimeType) {
    case Extension:
      print("Extension");
      break;
    /** Error: In constant expressions, operands of this operator must be of type 'num' 
    case GenericExtension<SubClass>:
      print("SubClass Generic Extension");
      break;
    */
    case GenericExtension:
      print("Unspecified Generic Extension");
      break;
    default:
      print("Missed");
  }
  
  print(c.runtimeType);

  if (c is GenericExtension<SubClass>) {
    print("works");
  }
}


class SubClassBase {}
class SubClass extends SubClassBase {}

class BaseClass {}
class Extension extends BaseClass {}
class GenericExtension<T extends SubClassBase> extends BaseClass{}

```

Output:
```
Missed
GenericExtension<SubClass>
works
```

This is not a huge issue, since checking for the type with `is` works as expected.

I was just wondering whether this is by design, since I had expected the switch version to work.

**Comment by eernstg** [comment] 2021-02-17 08:53
It's a delicate exercise to use `runtimeType` and compare the returned value (known as a reified type) with anything: Object-oriented modeling encourages substitutability, and if you are expecting `o` to be an instance of `SomeClass` and actually encounter an instance of `ASubclassOfSomeClass` then you will get `false` from `o.runtimeType == SomeClass`.

That said, you can still make it work.

The error occurs because you are trying to use `GenericExtension<SubClass>` as an expression, and that's a syntax error. It is a `<type>`, but not an `<expression>`.

You can in general use a function like `typeOf`:

```dart
class SubClassBase {}

class SubClass extends SubClassBase {}

class BaseClass {}

class Extension extends BaseClass {}

class GenericExtension<T extends SubClassBase> extends BaseClass {}

Type typeOf<X>() => X;

main() {
  BaseClass c = GenericExtension<SubClass>();
  var cRuntimeType = c.runtimeType;
  if (cRuntimeType == Extension) {
    print("Recognized: Extension");
  } else if (cRuntimeType == typeOf<GenericExtension<SubClass>>()) {
    print("Regocnized: GenericExtension<SubClass>");
  } else if (c is GenericExtension) { // Use `is` to cover subtypes of `GenericExtension<dynamic>`.
    print("Recognized: Unspecified Generic Extension");
  } else {
    print("Missed");
  }
  print('Runtime type is ${c.runtimeType}');
}
```

The missing bit is that you cannot use a function invocation as a constant, which means that you cannot use a switch statement. You already need to use something other than switch because you need to use `is` in order to recognize all subtypes of `GenericExtension` (which is just a concise way to write `GenericExtension<dynamic>`).

**Comment by eernstg** [comment] 2021-02-17 09:02
I'll close this issue as a duplicate of https://github.com/dart-lang/language/issues/123, where there is a request to allow parameterized type as an expression.

**Closed by eernstg** 2021-02-17 09:02 UTC
Labels: request, state-duplicate

**Comment by ltOgt** [comment] 2021-02-17 13:49
Thank you for the detailed response.
Learned something new
