### ISSUE TITLE
Extension type function not available

### ISSUE THREAD

**Issue by Soliardi-Chyngyz** [dart-lang/language#3806] opened 2024-05-15 11:48 UTC
Hi all
I came across the following error when trying to implement an **extension type**.

In pubspec.yaml I raised the minimum version and called the fvm flutter pub get command
however no changes

`environment:
  sdk: ">=3.3.0 <4.0.0"`

<img width="699" alt="Снимок экрана 2024-05-15 в 17 40 54" src="https://github.com/dart-lang/language/assets/66687051/e30cccb5-4a06-4b8b-aab9-d181e8af890a">
<img width="772" alt="Снимок экрана 2024-05-15 в 17 41 52" src="https://github.com/dart-lang/language/assets/66687051/1eaa0392-9c4e-472c-b9e4-83036dde6630">

**Comment by jakemac53** [comment] 2024-05-15 14:39
Is this file for sure under the package in which you set the new SDK constraint? Language versions are per package.

You can also check your `.dart_tool/package_config.json` file, search for the name of the package containing this file, and see what language version it has. If you see something other than `3.3` then the pub get didn't properly overwrite this file and I would try it again.

**Comment by Soliardi-Chyngyz** [comment] 2024-05-16 03:52
> Наверно ли этот файл находится в пакете, в котором вы установили новое ограничение SDK? Языковые версии указаны для каждого пакета.
> 
> Вы также можете проверить свой `.dart_tool/package_config.json`файл, найти имя пакета, содержащего этот файл, и посмотреть, какая у него языковая версия. Если вы видите что-то иное `3.3`, то паб не перезаписал этот файл должным образом, и я попробую еще раз.

As I understand it, we are talking about this line of json code:

{
      "name": "packageName",
      "rootUri": "../",
      "packageUri": "lib/",
      **"languageVersion": "3.3"**
    }

**Comment by jakemac53** [comment] 2024-05-16 16:11
> As I understand it, we are talking about this line of json code:

Correct, and it looks like you are definitely >3.1. Have you tried restarting the analysis server in your IDE? You shouldn't have to, but maybe it didn't pick up the change somehow. In VsCode you can to Ctrl+shift+p and then type "restart analysis server" and run that action. I am not sure how it is done in intellij.

**Comment by jakemac53** [comment] 2024-05-16 16:11
I am also curious if you get the same error from `flutter run` or if it is only an IDE analysis issue.

**Comment by Soliardi-Chyngyz** [comment] 2024-05-17 09:55
> Мне также интересно, получаете ли вы ту же ошибку `flutter run`или это только проблема анализа IDE.

Yes I'm getting an error
The current Dart SDK version is 3.1.3.
Because package requires SDK version >=3.3.0 <4.0.0, version solving failed.

**Comment by Soliardi-Chyngyz** [comment] 2024-05-17 10:01
> restart analysis server

I tried this method but nothing, it’s possible that the fvm third-party lib somehow influences this
maybe I should just do a **flutter upgrade**?

**Comment by jakemac53** [comment] 2024-05-17 18:59
You could do a `flutter upgrade` - or just change your SDK constraint to `>=3.1.0 <4.0.0` - 3.1 looks like the version this feature was released in.

**Comment by Soliardi-Chyngyz** [comment] 2024-05-20 04:35
Thank you, the question is most likely not for you but for **fvm**
flutter upgrade solved the problem but in my case it does not work My Mac does not support Xcode 15 as required by the latest version of flutter

**Comment by munificent** [comment] 2024-10-09 23:09
I'm going to close this because it looks like the problem is resolved.

**Closed by munificent** 2024-10-09 23:09 UTC
Labels: request
