### ISSUE TITLE
Explicit Name For Default Constructor

### ISSUE THREAD

**Issue by fweth** [dart-lang/language#1477] opened 2021-02-25 07:31 UTC
There is this ambiguity between types and default constructors, so `[Foo(a)]` is interpreted as 'call the default constructor of `Foo` with argument `a`' but `[a].map(Foo)` gives an error because `Foo` is interpreted as type, so we have to type `[a].map((x)=>Foo(x))`.  It would be cool to have a way to explicitly call the default constructor, like `[a].map(Foo.Foo)` or `[a].map(Foo.constructor)`.

**Comment by eernstg** [comment] 2021-02-25 09:16
This is essentially a proposal to support tearing off constructors, hence a duplicate of https://github.com/dart-lang/language/issues/216. (Please vote up that one if you wish to support this feature!)

**Closed** 2021-02-25 09:22 UTC
Labels: feature, state-duplicate

**Comment by fweth** [comment] 2021-02-25 09:55
Ah, sorry, I didn't find that one.  Thanks for the link!
