### ISSUE TITLE
Remove required parentheses in conditions (if, else if, switch, while, for in)

### ISSUE THREAD

**Issue by mnordine** [dart-lang/language#2719] opened 2022-12-13 17:57 UTC
Would be nice to make them optional.

**Comment by lrhn** [comment] 2022-12-13 20:34
The problem is that we already made the branch braces optional.

Parsing `if x > y [1] - z;` would be ambiguous, it can be either `if (x > y) { [1] - z; }` or `if (x > y[1]) { -z; }`.

Both look ridiculous, but with suitable types and extension methods, both can be valid.
The parser needs to decide long before we can begin to guess what types thing might have.

So, if you omit the parentheses, you probably have to make the braces mandatory. And that won't work for collection-`if`s, where there are no braces.

Not trivial.

**Comment by munificent** [comment] 2022-12-13 20:41
Yeah, I sympathize with the goal here, but I don't see how it's feasible given Dart's firmly entrenched syntax history. I'm going to close this because I can't imagine us ever doing it.

**Closed by munificent** 2022-12-13 20:41 UTC
Labels: feature
