### ISSUE TITLE
Is it possible to mimic generic type constraints in Dart?

### ISSUE THREAD

**Issue by rubenferreira97** [dart-lang/language#2631] opened 2022-11-14 02:16 UTC
Some languages like `Swift` and `C#` allow to constraint generics to some given rules. Imagine the following example:
Adding a method extension to `List<num>`. 

```
extension NumList<T> on List<T> where T : num {
  List<T> rev() => reversed.toList();
}

void main() {
  List<num> a = [1,2,3];
  a.rev();
  List<String> b = ["1","2","3"];
  b.rev(); // should error
}
```

Swift example:
```
extension Container where Item == Double {
    func average() -> Double {
        var sum = 0.0
        for index in 0..<count {
            sum += self[index]
        }
        return sum / Double(count)
    }
}
print([1260.0, 1200.0, 98.6, 37.0].average())
```
It's even possible to contextually constraint a generic extension to a method like this:
```
extension Container {
    func average() -> Double where Item == Int {
        var sum = 0.0
        for index in 0..<count {
            sum += Double(self[index])
        }
        return sum / Double(count)
    }
}
```

Many other examples can be viewed here: https://docs.swift.org/swift-book/LanguageGuide/Generics.html#ID192

Side note, one interesting and powerful feature that also allows to take advantage of type constraints in `Swift` are `Associated Types`. These types allow to declare one or more associated types as part of the interface definition. They give a placeholder name to a type. They may or may not be generic on the concrete implementation.

Example of a concrete implementation without a generic, while conforming with a type `Item`:
```
protocol Container {
    associatedtype Item // we could give a constraint here like where "Int"
    mutating func append(_ item: Item)
    var count: Int { get }
    subscript(i: Int) -> Item { get }
}
```
```
struct IntStack: Container {
    var items: [Int] = []
    mutating func push(_ item: Int) {
        items.append(item)
    }
    var count: Int {
        return items.count
    }
    subscript(i: Int) -> Int {
        return items[i]
    }
}
```

**Comment by ykmnkmi** [comment] 2022-11-14 03:57
Try `extends`:
```dart
extension<T extends num> on List<T> {
  List<T> get reversedList => reversed.toList();
}

void main() {
  var a = <num>[1, 2.0, 3.14];
  print(a.reversedList);

  var b = <String>['1', '2', '3'];
  print(b.reversedList); // The getter 'reversedList' isn't defined for the type 'List<String>'.
}
```

**Comment by eernstg** [comment] 2022-11-14 11:13
For the 'associatedType' example, the following can be used in Dart:

```dart
abstract class Container<Item> {
  void append(Item item);
  int get count;
  Item subscript(int i);
}

class IntStack implements Container<int> {
  final List<int> items = [];
  void push(int item) => items.add(item);
  void append(int i) => items.add(i);
  int get count => items.length;
  int subscript(int i) => items[i];
}
```

I'll close this issue because it is all working as intended.

@rubenferreira97, if you were aiming for something else when you mentioned the `associatedType` feature in Swift, please create a new issue and explain in more detail what you're looking for!

**Closed by eernstg** 2022-11-14 11:13 UTC
Labels: request
