### ISSUE TITLE
Allow `==` on Enum values in const expressions.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#312] opened 2019-04-11 18:07 UTC
As reported in:
  - https://github.com/dart-lang/sdk/issues/26980
  - https://github.com/dart-lang/sdk/issues/36511
  - https://github.com/dart-lang/sdk/issues/36564
  - https://github.com/dart-lang/sdk/issues/36528

The specification does not allow `==` to be used on enum values in const contexts.  This seems reasonable to allow, customers have asked for it, and it should be an easy change to make.

Example from https://github.com/dart-lang/sdk/issues/26980
``` dart
enum MyEnum { a, b }

class Test {
  const Test(MyEnum arg) : value = arg == MyEnum.a ? 0 : 1;
  final int value;
}

void main() {
  Test q = const Test(MyEnum.a);
  Test r = const Test(MyEnum.a);
  print(identical(q, r));
}
```

**Comment by leafpetersen** [comment] 2019-04-11 18:07
cc @Hixie @mit-mit

**Comment by mpfaff** [comment] 2020-08-10 03:59
Is anything being done about this? It seems like a pretty basic language feature, especially considering how weak Dart's enums already are.

**Comment by mit-mit** [comment] 2020-08-10 09:29
@Hixie looks like you opened https://github.com/dart-lang/sdk/issues/29278 originally; do you still believe this would be a solid improvement?

**Comment by Hixie** [comment] 2020-08-10 22:25
I think this is table stakes. I think we should go much, much further and allow all code in const expressions except code that ends up having side-effects (e.g. opening sockets, printing to stdout, accessing the filesystem, that kind of thing).

**Comment by rdnobrega** [comment] 2020-08-27 19:10
@mit-mit Why wouldn't it be? Enums are already constant-like structures, and using static class members is just a lot of boilerplate code for such a simple thing...

**Comment by mit-mit** [comment] 2020-08-28 08:31
> Why wouldn't it be?

I'm not saying it isn't, just asking for input.

**Comment by rdnobrega** [comment] 2020-08-28 11:42
@mit-mit Hi! I'd like to say what I think and am trying to do and would like your feedback on the topic. I have a list of type of working hours, being 4: hflex, hnor, hnot, henor. Today we can write with a class for const expressions:

`class WorkType {
  final int _value;
  static const HFLEX = WorkType._internal(0);
  static const HNUCL = WorkType._internal(1);
  static const HENOR = WorkType._internal(2);
  static const HENOT = WorkType._internal(3);
  const WorkType._internal(this._value);
}`

with enums, I'd like to write like this:
`enum WorkType { HFLEX, HNUCL, HENOR, HENOT }`

Furthermore, I'd like enums to be even more flexible, first with value setting for ints only:
`enum WorkType { HFLEX: 0, HNUCL: 1, HENOR: 2, HENOT: 3}`

and being even more flexible, enumeration with another enums:
`enum WorkType { HFLEX, HNUCL, HENOR, HENOT }`
`enum WorkGroup<WorkType> { Group1: WorkType.HNUCL + WorkType.HENOR + WorkType.HENOT }`

This would allow loop in WorkType.values() without the concern of getting groups instead of single enum values.

This would help A LOT coding flags. Of course, all of this is already possible with classes, but it is a lot more code and doesn't really quite match.

**Comment by eernstg** [comment] 2021-08-19 12:42
This feature could be expected to be available in Dart already: An instance of an `enum` class has primitive equality, and that is the property that we otherwise require when constant evaluation needs to evaluated `==`. So it's a surprising exception that `operator ==` in constant expressions isn't specified using the same concept. Cf. #1811 where this generalization is proposed.

**Comment by lrhn** [comment] 2021-09-29 07:42
Closing as duplicate of #1811.

**Closed by lrhn** 2021-09-29 07:42 UTC
