### ISSUE TITLE
Function parameters casting

### ISSUE THREAD

**Issue by 4lfant** [dart-lang/language#310] opened 2019-04-10 17:52 UTC
### Problem
I recently faced with the problem that function parameters cannot be cast automatically, so I cannot pass

```dart
void someFunction(String)
```

 as parameter into 

```dart
void anotherFunction(void Function(dynamic))
```

I got the error:
> The function 'someFunction' has type '(String) → void' that isn't of expected type '(dynamic) → void'. This means its parameter or return type does not match what is expected. Consider changing parameter type(s) or the returned type(s).  dart(strong_mode_invalid_cast_function_expr)

### Example
We can cast dynamic variables to other types, for example, this works fine:

```dart
main() {
  dynamic dynamicValue;
  String stringValue;

  dynamicValue = "123";
  stringValue = dynamicValue; // No problem
  dynamicValue = 123;
  stringValue = dynamicValue; // _TypeError (type 'int' is not a subtype of type 'String')
}
```

But when I try to cast function with dynamic parameter to function with parameter of the other type, I get the error.
```dart
void Function(dynamic) someFunction = (String stringArg) => printMessage(stringArg);
```

Or in other words:

```dart
main() {
  someFunction(stringFunction);
}

void someFunction(void Function(dynamic) function) {
  function("Hello world!");
}

void stringFunction(String stringArg) {
  print(stringArg);
}

```

### Workaround
I found the workaround for this. The solution is to add intermediate function that receive dynamic parameter and pass it to string function:

```dart
main() {
  someFunction(intermediateFunction);
}

void someFunction(void Function(dynamic) function) {
  function("Hello world!");
}

void stringFunction(String stringArg) {
  print(stringArg);
}

void intermediateFunction(dynamic dynamicArg) {
  stringFunction(dynamicArg);
}
```

But I wish that function parameters casting would be processed implicitly, without creating additional function.

### Usage
I faced with this scenario when I was implementing callbacks in my Flutter project.
I have a function that receives anonymous function parameter as callback and then saves this callback into list. Callback can receive different types of data. Later I take the callback from list and pass argument to it.

```dart
List<Function(dynamic)> _callbacks = List();

void addCallback<T>(void callback(T response) { // For example, declare T as String
  _callbacks.add(callback);
}

// Receive string response and get error
// (String) → void' isn't of expected type '(dynamic) → void'.
_callbacks[index](response);
```

So I had to add intermediate function for my callback and save it to the list.

**Comment by eernstg** [comment] 2019-04-10 17:59
If you have a function of type `void Function(String)` (which would be the type of a function declared as `void someFunction(String) {...}`) then it is actually not of type `void Function(dynamic)`.

The problem is intuitively that the expected function should accept all kinds of arguments (as long as they have type `dynamic`, which is true for all objects), but the given function insists on getting arguments of type `String`. So it's just like `num n = 42; double d = n`, you get a dynamic check which fails at run time, because `42` is not of type `double`.

The rule of thumb is that you only get a subtype with a function type by making the parameter types _more general_ (go to supertypes). In that sense, subtyping for function types has "the same direction" for the type as a whole and for the return type, but "the opposite direction" for parameter types. This is known as contravariance.

**Comment by eernstg** [comment] 2019-04-10 18:07
In any case, this is concerned with subtyping rules for functions, and I couldn't see anything which is not working as intended, so I'll close the issue.

**Closed by eernstg** 2019-04-10 18:07 UTC

**Comment by 4lfant** [comment] 2019-04-10 18:09
But I can't still understand why we can cast dynamic variable to Staring variable and cannot cast dynamic argument to String argument.

**Comment by eernstg** [comment] 2019-04-10 18:17
The cast from `dynamic` to `String` is a downcast, and it will succeed if the value of that `dynamic` expression is actually a `String`.

For the parameter type, you don't have a parameter with a certain value that you can test. You have a function with a parameter type, and you are _providing_ the value by passing an actual argument to that function when you call it. So if you have a function that accepts `String` then you can replace it by a function that accepts `dynamic`, and callers of that function will be happy (they provide `Strings`, and they are accepted). That's the reason why `void Function(dynamic)` is a _subtype_ of `void Function(String)` and not vice versa.

If you do try to use a function of type `void Function(String)` in a situation where the static type is `void Function(dynamic)` then you are perfectly justified in expecting to be able to pass a `double` to that function. But it won't have that, you must pass only `String`s. This is the reason why `void Function(String)` is _not_ a subtype of `void Function(dynamic)`.

You just have to get used to the fact that function types have parameter types that vary in the opposite direction of the type as a whole: More general arguments means more special function type. ;-)

**Comment by 4lfant** [comment] 2019-04-10 18:20
I got it. Thanks a lot for clarification, @eernstg ! :)

**Comment by lemohammed** [comment] 2023-09-01 22:39
I am inclined to I think this is actually a bug and the downcast should be done by dart natively. Or maybe my analyzer can be set to avoid implicit casting?

if I have some function

```dart
 final List<dynamic> values = ['1', '2', '3'];
  //doesn't work: Dart refuses to cast
  values.map(int.tryParse);

  // works: Dart does the casting automatically
  final dynamic n = '1';
  int.tryParse(n);

```


if void Function(String) insists on its arguments being Strings then it cant't be called with dynamic...
