### ISSUE TITLE
Generic class can't infer its concrete subtype when used as parameter.

### ISSUE THREAD

**Issue by ltOgt** [dart-lang/language#1713] opened 2021-06-28 12:23 UTC
Take the following class hierarchy (Top > Center > Bottom):
```dart
class GenericTop {}
class GenericCenter extends GenericTop {}
class GenericBottom extends GenericCenter {}
```

And another class that takes subtypes of `GenericTop` as generic parameter:
```dart
class GenericInferer<G extends GenericTop> {
  final G genericField;
  Type get g => G;
  GenericInferer(this.genericField);
}
```

Now when I create a `GenericInferer` it can infer its most concrete generic type via `genericField`.

```dart
GenericInferer(GenericBottom()).g == GenericBottom;
```

If `GenericInferer` is passed as argument to another class, this inference does not happen as far (i.e. seems to be restricted only by the field it gets assigned to):

```dart
/// Can't be generic itself:
/// Take e.g. a field `List<GenericInferer<G>>` with different `G`
class Wrapper {
  final GenericInferer<GenericCenter> inferer;
  Type get g => inferer.g;
  Wrapper(this.inferer);
}
```

```dart
Wrapper(GenericInferer(GenericBottom())).g == GenericCenter;
```

**Why is that?**
___

I can "fix" this by either creating the object before passing it or by making the generic type explicit:

```dart
final postWrapped = GenericInferer(GenericBottom());
Wrapper(postWrapped).g == GenericBottom;
```
```dart
Wrapper(GenericInferer<GenericBottom>(GenericBottom())).g == GenericBottom;
```

___

My main issue here is the inconsistency when creating the object inlined.
Which is most probably just an issue of me not understanding why this happens.

`GenericInferer.genericField` always has the correct `runtimeType`.

But in case one wants to do something based on the generic type of an object (which I do) this may introduce hard to find issues.

And the `runtimeType` is also not always useful, e.g. when the field is
`G Function() genericReturner`.

<details>
  <summary>Runnable Example</summary>

```dart

void main() {
  print("-------------");
  final alone = GenericInferer(GenericBottom());

  print(alone.g == GenericBottom); //           true
  print(alone.runtimeType); //                  GenericInferer<GenericBottom>
  print(alone.genericField.runtimeType); //     GenericBottom

  // ------------------------ "ISSUE"
  print("-------------");
  final wrapped = Wrapper(GenericInferer(GenericBottom())).inferer;

  print(wrapped.g == GenericBottom); //         false
  print(wrapped.runtimeType); //                GenericInferer<GenericCenter>
  print(wrapped.genericField.runtimeType); //   GenericBottom

  // ------------------------ ~ "FIXES"
  print("-------------");
  final _postWrapped = GenericInferer(GenericBottom());
  final postWrapped = Wrapper(_postWrapped).inferer;

  print(postWrapped.g == GenericBottom); //       true
  print(postWrapped.runtimeType); //              GenericInferer<GenericBottom>
  print(postWrapped.genericField.runtimeType); // GenericBottom

  print("-------------");
  final explicitWrapped = Wrapper(GenericInferer<GenericBottom>(GenericBottom())).inferer;

  print(explicitWrapped.g == GenericBottom); //       true
  print(explicitWrapped.runtimeType); //              GenericInferer<GenericBottom>
  print(explicitWrapped.genericField.runtimeType); // GenericBottom
}

class GenericTop {}

class GenericCenter extends GenericTop {}

class GenericBottom extends GenericCenter {}

class GenericInferer<G extends GenericTop> {
  final G genericField;
  Type get g => G;
  GenericInferer(this.genericField);
}

/// This is not generic since I would like to have something like `List<GenericInferer<G>>` with different `G`
class Wrapper {
  final GenericInferer<GenericCenter> inferer;
  Type get g => inferer.g;
  Wrapper(this.inferer);
}

```

</details>

**Comment by eernstg** [comment] 2021-06-28 13:51
This is working as intended.

The reason why `Wrapper(GenericInferer(GenericBottom()))` infers as `Wrapper(GenericInferer<GenericCenter>(GenericBottom()))` is that the context type for `GenericInferer(GenericBottom())` is `GenericInferer<GenericCenter>` (because that's the type of the parameter of the constructor), and the context type generally gets a higher priority during Dart inference than the types obtained by a bottom-up analysis.

This prioritization is useful in Dart because it uses dynamically checked covariance, and this means that the actual type argument matters:

```dart
void main() {
  List<num> nums = <int>[1, 2, 3]; // We can do this.
  for (var n in nums) {
    print(n.floor()); // No problems, we expect a `num`, but it's OK that it is guaranteed to be an `int`.
  }
  nums.add(2.71828); // Throws at run time!

  // But this is generally a more useful approach.
  List<num> nums2 = [1, 2, 3]; // It will be a `List<num>` even though it could be a `List<int>`.
  for (var in nums2) {
    print(n.floor()); // Still fine, it is guaranteed to be a `num`, and each time it happens to be an `int`.
  }
  nums.add(2.71828); // OK, because we allowed all `num`s.
}
```

As long as we are only reading the elements of the list it makes no difference that the statically known type argument is `num` and the actual dynamic type argument is `int`, but it matters when we want to modify the list.

So it's more useful for the language to give priority to the type argument in the context type during inference, rather than aiming for the most special type argument that is allowed by the elements of the list (or whatever it is that we're inferring). You could say that this makes a larger portion of Dart code invariant rather than covariant, and that helps us avoid a lot of dynamic type checks.

Sound variance (https://github.com/dart-lang/language/issues/524 and https://github.com/dart-lang/language/issues/753) could be used to avoid the dynamic checks entirely, but that hasn't happened (yet), and the community might still decide that the added rigor of the sound approaches is a bit too verbose, such that we will have a certain amount of dynamically checked variance also in the future. This means that we will probably continue to give the context type priority, at least for the kind of code that we can write today.

**Comment by eernstg** [comment] 2021-06-28 13:52
I'll close this issue because it is all working as intended.

**Closed by eernstg** 2021-06-28 13:52 UTC
Labels: request
