### ISSUE TITLE
Re: “reveal”, a concrete private member access proposal

### ISSUE THREAD

**Issue by icatalud** [dart-lang/language#760] opened 2019-12-20 20:33 UTC
**Proposal starts below at Reveal. Initial part is information to Dart team members who are unaware of certain things.**

@matanlurey , issue #693 is closed and blocked and the conditions in which the issue was closed have been put under the scope of an ethical investigation. I opened a case of a Dart code of conduct transgression. The Code of conduct team is performing an investigation on the matter.

Citing @timsneath response:
> We'll investigate and take any action we deem necessary. Out of respect for all parties, the results of code of conduct investigations may remain private.

The code of conduct transgressions in issue #693 that I have accused are the following:
- Be kind. Be courteous. Be welcoming.
- Listen. Consider and acknowledge people’s points before responding.

I asked for a deadline on the investigation, but it has not been given yet. I don't know who is responsible for that, but until there is a pronunciation from the code of conduct team, the status of #693 is not a valid reference for this subject.

**For now please assume this subject is original and discuss it under the scope of rational objective perspectives.**

I don't think there is much to discuss about the validity of this feature (unless someone has new ideas), the only thing that is in discussion is if it is worth or not implementing, but that's only possible to know upon gathering objective data, which is impossible to gather if there is no open issue about it. If you decline to listen, then you will not be able to take informed objective decisions. As stated in #759, private member access provides a convenient shortcut for a pattern that is common to some people (it's unknown how many).

I repeat the proposal, so developers from the community may see it.

### Reveal

The `reveal` keyword can only be used over classes and packages. It reveals the private scope of them in the local scope where it is used. Revealing a package does not reveal the private members of the classes.
When reveal is used in a class, it's private var context superimposes over the default scope.

```dart
Library lib;

int _counter = 0;

class _Foo() {
  int _id = _counter++;
}

///
import .... as lib;
reveal lib;

var count = lib._counter; 

class A extends lib._Foo {
  final _id = 'id';
  int id() {
    print(_id);       // 'id'
    reveal lib._Foo;     // places _Foo var context on top
    return _id++;
  }

  String strId() {
    return _id;
  }
}

class B extends lib._Foo {
  reveal lib._PrivateClass; 
  String _id;      // invalid
}
```

**Comment by matanlurey** [comment] 2019-12-21 00:43
Duplicate of #693. Please do not open new issues because you are not satisfied a previous issue was closed. I understand that this is personally important to you and you feel strongly about whether you were treated fairly, but it is inappropriate to harass the maintainers of the repository continuously. Thank you.

**Closed by matanlurey** 2019-12-21 00:43 UTC
Labels: feature

**Comment by icatalud** [comment] 2019-12-21 04:35
@matanlurey 
You are right on one thing you pointed out, I didn't notice the issue was not locked (I thought you locked it like the original one), so I could still post comments and I should have established a conversation and inform you of the code of conduct investigation over there and hear your reply before opening another feature request. It can be considered harassment, so I apologize for it.

About the rest

- This request is not a duplicate, because this time a concrete proposal was posted and that was something missing. So far no one commented a clear approach for something like this. A concrete proposal can help people see things in a different way. An ambiguous philosophical discussion about personal considerations is unlikely to capture interest.
- Issue #693 is locked, so I couldn't post the concrete proposal over there.
- It should be positive that it remains open for some time to gather information from the community. It's not reasonable to reject objective information.

It's innapropiate:
- To make subjective assumptions about people and the actions they take. It's wrong to say "I understand you feel", because there is no reliable way to know that.
- To take definitive decisions that affect others based on feelings or subjective assumptions (whenever it's possible to avoid them).
- To use as reference an issue where there are highly questionable ethical considerations. If you want to use that as reference then you should give an explanation and validate it on all those considerations. If you read carefully and objectively the comments you will notice that some of the members understood very little of what was being explained, most notably the person who closed the issue. I saw a comment from only one person who displayed understanding and helped clarify the discussion.
- To give as a reason a short comment that dismisses all what a person is saying. If you do not have the time to reply or consider what is being explained, simply do not interfere.

If you wish, I can link you the document where I objectively proof the code of conduct transgression of some of your fellow team members, which I wrote not because I feel something, but because I assume it's my responsibility, as it is the responsibility of everyone to denounce when others transgress ethical limits. In the same way you find the flaws in my actions, you should also find the flaws in the actions of your colleagues and criticize them with equal lenses and only then the moral values of your team will start rooting. Should you decide to approve them in everything they do because their are your friends then without even noticing it you will start walking over others, because others are not the ones you have see and feel every day.

**About your assumption:**

I tell you this so it may be used as an example about why it's wrong to make assumptions. I've been working with Dart daily during the last few months and I write down the features I miss while I'm developing. From time to time I decide to devote some time to come here and express them. This last week I had an idea about another issue we have been discussing after a comment I saw and I literally spent the whole week writing it, setting aside the personal project I've been working on. Today I posted it and I decided to post all other ideas I had in the stack. This was one of them, because I'm permanently struggling with the private members of the Flutter framework. None of my feelings were involved in this, I posted it for mere practical purposes, intending to help.

When there are moral transgressions I do commit to act on them, but completely rationally, because if they were emotional I would drop them. The emotion to act only lasts the first ten minutes and then you can keep living your life as if nothing happened. There is little I enjoy from having to devote time on that. I'm facing a lawsuit and my emotions wish all the time I didn't have that responsibility, because it's wearing and it drains your time in something you do not want to do when you are inspired in something else. But doing it is a social responsibility, because if people didn't rationally commit to act on moral transgressions, people and companies would be stepping over whoever they want. It takes time to enforce limits on a system that is meant to work with timelines and procedures, but it's the only way. Believe me that people that have to face the criminal that murdered a family member or raped them, does not want to face him 3 years later in the court when perhaps they were able to move on and would prefer to stop remembering that traumatic episode. But because they do go to court (despite their feelings), the rest of us can live in a better world. We should be grateful to this invisible people who had the bad luck to have to suffer others immoral actions and decide to denounce them, because they sustain the ethical limits of our society.

My suggestion is that you open the previous issue and leave it open for some time for the reasons I exposed (it’s a new undiscussed feature), but I’ll gladly hear your point of view.

**Comment by icatalud** [comment] 2019-12-24 02:07
Matan Lurey (@matanlurey),

I expect a response and I will wait for one until Friday, since it’s Christmas time. I will write the date in my calendar so I don’t forget (I do not like to leave things unconcluded). If there is no response I will assume that you have conceded to the points I gave and therefore it will be appropriate to open the same request again. You may also reply asking for more time to think about it. Because I have announced my intentions and I’m giving time to respond, it can no longer be considered inappropriate.

In the case you think otherwise and you still believe it is inappropriate and you feel harassed, I explain this preemptively:

People who abuses a person feel harassed when the abused one starts complaining against them. Criminals feel harassed when the police starts chasing them. People that breaks the law feel harassed when others take legal actions against them. Overall we feel harassed or that something is inappropriate whenever someone does something that goes against our desires. Our feelings just want the rest of the world to let us be and to not bother us. But there are rules that define how interactions with the rest of world should go, because if people acted based on how they would like things to be, we would be conflicting all the time, because everyone's judgement about right or wrong is different.

Feeling uncomfortable about something gives us a hint about something we should address, but it doesn't necessarily mean that something from the outside is wrong. Sometimes it is something in us that should change, as our expectations about the environment do not meet the reality of what has been agreed to be acceptable. Furthermore our emotions are resistant to change, so whenever we see something different it makes us feel uncomfortable, because it forces us to make an effort to reevaluate things under new variables we have not taken into account before. And because we feel uncomfortable, many times we react with hostility and that is the reason why many people (if not most) choose to not bother telling someone else that they are doing something wrong, or that they could improve on something. Telling someone anything that goes against their desires translates in us having to go through an uncomfortable moment and people that do not like feeling uncomfortable will always attempt to smile and make you feel good.
I’ll rather be with people that is straightforward with me, tells me with as much transparency as possible how they perceive what I say or do, because that is valuable information that will help me grow, improve and find the place I belong within society. Should my peers enable me in everything I do, then I’ll never have to make an effort and I will keep being the same person thinking I’m doing everything right when in reality I’m leaving an illusion enabled by my peers only to discover that when I go out to the real world I’m perceived in a completely opposite way. They didn’t tell me just because they were afraid or didn’t want to deal with my mood.

If you create a company or product, you may do whatever you want with it, as your are solely responsible for the results of your decisions. But when you are inside a company or team, whenever you make a statement or take a decision that has an implication to a group of people, you can no longer do what you feel, because your statements and decisions are representing that group. In order to address an issue you have to make the effort to abstract from yourself and attempt to be objective under the rules and values of the company or team that you are representing, which is what a judge does when he has to pass a sentence in court.

Objective statements do not exist by themselves, they exist under the scope of a context of rules. When people complain to a supermarket when they buy one kilogram of apples but instead receive one pound, their complaint is valid under the context that labels must represent faithfully what is being sold. In the same way, I had expectations about interactions related with Dart as a whole, expectations created when I explored the product to make a decision of whether or not I should embark into Flutter. Among the considerations that convinced me to embark were the code of conduct ones, because I particularly care about that and I felt represented by them. I complained to the Dart code of conduct under the context of its statements and the values of the company the product belongs. Based on that I determined objectively that there was unethical behavior from some of the team members in the same way someone complains when the label of a product does not represent it. I never based myself on feelings as you tried to make it look to invalidate my claim. Should you reply to my comment and talk about my complaint or attempt to reference issue #693, don’t be lazy and make objective statements in the same way I did, because by being polite and saying you understand, the reality is that you are hiding a disrespectful action which is dismissing all objective points raised and all the effort that was made to unveil them, simplifying the situation in a triviality. Not only that, but are disrespecting some of your own colleagues, because decisions based on subjective statements can only represent you and people that is biased to favor you. If you want to claim that something is inappropriate, you cannot just declare it like that, you have to objectively justify it under a context of rules.
