### ISSUE TITLE
[Enum] generic, constraint, types and named parameters for ADT Enums

### ISSUE THREAD

**Issue by cindRoberta** [dart-lang/language#2006] opened 2021-12-02 19:57 UTC
Dart enums are anemics and force us to use class

### Dart Proposal
```dart
enum Option<T> {
    None,
    Some(T)
}

var functor = Option<int>.Some(4);
```
```dart
enum IpAddr {
    V4(String),
    V6(String)
}

var ip = IpAddr.V4("0.0.0.0");
```
```dart
enum IpAddr {
    V4(int, int, int, int),
    V6(String)
}

var ip = IpAddr.V4(192, 168, 1, 1);
```
```dart
enum Message {
    Quit,
    Move({ int x, int y }),
    Write(String),
    ChangeColor(int, int, int)
}

var message = Message.Move(x: 45, y: -82);
```
### Rust Enums
```rust
pub enum Option<T> {
    None,
    Some(T)
}
```
```rust
enum IpAddr {
    V4(String),
    V6(String)
}
```
```rust
enum IpAddr {
    V4(u8, u8, u8, u8),
    V6(String)
}
```
```rust
enum Message {
    Quit,
    Move { x: i32, y: i32 },
    Write(String),
    ChangeColor(i32, i32, i32)
}
```

**Comment by mateusfccp** [comment] 2021-12-02 20:20
Duplicate of #349.

**Comment by cindRoberta** [comment] 2021-12-02 20:50
relateds:
https://github.com/dart-lang/language/issues/158
https://github.com/dart-lang/language/issues/546

**Comment by cindRoberta** [comment] 2021-12-02 21:07
```dart
enum Foo {
    Bar,            // 0
    Baz = 123,      // 123
    Quux,           // 124
}
```

**Comment by Levi-Lesches** [comment] 2021-12-02 21:18
I think this can be closed now that the [enhanced-enums](https://github.com/dart-lang/language/blob/master/accepted/future-releases/enhanced-enums/feature-specification.md) proposal is being worked on. Issue #158 is the official tracking issue for the topic.

**Comment by cindRoberta** [comment] 2021-12-02 22:42
> I think this can be closed now that the [enhanced-enums](https://github.com/dart-lang/language/blob/master/accepted/future-releases/enhanced-enums/feature-specification.md) proposal is being worked on. Issue #158 is the official tracking issue for the topic.

I think this is very verbose and unnecessary, I've never seen it anywhere. The variations I know are Haskell's `data`, Rust's `enum`, and V's `type` (sumtype)

https://github.com/vlang/v/blob/master/doc/docs.md#sum-types

**Comment by Levi-Lesches** [comment] 2021-12-03 01:18
I don't quite understand your concern. Looking at your examples, you seem to be asking for a way to give enums parameters and fields, like regular classes. I see that some of your examples don't take any arguments, or have a different signature than the other elements of the enum, but that's a smaller detail. The enhanced-enums proposal gives you the ability to treat enums like regular classes. Combine that with the idea of [enum-like](https://dart-lang.github.io/linter/lints/exhaustive_cases.html) classes and you should be fine. Your first example would be something like: 

```dart
/// Enum-like class -- works today.
class Option<T> {
  final int? value;
  const Option([this.value]);

  static const none = Option();
  static const functor = Option<int>(4);
}

/// Enhanced enum -- requires the enhanced-enum feature.
enum Option<T> {
  none(),
  functor<int>(4);

  final T value? 
  const Option([this.value]);
}
```

**Closed** 2021-12-03 02:34 UTC
Labels: feature
