### ISSUE TITLE
'Switch-case' shorthand syntax 

### ISSUE THREAD

**Issue by Den163** [dart-lang/language#703] opened 2019-11-23 09:33 UTC
This is about an antique C-syntax construction like a 'switch-case' statement. In my experience, the use case of it is often like a map some value 'A' to another value 'B'. Therefore, some modern languages try to simplify this case (influenced by functional languages like Haskell, I think). So it will be nice if Dart would have something like that.
For example, Kotlin has 'when' operator :
``` kotlin
val aStr = when (a) {
    1 -> "first"
    2 -> "second"
    3 -> "thrird"
    else -> "${a}th"
}
```
C# 8.0 has something the same: 
``` C# 
a switch 
{
    1 => "first",
    2 => "second",
    3 => "third",
    _ => $"{a}th",
};
```
Notice that in both of languages improved 'switch-case' is not a statement, but an expression that 
prevent us to wrap statement into the function to get this sort of a 'mapping'.

In Dart to get this result, I need to:
1. Wrap all values in the map and check in the getter function - is the key argument exist in the map:
``` dart
final _values = const {
  1 : "first"
  2 : "second"
  3 : "third"
}

String getValue(final int a) => _values[a] ?? "${a}th";
```
Or 

2.  Write so cumbersome, a C-like switch statement function:
``` dart
String getValue(final int a) {
  switch (a) {
    case 1: return "first";
    case 2: return "second";
    case 3: return "third";
    default: return "${a}th"
  }
}
```
In other cases in my opinion it's better to avoid an antique 'switch-case' statement to improve code readeablitiy.

**Comment by tatumizer** [comment] 2019-11-23 13:56
How about
```
x.(switch {
    1 : "first",
    2 : "second",
    3 : "third",
    default: $"{a}th",
});
```
and
```
x.(match {
    String : "got Sting",
    int : "got int",
    default: "got something unexpected",
});
```

**Comment by lrhn** [comment] 2019-11-25 06:47
You can write the map literal inline, so it would be:
```dart
String getValue(final int a) => const {
  1 : "first",
  2 : "second",
  3 : "third",
}[a] ?? "${a}th";
```
That's not too far from the switch. It does require the expressions to be constant, or if the map is not constant, then all of the expressions are evaluated on each use.

Making `switch` into an expression matches with similar requests for `if` and other statements. I am not too optimistic about changing statements to expressions in general, but a way to embed a statement in an expression, without wrapping it in a new function, might be useful.

**Comment by tatumizer** [comment] 2019-11-25 14:30
> ...without wrapping it in a new function...

There's a problem of "return". Syntax should make it obvious that "return" returns the value of the expression, as opposed to the outer function. E.g.
```
var x = *switch  a { // asterisk before "switch" makes it an expression
   1: return "first";
   2: return "second";
   default: return "${a}th";
}
```
Is asterisk alone good enough to prevent confusion - I don't know, but if it is, the syntax can generalized to apply to other statements, e,g, `*{...}` could denote an executable block;
`*if` - conditional expression, etc. Example:
```
var x = 
  *if (z==0) return 0; 
  else if (z==1) return 1; 
  else return -1;
```

**Comment by mnordine** [comment] 2019-11-29 01:12
I think this has been discussed in many existing issues. I think this proposal may satisfy you?

https://github.com/dart-lang/language/issues/546

It mentions switch expressions and links to 2 reheated issues

**Comment by GregoryConrad** [comment] 2022-09-26 00:51
Here's a clean workaround when dealing with an enum and you want to be sure you cover all enum options (which unfortunately isn't possible with the `Map` workaround):
```dart
final resultOfExpression = (){
  switch(value) {
    case SomeEnum.foo:
      return 'fizz';
    case SomeEnum.bar:
      return 'buzz';
  }
}();
```
Worth mentioning: in lots of use cases, the above can be achieved better by using enhanced enums with a member field for whatever you are trying to access. Sometimes though, this little trick can come in handy.

**Comment by gaaclarke** [comment] 2022-09-29 20:05
Dart already does have a switch expression of sorts with nested ternary operators.

```dart
final x = y ? 1 : (z ? 2 : (w ? 3 : 4));
```

It's cumbersome but it is the only way you can initialize const fields.  In that sense a switch expression could just be syntactic sugar on the front end that transforms to nested ternary operators (and hopefully does a completeness check).

Getting a bit philosophical, if you don't mind, Dart was designed to be an optimal expression of well known languages at the time it was made.  It was designed, imo, to make it an easy transition from another popular languages and I think it did a marvelous job at that.  Right now we are experiencing a great shift to the next generation of languages, Objc->Swift, Java->Kotlin, C++->Rust, so the question becomes "Does Dart want to maintain familiar for the last generation of languages, or does it want to be familiar to the next generation of languages?"  What was odd when Dart was designed is now becoming common place.  A "switch expression" (which my guess actually comes from ML's `match`) appears to be more and more common and it missing from Dart is going to become more and more of an oddity, adding to the barrier-of-entry that is being constructed over time by the shift in programming languages.

**Comment by gaaclarke** [comment] 2022-09-29 20:14
It also looks like this issue is just a version of https://github.com/dart-lang/language/issues/27

**Comment by munificent** [comment] 2022-09-30 00:42
Note that with the in-progress patterns proposal, you can write:

```dart
val aStr = switch (a) {
    1 => "first";
    2 => "second";
    3 => "thrird";
    _ => "${a}th"
}
```

**Comment by Levi-Lesches** [comment] 2022-09-30 02:44
Would be cool if there could be a list somewhere of all the issues that will be fixed with records/other featuers so they can all be closed at once

**Comment by munificent** [comment] 2022-10-03 22:38
I'm trying to label all issues related to patterns and records with [patterns](https://github.com/dart-lang/language/labels/patterns) or [records](https://github.com/dart-lang/language/labels/records). There's also a pair of "later" labels for issues related to those that likely won't be addressed in the initial release. It's probably not entirely comprehensive because there isn't always a perfect mapping between a user request and a specific language feature, but most of them should be in there.

**Comment by munificent** [comment] 2023-03-28 19:38
Closing this because records and patterns are now enabled by default on the main branch of the Dart SDK! 🎉

**Closed by munificent** 2023-03-28 19:38 UTC
Labels: feature, patterns

**Comment by stefan-sherwood** [comment] 2023-06-17 12:45
A succinct and readable way to do this is:

```
var aStr = {
  1: "first",
  2: "second",
  3: "third"
}[ which ] ?? "${which}th";

```

**Comment by erayerdin** [comment] 2023-07-16 13:55
> Note that with the in-progress patterns proposal, you can write:
> 
> ```dart
> var aStr = switch (a) {
>   case 1 => "first";
>   case 2 => "second";
>   case 3 => "thrird";
>   case _ => "${a}th"
> };
> ```

`case` in this expression causes compile-time error. Remove them.

**Comment by mateusfccp** [comment] 2023-07-16 14:17
> > Note that with the in-progress patterns proposal, you can write:
> > ```dart
> > var aStr = switch (a) {
> >   case 1 => "first";
> >   case 2 => "second";
> >   case 3 => "thrird";
> >   case _ => "${a}th"
> > };
> > ```
> 
> `case` in this expression causes compile-time error. Remove them.

Yes, not only the `case` keyword, but the `;` too.

In Dart 3.0, this is the correct syntax:

```dart
var aStr = switch (a) {
  1 => "first",
  2 => "second",
  3 => "thrird",
  _ => "${a}th",
};
```

**Comment by munificent** [comment] 2023-08-10 22:38
Life comes at you real fast! :D Yes, we change the switch expression syntax after I wrote that comment. Thanks for the corrections.
