### ISSUE TITLE
`factory required`  constructor signature

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/language#2339] opened 2022-07-08 18:29 UTC
I was creating a controller to save a value and query it. And I figured, why cant we create a `factory required` constructor inside an abstract class?

Something like:

```dart
abstract class A {
  factory required A.fromMap(Map<String, dynamic> map);
  Map<String, dynamic> get map;
}
```

This way, with the `required` keyword or anything similar we could create a necessity for subclasses to implement this `factory` named controller.

Making so that we would have a better way to create parsers easier.

**Comment by jakemac53** [comment] 2022-07-08 18:40
There has generally been some discussion before around having a "static interface" for classes, which I think is the same as what you are asking for here.

I do generally agree it would be useful, especially if you want to be able to construct an instance of a generic type variable, which is something that comes up somewhat often. That would enable essentially something like this:

```dart
abstract class B<T extends A> {
  final T a;
  
  B.fromMap(Map<String, dynamic> map)
    // We can call `T.fromMap` since it's a part of the "static interface", yay!
    : a = T.fromMap(map['a'] as Map<String, dynamic>);
}
```

**Comment by lrhn** [comment] 2022-07-08 19:13
The problem with static interfaces that subclasses must implement is that they are (some combination of)
* not inherited, so every class has to implement them again, 
* not able to refer to the containing class (or not do so contravariantly),
* not implemented by `Never`, or
* not really something you can use using existing type parameters anyway.

Here you want a `static A fromMap(Map<String, dynamic>` method (constructor, but that's not important) on every subclass of `A`.  Except that that's precise, because it should probably return `B` on the subclass `B`. What if it returned `A` anyway? Would that be OK? If not, we need a notion of "self type" in the signature, which Dart currently doesn't have.
What if `B.fromMap` it returned `C`, a further subclass of `B`, or just of `A`? Is that OK? 

What if `D` extends `A` is an abstract class. It can't have a callable `D.fromMap` generative constructor. It can be a factory constructor, but then it must return a subclass, because it can't be a plain `D`.

The idea is to be able to use the functionality on a type parameter, so you can do `T build<T extends A>(... map) => T.fromMap(map);`. 
However, as Dart is currently defined, it means  *every subtype of `A`* must have a `fromMap`. Since `Never` is a subtype of any type, it must have all static methods. It doesn't. (Its instances have all instance methods, which is fine because there are no instances, but there is a `Never` type!).

All in all, it seems like you'd rather have `T  build<T with {static T fromMap(Map<String,dynamic>)}>(...map) => ...`, which is a *structural* constraint on the types that can be passed to `build`.
It's not subtype based - just because a type is valid, it doesn't mean that all subtypes are.
So, something completely new.

**Comment by jakemac53** [comment] 2022-07-08 19:52
> * not inherited, so every class has to implement them again,

That is imo a perfectly acceptable result of enforcing a static interface for a class.

> * not able to refer to the containing class (or not do so contravariantly),

Can you elaborate a bit on what you mean by this?

> * not implemented by Never, or

What is the distinction between instance members and static members here? Could you not specialize `Never` such that it implements all static interfaces, but they always throw if invoked? 

> * not really something you can use using existing type parameters anyway.

What do you mean by that?

> Here you want a `static A fromMap(Map<String, dynamic>` method (constructor, but that's not important) on every subclass of `A`. Except that that's precise, because it should probably return `B` on the subclass `B`. What if it returned `A` anyway? Would that be OK? If not, we need a notion of "self type" in the signature, which Dart currently doesn't have.

Interesting question, I definitely do think it should be required to return a `B` or some subclass of `B`. 

> What if `B.fromMap` it returned `C`, a further subclass of `B`, or just of `A`? Is that OK?

Also an interesting question, my intuition is a subclass should be fine, (but not `A`). But maybe it would be based on whether the interface was specified as a factory constructor or regular constructor. Pretty weird though for that to matter. If it is just a normal static method then `A` would be fine.

I suppose you could introduce a new concept which is some "self type" as you mentioned, and have more direct control over it that way.

> What if `D` extends `A` is an abstract class. It can't have a callable `D.fromMap` generative constructor. It can be a factory constructor, but then it must return a subclass, because it can't be a plain `D`.

Yeah I think you would have to require an implementation of the static interface, even for abstract classes. That might mean abstract classes cannot implement certain static interfaces, depending on how things are specified elsewhere.

**Comment by Levi-Lesches** [comment] 2022-07-08 20:26
The discussion before has led to the idea of a static-only interface, which should solve the problem regarding `Never`. 
```dart
static abstract class FromJson {  // ignoring that this would imply an instance method [toJson]
  static FromJson fromJson(Map<String, dynamic> json); 
}

class User extends FromJson {
  @override
  static User fromJson(Map<String, dynamic> json) =>  // ...
}
```

I won't speak much of the syntax, but it could fix a number of problems:

> * not inherited, so every class has to implement them again,
>
> ...
> What if `D` extends `A` is an abstract class. It can't have a callable `D.fromMap` generative constructor. It can be a factory constructor, but then it must return a subclass, because it can't be a plain `D`.

Inheritance would work the same way as current abstract classes, which can have abstract or concrete members. 

> * not able to refer to the containing class (or not do so contravariantly),

You would refer to the class itself by the name of the abstract interface (in this case `FromJson`). Similarly to instance interfaces, if a subclass uses a more specific type, that's okay.

> * not implemented by `Never`

If `Never` is a problem, then perhaps the semantics could be that `Never` is _not_ the bottom type for static interfaces. I'm guessing that won't break much since it wouldn't change the existing semantics for instance members. In cases where there is no type to infer, the inference would just fail. I don't know enough about the type system to know if that's actually feasible, just a suggestion. 

> * not really something you can use using existing type parameters anyway.

Would work just like a regular abstract class.

**Comment by munificent** [comment] 2022-07-09 00:38
This sounds like a duplicate of https://github.com/dart-lang/language/issues/356, so I'm going to close this so that we don't fork the discussion.

**Closed by munificent** 2022-07-09 00:38 UTC
Labels: feature

**Comment by lrhn** [comment] 2022-07-11 09:14
Just answering the questions here, do go to #356 for further discussion.

> > * not able to refer to the containing class (or not do so contravariantly),

> Can you elaborate a bit on what you mean by this?

If class `A` has a static interface containing a copy-constructor `static A copy(A value);` (depending on whether the static interface distinguishes between constructors and static methods, I think it probably shouldn't, unless you want to be able to extend a type variable.)

The subclass B should then have a `static B copy(B value);`, but that's not a valid override of A's copy-constructor, because the parameter behaves covariantly.
I guess we could just define the one in A as `static A copy(covariant A value)`.

That still allows B, with subclass C, to define `static C copy(C value);`. That's a valid override of the covariant `A` member.
To actually enforce that `B` has a copy constructor accepting B instances, we need some (new) notion of "self type".

That's not trivial to define. It would be inherently covariant, even when occurring contravariantly.

It might be usable in instance classes too: `class Comparable<T super $Self>` would require the type parameter to accept the comparable itself, which is what you need to ensure a total ordering.
 
But definitely not trivial.

> > * not implemented by Never, or

> What is the distinction between instance members and static members here? Could you not specialize `Never` such that it > implements all static interfaces, but they always throw if invoked? 

You can define static methods on `Never` to always throw, but that's unsafe.

`Never` having all instance interfaces work because we know it has no instances. There is no *counter-proof* to a `Never` having all interfaces, it holds vacuously.

`Never` having all static interfaces is countered by `Never` being a concrete type that doesn't actually have all interfaces.
You can reach the point where you try to call a static interface method, and the runtime will have to do *something*.
Throwing is *sound* (throwing is always sound, a program which does nothing else has no type errors), but it's not *safe, and people want safe.

It's also a problem to implement using V-tables, because a class can't have all V-tables. Every such invocation needs an extra check for "is this `Never`, if so throw" before going back to the desired static behavior.
If static member invocations are inherently structural, instead of nominative, then invocations will likely be dynamic anyway, but that risks not being as efficient.

>> * not really something you can use using existing type parameters anyway.

> What do you mean by that?

The issues above suggests, to me, that we won't require every subclass to satisfy the static interface.
Rather, we'd have static interface constraints on type parameters, and reject passing in a type which isn't known, at compile time, to satisfy that static interface. Merely being a subtype of a satisfying type is not sufficient to satisfy that. `Never` is the canonical counter-proof.
You can probably also have other classes in your hierarchy, say abstract base classes, which don't have their own copy constructor. (Can we have "abstract static interfaces", which specify the interface, but doesn't implement it?)

Or, if we use the nominative approach and has a `static interface FromJson` declaration, then any class can static-implement `FromJson`, but it's not required that all subclasses of that class also do. It's a separate inheritance hierarchy.
And yes, in that case `Never` doesn't implement any static interfaces, and the static type hierarchy doesn't necessarily have a bottom element. (The top element would be the empty static interface that all classes implement by default.)

At this point, we're getting close to just letting classes be objects implementing interfaces (no need to make them *static* interfaces then). A class with static members is just a singleton object instance, with an interface defined by the class declaration, and implementing the statically implemented interfaces.
Very close to Swift companion objects.

Then you'd can parameterize your type parameters in both ways: `<T extends Foo static Bar>` (`<T extends static Bar>` is equivalent to `<T extends Object? static Bar>`.

If we want individual "class objects" to implement general interfaces, we'd probably have to separate the static and instance namespaces, so you can declare a member in both, say:
```dart
class Foo extends Bar static Baz {
  String toString() => "Bar!";
  static String toString() => "Baz!";
}
void main() {
 print(Foo()); // Bar!
 print(Foo); // Baz!
}
```

It gets complicated. I think the companion object is a more honest way to say that classes have object-behavior.
