### ISSUE TITLE
Is this augmenting variable declaration actually allowed?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#3958] opened 2024-07-03 17:05 UTC
The augmentation specification seems to allow the following configuration:

```dart
// Original.
int x = 1;

// First level of augmenting declarations.
augment int get x => augmented + 1;
augment set x(int value) => augmented = value - 1;

// Second level of augmenting declarations.
augment int x = augmented + 2;
```

The following sentence in the specification justifies this situation, in the section about 'Augmenting a getter and/or setter with a variable':

> If a non-abstract, non-external variable is augmented by an augmenting getter or setter, you can still augment the variable, as you are only augmenting the initializer of the original variable. This is not considered to be augmenting the augmenting getter or setter, since those are not actually altered.

My reading of this would be that the variable `x` is initialized to have the value 3, and an evaluation of `x` would then yield 4. In other words, `augmented` at the second level of augmentation refers to the original, not the first level of augmentation.

Isn't that somewhat surprising? :grinning:

If we do continue to allow this then we should probably also allow adding a DartDoc comment and/or metadata (#3957).

**Comment by jakemac53** [comment] 2024-07-03 17:09
You do read it correctly. It might be a bit weird, but I think it is also fairly easy to rationalize/explain.

I do also think we should allow doc comments and metadata.

**Comment by lrhn** [comment] 2024-07-03 22:30
Agree that it can be explained. You can augment either the implicit getter, the implicit setter or the initializer expressions. Those are distinct entities, and are augmented independently.

**Comment by jakemac53** [comment] 2024-07-08 17:12
I am going to close this one - given it is specified as intended.

**Closed by jakemac53** 2024-07-08 17:12 UTC
Labels: question, augmentation-libraries

**Comment by eernstg** [comment] 2024-07-08 17:16
OK! @sgrekhov, do we have a test? ;-)

**Comment by sgrekhov** [comment] 2024-07-09 07:17
Not yet. But will be!
