### ISSUE TITLE
Allow type instantiation as expression.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#123] opened 2018-12-04 12:12 UTC
Dart does not allow you to write `List<int>` as an expression evaluating to a `Type` object, instantiating the generic class. This is inconvenient to users, who have to resort to helper functions like `Type typeOf<T>() => T;`.

Dart does not allow you to write `genericFunction<int>` to create a specific type instantiation of a generic function, but it does allow `T id<T>(T x) =>x; int Function(int) intId = id;` to *implicitly* instantiate the generic function. It should be possible to write the type explicitly.

Dart does not allow constructor tear-offs - the syntax `Foo<int>` or `Foo<int>.named` are not valid expressions. if `Foo<int>` was allowed syntax, then this would be an easy extension.

So, as a feature, Dart should allow type instantiation of all generic elements (typedefs, classes and functions) and allow constructor tear-offs.
The syntax `List<int>` can be seen both as a type and as the name of the unnamed constructor. I propose using the context type to distinguish: If the context type is `Function` or any function type, the expression is considered a tear-off of the unnamed constructor, otherwise it is a `Type` object.

This looks like two features, but because of the syntactic overlap, they should be implemented at the same time.

And if `expression < type* >` is  valid expression syntax, we can also do explicit instantiation of generic method tear-offs.

(If we extend type literal syntax to allow `List<int>`, then we might also want to allow `int?` as a NNBD type literal).

**Comment by leafpetersen** [comment] 2018-12-04 21:06
We could also consider generic getters as part of this.  Unfortunately, I haven't found any good syntax for generic setters.  `x =<T> e` could work, but sure is ugly.

**Comment by munificent** [comment] 2018-12-04 23:42
>  If the context type is Function or any function type, the expression is considered a tear-off of the unnamed constructor, otherwise it is a Type object.

I think constructor tear-offs are more useful than Type objects, so I wish we could make those the default. Otherwise, things like this don't work (do they?):

```dart
(removeDuplicates ? List.from : Set.from)(elements)
```

Otherwise, this SGTM.

> We could also consider generic getters as part of this.

You know, I feel like I should want this in principle because it generalizes, but I can't say I've ever actually found myself wanting it in practice. <shrug>

> Unfortunately, I haven't found any good syntax for generic setters. x =<T> e could work, but sure is ugly.

Eek, yeah. Does this not work:

```dart
object.setter<T> = value;
setter<T> = value;
```

?

**Comment by natebosch** [comment] 2018-12-07 00:15
> I think constructor tear-offs are more useful than Type objects, so I wish we could make those the default.

It would be breaking to make `var l = List` tear off the constructor instead of being a type.

Since `var l = List.from;` or `var l = List<int>.from;` already are errors I think it would not be breaking if we use `new` as the "magic" name for the unnamed constructor: `var l = List.new`.

**Comment by leafpetersen** [comment] 2019-12-09 12:05
This should cover nullable types as well:  e.g `int?` as a literal.

**Comment by lrhn** [comment] 2020-11-09 15:09
Allowing `int?` as an expression might get us into parsing ambiguities, fx. `int?[42]` can be both `(int?)[42]` and `(int)?[42]`.
It's most likely never going to be an issue for bug-free code, but we'll have to disambiguate in some way and it might make some error recovery harder.

**Comment by eernstg** [comment] 2021-03-08 09:02
Note that a very old SDK issue, https://github.com/dart-lang/sdk/issues/11923, was used to discuss this topic as well. I closed dart-lang/sdk#11923 as a duplicate of this one, because this one is directly phrased as a language feature proposal and has the more recent discussion.

**Comment by eernstg** [comment] 2021-07-08 12:01
Added label 'constructor-tearoffs' &mdash; it's a completely different topic, but there is an organizational relation: This feature is actually being implemented now as part of the experiment `constructor-tearoffs`.

**Comment by eernstg** [comment] 2021-12-07 15:39
Closing: This feature is included today.

**Closed by eernstg** 2021-12-07 15:39 UTC
Labels: feature, constructor-tearoffs
