### ISSUE TITLE
Introduce 'when' expression

### ISSUE THREAD

**Issue by halimpuckjava** [dart-lang/language#1338] opened 2020-11-26 21:49 UTC

**Comment by mateusfccp** [comment] 2020-11-26 22:56
What is `when` expression?

**Comment by lrhn** [comment] 2020-11-27 08:54
I'm assuming the Kotlin `when` expression in some variant.
I'll close this as a duplicate of #27, which is talking about general improvements to `switch`.

If it's more about having an *expression* switch, then #762 is relevant instead.

**Closed by lrhn** 2020-11-27 08:54 UTC
Labels: feature
