### ISSUE TITLE
Support generic type `T` to extend multiple classes

### ISSUE THREAD

**Issue by nathnaeld** [dart-lang/language#4195] opened 2024-12-05 17:19 UTC
Currently, generic types can only extend one class. Allow extending multiple classes to enhance flexibility.

**Example syntax:**

```dart
class User<T extends int & String> {
  final T id;
  // Implementation
}

// Or

class User<T extends int | String> {
  final T id;
  // Implementation
}
```

**Comment by mateusfccp** [comment] 2024-12-05 18:16
Duplicate of #2709.

**Closed** 2024-12-05 18:20 UTC
Labels: feature
