### ISSUE TITLE
[Enhancement] extension on Function type which has required named parameters.

### ISSUE THREAD

**Issue by Guang1234567** [dart-lang/language#1772] opened 2021-07-30 03:16 UTC
Hello dev:

As we known, dartlang can make extension on `Function` type. This is excellent feature that make `currying optional named parameters function` possible like below.

- library

```dart
extension CurryOptionalExtension<T, A> on T Function() {

  T Function([Map<Symbol, dynamic>]) curry(Map<Symbol, dynamic> parameter) =>
      ([Map<Symbol, dynamic> params = const {}]) => Function.apply(
            this,
            null,
            parameter..addAll(params),
          );

  T Function([Map<Symbol, dynamic>]) operator %(
          Map<Symbol, dynamic> parameter) =>
      this.curry(parameter);
}

extension CurryOptionalMapExtension<T> on T Function([Map<Symbol, dynamic>]) {

  T Function([Map<Symbol, dynamic>]) curry(Map<Symbol, dynamic> parameter) =>
      ([Map<Symbol, dynamic> params = const {}]) => Function.apply(
            this,
            [
              parameter..addAll(params),
            ],
          );

  T Function([Map<Symbol, dynamic>]) operator %(
          Map<Symbol, dynamic> parameter) =>
      this.curry(parameter);
}
```

- usage

```dart
  void printAll({String a = "", int b = 0, double c = 0.0}) {
    print(a);
    print(b);
    print(c);
  }

main() {
    final void Function() func0 = printAll;
    // final func = func0 % {#a: 'Hello'} % {#b: 3} % {#c: 6.0};
    // or 
    final func = func0.curry({#a: 'Hello'}).curry({#b: 3}).curry({#c: 5.0});
    func(); // Same as printAll(a: 'Hello', b: 2, c: 4.0);
}
```

Everything is ok until the `requried named parameter` be invented on `dart 2.12.0`

I can found out the solution about making extension on some `Function` type in a general rule for below function (but not limited to):

```dart
  void printAll1({required String a, int b = 1, double c = 1.0}) {
    print(a);
    print(b);
    print(c);
  }

  void printAll2({String a = "str_2", required int b, required double c}) {
    print(a);
    print(b);
    print(c);
  }
```

Please give me some suggestion, Thanks.

**Comment by eernstg** [comment] 2021-07-30 09:02
That's an interesting experiment!

However, the detour via a `Map` and via `Function.apply` implies that there is no static type safety for the actual arguments that you're passing in a curried fashion, and there's also no type check on the set of names of named parameters. So this is basically a dynamically typed technique, which is already a pretty significant step away from mainstream Dart code.

Given that there are no static type checks on the actual arguments, you might consider dropping the type check on the return value as well:

```dart
extension CurryOptionalExtension<T, A> on Function {
  Function([Map<Symbol, dynamic>]) curry(Map<Symbol, dynamic> parameter) =>
      ([Map<Symbol, dynamic> params = const {}]) => Function.apply(
            this,
            null,
            parameter..addAll(params),
          );
  Function([Map<Symbol, dynamic>]) operator %(Map<Symbol, dynamic> parameter) =>
      curry(parameter);
}

extension CurryOptionalMapExtension on Function([Map<Symbol, dynamic>]) {
  Function([Map<Symbol, dynamic>]) curry(Map<Symbol, dynamic> parameter) =>
      ([Map<Symbol, dynamic> params = const {}]) => Function.apply(
            this,
            [
              parameter..addAll(params),
            ],
          );
  Function([Map<Symbol, dynamic>]) operator %(Map<Symbol, dynamic> parameter) =>
      curry(parameter);
}
```

**Comment by eernstg** [comment] 2021-07-30 09:11
I don't think there's a language proposal within reach (that is, without radical changes to Dart) that would allow us to achieve type safe invocations based on this kind of technique.

So I'll close this issue because (1) the language features in use in the given example code are working as intended, and (2) any language proposal about doing this in a type safe manner would be very substantial. So if we would want to go that way, we'd discuss it in a separate issue (or 100 new issues ;-).

**Closed by eernstg** 2021-07-30 09:11 UTC
Labels: request

**Comment by Guang1234567** [comment] 2021-07-30 10:15
@eernstg 

Thanks your reply.

BTW, 

 > the detour via a Map and via Function.apply implies that there is no static type safety

I am informed.
