### ISSUE TITLE
[NEW] variable argument list, like `va_list` in C, and `Varargs` in Java

### ISSUE THREAD

**Issue by gintominto5329** [dart-lang/language#2821] opened 2023-02-06 12:55 UTC
Hello,

In other, and **mature** languages like C/CPP, and Java, there is a concept of **variable arguments**(va),

### Prominent use in existing(and mature) langs: 
- In C, `va_list` is used in the `stdio.h`'s `printf(format, ...)` function, which takes a minimum of one, and a super-large(but finite) number of additional arguments, and 
- In Java, `varargs` are used in [`java.util.Arrays.asList(T... a)`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Arrays.html#asList(T...))

### Why?
Dart is facing a problem, which is "Non-growable lists are implemented more efficiently than growable lists, but creating one is rather verbose and inconvenient"(from #2477([#2477](https://github.com/dart-lang/language/issues/2477))),

The new syntax, being proposed in that issue, is:
- `            <int>[0, 1, 2]` for growable list, same as current/present
- [NEW] `final <int>[0, 1, 2]` for non-growable/fixed-length list/array
- [NEW] `const <int>[0, 1, 2]` for non-modifiable/immutable list

#### Problem 
The reserved words, `final`, and `const` are for, and act on the underlying `Object`, which is `List<int>` here, and has no relation with the grow-ability or im-mutability of the entity/list, the proposed syntax seem like **patchy work** to me, and would definitely degrade the quality/logic in the syntax, and the trust of public, in dart's team

### Solution
Adding var-args to dart would allow us to:
- `List<int>(0, 1, 2)` for growable list, with def as `List<T>(T... va)`
- `Array<int>(0, 1, 2)` for non-growable/fixed-length list/array
- `FirmList<int>(0, 1, 2)` for non-modifiable/immutable list

`ArrayList` over `Array`, is possible, but more chars, and same for `ImmutableList`/`UnmodifiableList` over `FirmList`, maybe `ImmuList`/`UnmodList` could be used,

thanks

`va_list` in C: [cppreference.com](https://en.cppreference.com/w/c/variadic/va_list), [cprogramming.com](https://www.cprogramming.com/tutorial/c/lesson17.html)

`Varargs` in Java: [docs.oracle.com](https://docs.oracle.com/javase/8/docs/technotes/guides/language/varargs.html)

**Comment by julemand101** [comment] 2023-02-06 13:03
Sounds very much related to: https://github.com/dart-lang/language/issues/1014

**Comment by jakemac53** [comment] 2023-02-06 17:21
> "Non-growable lists are implemented more efficiently than growable lists, but creating one is rather verbose and inconvenient"

Fwiw this isn't universally true - on the web at least non-growable lists may actually add additional checks since it uses a growable JS array, which it then has to ensure doesn't actually grow.

I think the desire for this feature is valid regardless though.

**Comment by munificent** [comment] 2023-02-07 00:48
Closing as dupe of #1014.

(In practice, the typical workaround is to just define a function that takes a List. Since Dart has very compact list literals, that's only two characters longer than varargs.)

**Closed by munificent** 2023-02-07 00:48 UTC
Labels: feature
