### ISSUE TITLE
Should switch statements be exhaustive?

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#2474] opened 2022-09-10 01:42 UTC
The patterns proposal is currently silent about compile errors related to exhaustiveness checking on patterns, though it does talk about exhaustiveness checking as a *concept*. That needs to be filled in.

Switch *expressions* need to be exhaustive because otherwise there may not be a value that the switch expression can evaluate to. We could silently throw a runtime exception if no cases match, but I don't think anyone wants that.

It's less clear what the right answer for switch statements is. Currently, the language only reports static warnings for non-exhaustive cases when switching on an enum type. For all other types, it is happy to let you have unmatched values and no default case.

For switch statements *on sealed families*, I think users want it to be at least a warning if the cases are not exhaustive.

I suspect that switching on other unsealed types would be very annoying if we required users to write a default clause. It would certainly be extremely breaking.

Based on that, I propose:

* It is a compile-time *error* for a switch *expression* to not be exhaustive, regardless of the type being switched on. In practice, this means that for unsealed types, you'll need a `default` case, untyped variable, or wildcard that matches everything.
* It is a compile-time *warning* for a switch *statement* to not be exhaustive *when the static type of the matched value is a "sealed type".*
* For switch statements on any other type, it's fine for it to not be exhaustive.

A "sealed type" is:

* Bool
* Null
* Any enum type
* Any type marked as sealed using an as-yet-unspecified way
* A nullable type whose underlying type is sealed
* A record type whose fields are all sealed types

*TODO: Figure out how generic type arguments come into play.*

How does that sound?

**Comment by Jetz72** [comment] 2022-09-12 15:40
The small gripe I have with requiring exhaustiveness is that sometimes the cases of a switch can be logically exhaustive, even if the compiler is unable to ensure it. If you're switching over an integer that you've already confirmed is in a certain range of values and have cases for every one of those values, having to tack on something like `default: throw AssertionError("This should never happen")` to satisfy impossible alternative cases is really ugly.

It'd be nice if there was a shorthand for asserting that a switch expression is exhaustive, the way the `!` operator asserts that a value is nonnull. Can't think of a way that looks elegant though.

**Comment by Levi-Lesches** [comment] 2022-09-12 16:33
Integers and numbers in general aren't considered "sealed", so your example wouldn't change from today's behavior (unless you're referring to a switch expression, in which case, see below). 

I also disagree that it's "really ugly". Imagine this example: 
```dart
int findElement(List<int> numbers, int index) {
  if (index >= numbers.length) return -1;  // check for out-of-bounds
  // imagine this is a switch expression with < and > syntax instead
  return switch (index) {
    case 0: return numbers[0];
    case 1: return numbers[1];
    // ...
  }
}
```

One might imagine this is exhaustive, but we haven't checked for `index < 0`. 

> If you're switching over an integer that you've already confirmed is in a certain range of values and have cases for every one of those values

The point of the example is to show that the only way to _prove_ this to the compiler and yourself is to use `default`. That's the point of soundness and exhaustiveness: to point out mistakes in our code. A switch expression needs to evaluate to _something_, so an error when it's non-exhaustive makes sense (otherwise, you'd have a non-nullable function return nothing). For a switch statement, we generally expect our cases to be exhaustive based on what we're switching on, so a warning when a switch is non-exhaustive over a sealed type makes sense. Remember, you can always ignore errors with an `// ignore:` comment.

**Comment by Jetz72** [comment] 2022-09-12 19:33
I was using integers as an example of an unsealed set of values that can be logically narrowed down based on the surrounding code or context known to the programmer, but it can be done with any kind of value. 

> The point of the example is to show that the only way to _prove_ this to the compiler and yourself is to use `default`. That's the point of soundness and exhaustiveness: to point out mistakes in our code. A switch expression needs to evaluate to _something_, so an error when it's non-exhaustive makes sense (otherwise, you'd have a non-nullable function return nothing).

But when the `default` case is something you're confident cannot happen for one reason or another, and exhaustiveness is required as is being proposed for switch expressions, you still have to come up with _something_ for the expression to resolve to. Throw an exception? Pick one of the other cases to be the default value and swallow the discrepancy? Yield `null` and then follow the switch expression with a `!` nonnull assert? Throwing an exception that includes unexpected value is probably the safest choice but it's kinda wordy when a switch expression is meant to be part of a larger statement.

What I'm suggesting is, much as the postfix `!` is a quick way of telling the compiler "I guarantee the preceding value is not null and may my program crash and burst into flames if I am wrong", it'd be nice for a quick way of saying "I guarantee that the cases here are exhaustive so if any other value appears then something is already wrong, just go ahead and explode."

**Comment by lrhn** [comment] 2022-09-12 21:01
The suggestion, as I understand it, is to allow something like `switch!(expression) { case e1: ...; case en: ...}` to mean, implicitly, `switch(expression) { case e1: ..., case en: ..., case var v: throw SomeError(v, "Not exhaustive"); }`

It just a shorthand which adds an implicit default case which throws. That sounds reasonable, like `e!` is a shorthand for `e ?? (throw...)`.

**Comment by leafpetersen** [comment] 2022-09-14 05:35
> Integers can be considered "exhausted" if we use relational patterns, like:

@lrhn assuming, of course, that the scrutinee here has static type `int`?  Otherwise, of course, this is not exhaustive.

**Comment by leafpetersen** [comment] 2022-09-14 05:39
> * It is a compile-time _warning_ for a switch _statement_ to not be exhaustive _when the static type of the matched value is a "sealed type"._

We keep talking about getting out of the business of specifying warnings, and we keep not walking the walk.  I wonder whether we should either be silent here, or specify an error?  If we go forward with what we've discussed in the past of moving all warnings to "tool discretion", this (and the enum warning) would go away from the spec.  Is that what we want?   If not, we should make it an error.

**Comment by lrhn** [comment] 2022-09-14 07:13
I'm fine with making non-exhaustiveness not an error/warning. Then we will add "non-exhaustive-switch" as a lint in our recommended set, but then you can use all the existing means of silencing a lint if you think you don't need exhaustiveness.
And we can also allow the lint to recognize other kinds of sealed or enum-like data, maybe ones annotated with an `@enumlike` annotation. Rather than us having to predict what people do.

That doesn't remove the notion of exhaustiveness from the language, because it still affects flow control, and therefore promotion.
If your switch assigns to `x` on every branch, whether `x` is definitely assigned afterwards depends on whether the switch is exhaustive. Same for promoting on every branch. It's important to the language whether there is another way past the switch statement or not. 
Whether you get exhaustiveness or not just won't be a source of language errors.

The `switch! (expression)` would be a way to ensure exhaustiveness, even when the compiler cannot see it, by adding a throwing default case.

**Comment by munificent** [comment] 2022-09-14 21:03
> We keep talking about getting out of the business of specifying warnings, and we keep not walking the walk.

Haha, fair.

> I wonder whether we should either be silent here, or specify an error? If we go forward with what we've discussed in the past of moving all warnings to "tool discretion", this (and the enum warning) would go away from the spec. Is that what we want? If not, we should make it an error.

I think for sealed families, I would not want the error/warning to be removed from the spec. The whole point of adding sealed types to the language is to cause this error/warning to appear. So that suggests that this should be an error, even for switch statements where not being exhaustive is not actually a soundness problem.

What about enum types? It would technically be a breaking change to make that warning into an error. But it feels pointlessly inconsistent to say that non-exhaustive switches on sealed types are errors but warnings on enums. Should we try to make this breaking change and treat these as errors too?

**Comment by leafpetersen** [comment] 2022-09-14 21:12
I'm not keen on having this just be an opt-in lint.  As @munificent says, this is a huge part of the value proposition in sealed families.  You get reliable feedback from the compiler when you miss a case, or when you're refactoring by adding members of the family.  

We've discussed moving to a model where we had:
  - Specified errors
  - On by default ignorable warnings (in both front ends)
  - Off by default lints (in the analyzer)

In that world, I'd be fine with this being in the second category.  Choosing between the first and the third, I'd definitely go for the first.

In the short term, we could consider making the breaking change to enums, and have this be an error.  Or, we could just specify it as a specified warning for now, with the understanding that all warnings will move to the second category at some point.

**Comment by Levi-Lesches** [comment] 2022-09-14 21:48
Just curious, what's 

> We've discussed moving to a model where we had:
> 
> * Specified errors
> * On by default ignorable warnings (in both front ends)
> * Off by default lints (in the analyzer)

Just curious, what's the difference between this and what Dart has now? For example, this produces no warnings: 
```dart
int temp = 5;
print(temp ?? 0);  // ignore: dead_null_aware_expression
```

I guess the only difference is that 
```dart
int temp = null;  // ignore: invalid_assignment
```
ignores the error when maybe it shouldn't be able to. Is that all?

**Comment by leafpetersen** [comment] 2022-09-14 21:54
> Just curious, what's the difference between this and what Dart has now?

Mostly organizational.  Currently, we put warnings in the spec (which are always turned on, and implemented in the compilers + analyer) and then the analyzer adds on some opt out diagnostics (hints), and opt in diagnostics (lints). This is a bit of a confusing state, so we'd like to get to a world where the two front ends agree on the opt-in ignorable behavior, and we can make warnings/hints be tooling things rather than language specification things.

**Comment by lrhn** [comment] 2022-09-15 12:38
I'm not a fan of language mandated warnings. They risk being too narrow. If the analyzer can give *better* warnings (perhaps even detect false positives and avoid warnings), the user is better off without the language specification mandating a specific worse result. 
We also cannot expect the language specification to ever have the same sophistication and domain knowledge (and understanding of annotations) that the analyzer has, so the specification should not try to understand user *intent*.

Make it an error, because it's just considered *bad*, or get out of the way and let other, smarter tools guide the user.

If we make non-exhaustiveness of sealed types an error, then it's probably not a problem for users. If they get the error, they can always add a `default:` case (switch expressions must all be exhaustive anyway, so it's only for statements).

It does make it a breaking change to add something that will break exhaustiveness. That's a double-edged sword.
It means that if you *do* make such a breaking change, everybody switching on your "thing" will be forced to account for the new addition/removal. It also makes it prohibitively expensive to make such a change.
There will be cases where you don't want to use an `enum`, because adding to it in the future will be breaking, so you will roll your own enum-like class instead. If you realize too late, you have to migrate your class away from being an `enum`.
Is that a problem?

Concretely, we are currently migrating the `TargetType` enum to not be an enum, precisely because it's expected to grow in the future. We do not want it to be a breaking change to add more target types. That also means that, because it won't be an enum, you won't get a warning if a switch is non-exhaustive. We can add new values in the future, and users won't even get a warning.
(Should we then introduce an annotation, like `@enumlike`, which provides a *warning* if a switch isn't exhaustive? One which can be silenced, or addressed, but won't break you. Or maybe you could annotate the `switch` instead, to ask for exhaustiveness checking for a non-`enum` type.)


If we do make errors, we then just have to decide which potentially exhaustible types we want to make it an error for.
It depends only on the static type of the scrutinee. If I switch on `dynamic` and all the cases happen to be enum values of the same type, it might be a lint opportunity, but the language won't care.

The possible exhaustive switch types would b:
* An enum type? Probably should be exhaustive.
* A sealed type hierarchy root type? Probably should be exhaustive (it was declared to be usable for exhaustiveness checking).
* `bool`: I'd say no. Because I'd say no to `bool?` too.
* Integers with `<` ranges? Probably not.
* `T?` where `T` is exhaustible? Do what you do for `T` itself.
* `(T1,..,Tn)` where all the `T`s are exhaustible. Yes only if yes for all `T`s.

You should not be doing a statement switch on booleans. Even less an inexhaustive switch. That's like `switch (b) { case true: .... }`. Being non-exhaustive is not the biggest problem here.

Integers can be made exhaustive, but they are not designed for it. Being non-exhaustive is not inherently weird.


I still think I'd prefer no warnings or errors in the language, and letting the analyzer do its darned best to help users based on all available information, not just what the language specification knows about.

**Comment by leafpetersen** [comment] 2022-09-16 00:07
> You should not be doing a statement switch on booleans. Even less an inexhaustive switch. That's like `switch (b) { case true: .... }`. Being non-exhaustive is not the biggest problem here.

I very much disagree with this.  Including booleans in patterns is quite common, though usually as a subcomponent.  of other patterns.  Examples include when you have a bunch of booleans, and you want to cleanly dispatch on different combinations (it's vastly more readable to just write a switch rather than complicated boolean logic in conditionals), or just as subcomponents of a general pattern match.

**Comment by lrhn** [comment] 2022-09-16 11:12
ACK. Booleans as sub-components makes much more sense. At top-level it's stupid, but then it doesn't really matter what we do there, because you shouldn't be doing the switch anyway. (If it's `bool?`, then needing to be being exhaustive is probably fine.)

**Comment by lrhn** [comment] 2022-09-19 09:13
The `jsontool` package is a third-party package, not a Dart team supported one. 
Would you be willing to fork or vendor it?

**Comment by munificent** [comment] 2022-09-20 00:36
Re-opening because I want to refine this a little more:

I specified an answer to this issue in https://github.com/dart-lang/language/pull/2493. It says, roughly, that nonexhaustive switch statements are a warning when the matched type is an enum type, an error if it's an exhaustive type, and nothing otherwise.

An interesting wrinkle is how exhaustiveness is determined for record types. If all of the fields of a record type are sealed types, (or records containing sealed types), the record type should itself be exhaustive.

What if a record type has fields that are all enum types? Is a non-exhaustive switch on that record type a warning or an error? Right now, the proposal says it's a warning.

The logic is basically: All non-exhaustive switches on types that users expect to be exhaustive are errors, *except* that entirely for backwards compatibility, we make it a warning if the matched type is an enum type or nullable enum type.

* Sealed type: Error.
* Nullable sealed type: Error.
* Record containing sealed types: Error.
* Record containing sealed and types: Error.
* Record containing *only* enum types? Error.

*(insert "straight to jail" meme here)*

I think this is *feasible*, but it doesn't feel elegant.

What are the chances that we can just take the breaking change and make it an error to have a non-exhaustive switch statement on an enum type (or nullable enum type)? Mitigating factors:

* Many users already treat warnings as errors, so will have already fixed any non-exhaustive switches on enum types.

* Flow analysis depends on whether a switch is exhaustive, so if the switch appears in, say, a function with a non-void return type and each case is a `return`, it would already be an error to not have the switch be exhaustive.

Thoughts, @mit-mit or other language folks?

**Comment by mit-mit** [comment] 2022-09-20 06:57
Could such a potential breaking change be language versioned, so that only those on 3.0 language version or later would hit it?

**Comment by munificent** [comment] 2022-09-20 19:04
SGTM, I'll update the proposal.

**Closed** 2022-09-21 14:27 UTC
Labels: patterns

**Comment by Sameer-Ijaz** [comment] 2024-11-24 16:39
I was getting the error for expo apple authentication and fixed it by doing this https://www.youtube.com/watch?v=ya3kyKU-HY8&ab_channel=SgtSam
