### ISSUE TITLE
Add if not null operator: !? 

### ISSUE THREAD

**Issue by mathieudevos** [dart-lang/language#706] opened 2019-11-25 18:08 UTC
Simple suggestion, allow the negation of the if null operator: `??` with the following: `!?`.

This prevents you from running functions that cannot handle null input.

Example:

```
double foobar(double input) {
  return input / 2;
}

void printIt(dynamic input) {
  print(input.toString());
}

void main() {
  final foo = null;

  // Suggested method
  printIt(foo !? foobar(foo));

  // Current method
  printIt((foo == null) ? null : foobar(foo));
}
```

The current style just has a weird way of writing with the null repetition. 
Alternatively we could allow the unary prefix to apply: `!foo ?? foobar(foo)` would also be acceptable.

**Comment by natebosch** [comment] 2019-11-25 21:55
You might want to add a comment on https://github.com/dart-lang/language/issues/361 which proposes something similar but uses `!!` instead of `!?`

**Comment by lrhn** [comment] 2019-11-26 08:31
Agree, this is a duplicate of #361.

**Closed by lrhn** 2019-11-26 08:31 UTC
Labels: feature
