### ISSUE TITLE
Unexpected parse of semicolon terminated switch expression

### ISSUE THREAD

**Issue by TimWhiting** [dart-lang/language#3066] opened 2023-05-11 15:11 UTC
I don't know if this is expected behavior but a semicolon terminated switch isn't considered a switch expression by the tooling (it is considered a switch statement, and gives an error that it expects to find the keyword case). 

Example:
```dart
switch (this) {
      ILit() => print("Literal"),
    };
```

It probably just assumes that the ending semicolon is a separate statement which seems to be confirmed by the formatter.

This makes it somewhat difficult to start working on a switch expression since often when starting the body of a function I'd like to switch on something, but don't want to come up with a name for the thing to assign the result to, and am not immediately returning it. It also came up in the case where I wanted to use a switch to print out the result of a program, (where the return type is void, and shouldn't be assigned to a variable) - as in the above example.

I think a better way to parse this would to be to parse both switch expressions and switch statements the same, but consider it a switch expression if any of the cases don't begin with case. If a majority have the keyword case or if none of the cases have a => then report the missing keyword case error.

**Comment by lrhn** [comment] 2023-05-11 20:08
It's expected and deliberate behavior.

It's not the semicolon which determines it. An expression statement cannot start with `switch`, just like it cannot start with the `{` of a map literal. 

Not a big restriction, you can just use a switch statement, since the value isn't being used for anything.
Or parenthesize it: `(switch (this) { ILit() => print("Literal")};` is valid.

**Comment by munificent** [comment] 2023-05-11 22:56
Yeah, as Lasse says, this is working as intended. I'm going to close this out but it's worth paying attention since this has already come up twice in the past day or two as a point of confusion for users.

**Closed by munificent** 2023-05-11 22:56 UTC
Labels: request

**Comment by leafpetersen** [comment] 2023-05-12 13:41
cc @stereotype441 @johnniwinther I wonder if we can make the error message more helpful here?

**Comment by stereotype441** [comment] 2023-05-15 18:12
> cc @stereotype441 @johnniwinther I wonder if we can make the error message more helpful here?

Good idea. I filed an issue to track: https://github.com/dart-lang/sdk/issues/52404
