### ISSUE TITLE
Pattern matching

### ISSUE THREAD

**Issue by black-redoc** [dart-lang/language#1747] opened 2021-07-16 20:49 UTC
Sometimes I need to pipe some program flow but in actually I can use two alternatives, if-else and switch case. But there two are extensive and imperative. because to use else or elsif to matching some event or use a break to the end of each switch case, this becomes boilerplate and expensive for something short like this:

```
match (event) {
  is Event.Success => Navigator.of(context).pushNamed("/");
  is Event.Error => Navigator.of(context).pop();
}
```

```
final result = match (request.status) {
  Status(400) => AlertDialog(content: Text("Error"));
  Status(200) => AlertDialog(content: Text("OK"));
}
```

**Comment by Levi-Lesches** [comment] 2021-07-18 06:32
Duplicate of #1047, #546, and the langauge proposal docs [here](https://github.com/dart-lang/language/blob/master/working/0546-patterns/goals-and-constraints.md) and [here](https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md). 

It seems a _lot_ of people want this

**Closed** 2021-07-26 18:06 UTC
Labels: feature, state-duplicate
