### ISSUE TITLE
Destructuring records in functions

### ISSUE THREAD

**Issue by Nikoro** [dart-lang/language#3640] opened 2024-03-05 22:07 UTC
Let's say I've got a list of records:

```dart
 final List<(int, int)> records = List.generate(10, (index) => (index, index));
```
and want to apply a map function on that list:

```dart
records.map((record) {
      final (a, b) = record; // I have to write this line to destructure a record
      return '$a$b';
    });
```

It would be nicer if destructuring could be done directly in function parameter:

```dart
records.map((a, b) => '$a$b');
```

**Comment by lrhn** [comment] 2024-03-06 11:43
Most likely the syntax will have to be
`((a, b)) ...`, because there is a fundamental difference between a two parameter function, `Function(int a, int b)`, which `(a,b)=>…` already means, and a single-record parameter `Function((int, int) pair)`.

It should, hopefully one day, be possible to call the former using a record with a parameter spread, `foo(... pair)`.

**Comment by mateusfccp** [comment] 2024-03-06 13:06
Seems like a duplicate of #3001.

**Comment by Nikoro** [comment] 2024-03-07 21:58
> Most likely the syntax will have to be `((a, b)) ...`, because there is a fundamental difference between a two parameter function, `Function(int a, int b)`, which `(a,b)=>…` already means, and a single-record parameter `Function((int, int) pair)`.
> 
> It should, hopefully one day, be possible to call the former using a record with a parameter spread, `foo(... pair)`.

Got it!

How about simply double parentheses when parameter is a record? Is this spread operator needed?

I mean something like this then:
Two parameter function:
`Function(int a, int b)`, which `(a,b)=>…`

Single parameter record function:
`Function((int, int) pair)`, then `((a,b))=>…`

Two parameter which one is record:
`Function(int a, (int, int) pair)`, which `(a, (b,c))=>…`

**Comment by lrhn** [comment] 2024-03-08 08:44
Yes, this is indeed a duplicate of #3001, so closing and deferring there.

**Closed by lrhn** 2024-03-08 08:44 UTC
Labels: feature
