### ISSUE TITLE
Optional way of declaring final variables with "val" keyword

### ISSUE THREAD

**Issue by MuhammadFahidSarker** [dart-lang/language#3006] opened 2023-04-18 14:50 UTC
I really appreciate the consistency and readability that the Kotlin language provides with its use of "val" and "var" for declaring immutable and mutable variables, respectively. However, in Dart, the equivalent to a final variable is declared using the "final" keyword, which can make code less consistent and harder to read.

Hence, An optional way of declaring a final variable with the "val" keyword in Dart would be great. This would provide a more consistent syntax and increase the readability of the code.

Here is an example of what this could look like:

```kotlin
val foo = "Foo"; // Immutable variable
var bar = "Mutable Bar"; // Mutable variable
```
Comparing that to what we currently have in dart:
```kotlin
final foo = "Foo"; // Immutable variable
var bar = "Mutable Bar"; // Mutable variable
```
I believe everyone would agree the kotlin version looks more consistent and readable.

This syntax can be optional and can be used interchangeably with the current syntax using the "final" keyword, so as not to break any existing code.

Not sure if this is too good to be true :-)

**Comment by julemand101** [comment] 2023-04-18 15:33
> I believe everyone would agree the kotlin version looks more consistent and readable.

I disagree. I find the code less readable since `val` and `var` are spelled very similar, and starts with the same two letters, so I need to look closer at my screen to easily tell the difference.

It would also become rather irritating if both `val` and `final` are allowed since it then really becomes a pain to read the code since you can no longer just trust the length of the keyword when reading Dart code.

**Comment by Wdestroier** [comment] 2023-04-18 15:50
Duplicated #136

**Comment by mateusfccp** [comment] 2023-04-19 00:43
> Duplicated #136

Not really a duplicate, although related.

**Comment by munificent** [comment] 2023-04-26 23:46
I'm going to go ahead and close this as a dupe of #136. This issue may prefer a specific three-letter solution, but the underlying problem is the same as I see it: `final` is too long.

**Closed by munificent** 2023-04-26 23:46 UTC
Labels: feature
