### ISSUE TITLE
Tree-shaking not producing the same result depending on whether Dart code is compiled as Javascript or Android binary

### ISSUE THREAD

**Issue by andynewman10** [dart-lang/language#4100] opened 2024-09-22 15:58 UTC
Create a Flutter application containing the following code:

```
import 'dart:math';

void log(String s) {
  // This line is basically 'if (!kReleaseMode)', but is compatible with plain-Dart (not Flutter) compilation
  if (!(const bool.fromEnvironment('dart.vm.product'))) {
    print(s);
  }
}

final val = Random().nextInt(1000).toString();
log("Testlog: $val"); // only tree-shaken when building for web (Flutter or plain Dart)
log("Testsimplelog"); // tree-shaken in all cases (web or Android)
```

Now build with

- `flutter build web`. Open the generated `main.dart.js` file with an hexadecimal editor, look for 'Testlog': you won't find the string, meaning its construction has been tree-shaken away. Of course, the call to nextInt() does take place, and is not tree-shaken away (as expected). Note that `dart compile js ... -O[1-4]` also correctly tree-shakes the string generation code.

- `flutter build appbundle --obfuscate`. Open `libapp.so` (from the, eg., armeabi-v7a platform under base\lib) and do the same: you will find the string, this time. It is created by the compiler, and is not tree-shaken away.

Tree-shaking is less powerful with the Android compiler - is that expected, or is this a bug?

Note that, in both cases this time, "Testsimplelog" is correctly tree-shaken away.

Using Flutter 3.22.3 (Dart 3.4.4), on Windows.

EDIT: same result with Flutter 3.24.3 (Dart 3.5.3)

**Comment by julemand101** [comment] 2024-09-23 05:11
This sounds more like an issue for: https://github.com/dart-lang/sdk/issues

The current issue tracker are for issues and suggestions related to the Dart language specification where the other are for the implementation of Dart.

**Comment by mraleph** [comment] 2024-09-23 07:17
Duplicate of https://github.com/dart-lang/sdk/issues/56766

**Closed by mraleph** 2024-09-23 07:17 UTC
Labels: request
