### ISSUE TITLE
Dart Analysis cannot detect nullable type in where method

### ISSUE THREAD

**Issue by nguyenxndaidev** [dart-lang/language#1391] opened 2020-12-31 14:20 UTC
The code below warns incorrectly: `info: The operand can't be null, so the condition is always true. (unnecessary_null_comparison at ...)`

and then error when compile: `Error: The argument type 'Stream<List<Event>?>' can't be assigned to the parameter type 'Stream<List<Event>>?' because 'List<Event>?' is nullable and 'List<Event>' isn't.`

![image](https://user-images.githubusercontent.com/24372782/103414095-bc2c9b80-4b7c-11eb-9bb2-35ff5707a0bf.png)

```
class EventsLoadedState  {
  const EventsLoadedState({required this.events});
  final List<Event> events;
}
```

**Comment by nguyenxndaidev** [comment] 2020-12-31 14:37
The Bloc library doesn't support null-safety. If I change the bloc by a dummy stream, it works again.

But I think the logic here is independent from the library and therefore it's still the bug of dart. Am I wrong?

**Comment by leafpetersen** [comment] 2021-01-05 02:33
Sorry, I'll need a bit more context for the code to diagnose this.  What is the type of `_eventsBloc`?  And does the fragment of code you list appear as a statement, or is it assigned to a variable/passed as an argument?  And if the latter, what is the type of the location to which it is assigned?

**Comment by nguyenxndaidev** [comment] 2021-01-05 09:29
Sorry, it's look like this: `class EventsBloc extends Bloc<EventsAction, EventsState> {}`
`Bloc` from `bloc: ^6.0.0`

**Comment by munificent** [comment] 2021-01-12 00:25
The `where()` method always returns a new Iterable of the same type as the original Iterable you called it on, so if you use `where((e) => e != null)` on an Iterable of a nullable type, you'll still get an Iterable of a nullable type back. It just won't actually contain any null elements.

If you want to filter and change the type, you can use `whereType()`:

```dart
eventsBloc.map((state) {
  if (state is EventsLoadedState) {
    return state.events;
  }

  return null;
}).whereType<List<Event>>()
```

That will also filter out the nulls (since `null` is not a `List<Event>`) and correctly give you a `Iterable<List<Event>>` in return. Having to state the element type is a little verbose, though. Another option would be to define an extension method like:

```dart
extension NullableIterableExtensions<T> on Iterable<T?> {
  Iterable<T> whereNotNull() => whereType<T>();
}
```

Then you could do:

```dart
eventsBloc.map((state) {
  if (state is EventsLoadedState) {
    return state.events;
  }

  return null;
}).whereNotNull()
```

Another option for this specific case is to use `expand()`:

```dart
eventsBloc.expand((state) {
  if (state is EventsLoadedState) return [state.events];
  return const [];
})
```

Closing this because the analysis is working as intended. The `where()` method's return type is baked into the core library, so even when the analyzer knows that there is a more precise element type, there isn't anything it can do.

**Closed by munificent** 2021-01-12 00:25 UTC
Labels: bug
