### ISSUE TITLE
Why dart-lang mark checked final parameter as nullable?

### ISSUE THREAD

**Issue by MohammedAsaadAsaad** [dart-lang/language#2834] opened 2023-02-09 13:36 UTC
Look the following part of code:

```dart
class SomeClass {
  final int? value;

  SomeClass(this.value);

  void printHalfValue() {
    if (value != null) {
      print(value / 2);
    }
  }
}
```
The following line is marked as not safe:
`      print(value / 2);
`
while it contained in if(not null) scope, and value is final parameter:

   ```dart
 if (value != null) {
      print(value / 2);
    }
```

And I get an error:

> The operator '/' can't be unconditionally invoked because the receiver can be 'null'.
> Try adding a null check to the target ('!').dart[unchecked_use_of_nullable_value](https://dart.dev/diagnostics/unchecked_use_of_nullable_value)
> 

Do I miss some thing?

**Comment by eernstg** [comment] 2023-02-09 13:59
Yes, support for promotion of instance variables is discussed [here](https://github.com/dart-lang/language/issues?q=is%3Aopen+is%3Aissue+label%3Afield-promotion).

The fundamental reason why promotion of instance variables is not sound is that any instance variable (final or not, late or not) introduces a getter which can be overridden, and there is no reason to believe that this getter will return the same result if you call it multiple times.

```dart
class A {
  final int? i;
  A(this.i);
}

class B implements A {
  bool useNull = true;
  int? get i => (useNull = !useNull) ? null : 0;
}

void main() {
  var a = B();
  if (a.i != null) print(a.i); // 'null'.
}
```

**Comment by eernstg** [comment] 2023-02-09 14:03
I'll close this issue because it's all working as intended. We do have an ongoing effort to introduce support for promotion of instance variables (or getters) in certain situations. See https://dart-review.googlesource.com/c/sdk/+/262865 for the situation where the instance variable is private. See https://github.com/dart-lang/language/issues/1518 for a proposal that enables promotion of getters in a more general manner.

**Closed by eernstg** 2023-02-09 14:03 UTC
