### ISSUE TITLE
Is `mixin` for non-supermixins a good idea?

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/language#33] opened 2018-09-28 00:37 UTC
I'm filing this issue as a place to discuss whether using the new `mixin` syntax for non-supermixins is a good idea. I do not wish to pollute issue https://github.com/dart-lang/language/issues/32 with this discussion, as I'd like that issue to be focused on the semantics of `extends` w.r.t. `mixin`.

The arguments presented so far:

@Hixie (https://github.com/dart-lang/language/issues/32#issuecomment-425282286):

> Personally I have no objection to being able to use "with" with a true class. I would not want a lint that discourages such use.
> I don't see much value in the "mixin" keyword. I'm ok with having it if it makes the language easier to process in the context of supermixins. I would not encourage people to move to that keyword except where required by the supermixin restrictions.
> In particular, I would not change WidgetsBindingObserver to use the "mixin" keyword.

@yjbanov:

`mixin` comes certain restrictions on what you can do with the class, such as:

- mixins cannot extend other classes
- mixins cannot have constructors and factories
- mixins cannot be instantiated directly

These properties protect mixin authors from accidentally breaking their users. I believe this is an important property for keeping the Flutter/Dart ecosystem healthy. Mixin usage is much higher than mixin authorship and therefore the cost of using `mixin` vs `class` is dwarfed by the stability guaratees the `mixin` semantics provide.

Some examples in Flutter that may be used as super-classes or as mixins:

- [LocalHistoryRoute](https://docs.flutter.io/flutter/widgets/LocalHistoryRoute-class.html)
- [WidgetsBindingObserver](https://docs.flutter.io/flutter/widgets/WidgetsBindingObserver-class.html)

Updates to the original issue description:

- Added examples from Flutter

**Comment by yjbanov** [comment] 2018-09-28 00:52
More arguments can be found in https://github.com/flutter/flutter/pull/22290. For example:

> > My worry is that in the future we may accidentally break the API by adding a seemingly innocent super call or attempt to extend another class.
> 
> The solution to that is to add tests. I would certainly support adding more tests to make sure we don't break that particular pattern.

> > The solution to that is to add tests.
> 
> This solution works for highly disciplined engineering teams. But I don't think it works for the ecosystem as a whole, where you will have users of varying levels of expertise. Using classes as mixins is known to be quirky. If there is a better way, I say we should accept it. I think [dart-lang/language#31 (comment)](https://github.com/dart-lang/language/issues/31#issuecomment-425158760) is a better way.

**Comment by lrhn** [comment] 2018-09-28 11:49
The problem with *allowing* any (no-constructor, `Object`-superclass) class to be used as a mixin is that it makes more changes into breaking changes for that class.

Adding tests *cannot* catch this. 

If someone else, in a package you never heard of, is using your class as a mixin (maybe even on a const class), then you break their code if you
* Add a generative constructor (e.g., by changing a factory constructor to be generative).
* Add a super-class.
* Add a first field (if used on const class, and someone uses the result as const)

These are not changes that would *normally* count as breaking, so most likely you won't do a major-version increment when you refactored the class to share some functionality with another class through a private super-class - but if they update their dependencies, their code stops working.

So, any API containing any class that can be used as a mixin, *should* do a major-version increment whenever they change such a class so it can no longer be used as a mixin.
Obviously nobody wants to do that, which is why there is this request to ensure that a non-mixin class cannot be used as a mixin.

**Comment by eernstg** [comment] 2018-09-28 12:44
Why don't we simply answer "**Yes**, it is indeed a good idea to use `mixin` for a declaration _M_ that is intended to be used as a mixin, even in the case where no method implementation in its body performs any superinvocations!"

The point is that this is a contract that involves the author(s) of _M_ and the clients of _M_, and the software artifacts containing _M_ are simply going to be more maintainable when such a tightly coupled piece of reusable code as a mixin is marked explicitly as such.

Do we need a 'resolution-yes' label? ;-)

**Comment by Hixie** [comment] 2018-09-28 19:07
I don't see why mixins are special here. Any class can be used as an interface too, with the same problems.

**Comment by munificent** [comment] 2018-09-28 19:57
> Any class can be used as an interface too, with the same problems.

That's one of the reasons we're looking into sealed classes and the ability to express a class that cannot be implemented. The language already supports this for a hand-picked set of magic classes — bool, double, num, int, and String. If it's useful for those types, it's likely useful for user types.

**Comment by Hixie** [comment] 2018-09-28 20:46
Sure, but most classes can't be sealed since they're intended to be subclassed, and almost all classes need to be implementable for mocking purposes.

**Comment by munificent** [comment] 2018-09-28 23:17
> Sure, but most classes can't be sealed since they're intended to be subclassed, and almost all classes need to be implementable for mocking purposes.

As far as I know, we don't actually have any real empirical data to justify a claim like that.

**Comment by yjbanov** [comment] 2018-10-02 20:08
> Adding tests cannot catch this.

More than that. In practice, few developers write tests.

> I don't see why mixins are special here. Any class can be used as an interface too, with the same problems.

One special thing about mixins is that we are trying to fix them now. We are currently not trying to fix interfaces, which, I agree, also have problems. I guess I don't understand what conclusion this argument is trying to reach.

I'm also not sure if the problem are the same. For example, if a class is also used as an interface, then adding a `factory` or a generative constructor, extending another class, and adding `super` calls are rarely breaking changes. OTOH, these changes are _guaranteed_ breaking changes in the case when a class is also used as a mixin.

Classes-used-as-interfaces do have issues though, and I think they should be addressed at some point. Some background is documented [here](https://github.com/dart-lang/language/blob/master/resources/class-capabilities/class-capabilities.md).

> most classes can't be sealed since they're intended to be subclassed, and almost all classes need to be implementable for mocking purposes.

Perhaps, but also most classes do not need to be fast. In practice, only a small portion of code is on the hot performance path, and that's where you will see benefits from things like `sealed`, static dispatch, memory-locality, etc. For example, Dart draws a lot of performance benefits from keeping `int`, `double`, `String` and `bool` sealed. What's changed recently is our realization that this could have impact beyond built-in classes. C++ is not fast because every single line of code your write is fast, but because it gives you the tools to make the 5% of code that _does need_ to be fast fast.

Not that this particular issue has to do with performance. I'm just doubting the logic in the claim that a feature should be rejected because of low usage count. I think a feature's inclusion should be evaluated according to its overall impact.

**Comment by mit-mit** [comment] 2018-10-17 15:11
@yjbanov @lrhn did we reach a conclusion here? Can we close this issue?

**Comment by yjbanov** [comment] 2018-10-17 17:11
AFAICT, no conclusion has been reached yet.

**Comment by lrhn** [comment] 2018-10-19 09:13
My opinion is definitely that, yes, it is a good idea to use `mixin` for all mixins.

I'm not sure what it would take to close this issue, though.

**Comment by munificent** [comment] 2018-10-19 17:59
> My opinion is definitely that, yes, it is a good idea to use `mixin` for all mixins.

Me too. But, either way, I think this is a question about best practices and not something actionable in the language repo. Maybe it would be worth [filing a bug](https://github.com/dart-lang/site-www/issues) for what "Effective Dart" should say here, but that's a separate repo.

**Comment by yjbanov** [comment] 2018-10-20 06:55
The goal of the issue is to get a recommendation from the language team so we could follow it in Flutter and steer our users towards it via [analysis_options_user.yaml](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/analysis_options_user.yaml).

If the recommendation is to use `mixin` for all mixins, then we're back to issue #32, which prevents us from being able to follow the recommendation.

**Comment by rodion-m** [comment] 2021-07-16 16:33
And what is the solution? effective_dart abuses about using WidgetsBindingObserver as a mixin, but it's a code from the example: https://api.flutter.dev/flutter/widgets/EditableTextState-class.html

**Comment by lrhn** [comment] 2021-07-26 08:09
My strong recommendation is to *never* use a class as a mixin and *never* design a class as intended to be used as a mixin.
My long time goal is to remove the ability to use classes as mixins. It's not necessary now, except for backwards compatibility. 

If you change all current classes used as mixins to be declared as mixins, and change all uses of those classes as superclasses from `extends TheClass` to `with TheClass`, then everything should keep working, and we could remove the ability to use classes as mixins tomorrow (and I would do that!)
 The only thing holding us back is that we need to change all the existing `extends ClassAlsoUsedAsMixin` to `with ClassAlsoUsedAsMixin` before being able to change its declaration to `mixin ClassAlsoUsedAsMixin { ... }`. That's a migration step with no obvious enforcement. Changing `class` to `mixin` first breaks the existing code (easy to fix, but still broken). Changing `extends` to `with` is hard to automate because there is no obvious hint on the class declaration that it's intended to be used as a mixin. It looks like a perfectly normal class and your code is just extending it. You have to be able to see another instance of `with TheSameClass` to be able to decide that the `extends` should also be `with`.

We could introduce an intermediate `@asMixin` annotation that can be put on the `class TheClass` declarations, then we can automate the migration of all instances of `extends TheClass` to `with TheClass`, and finally we can remove the annotation again.
Or we can do as I propose in #1643 and use language versioning.

**Comment by Levi-Lesches** [comment] 2021-10-15 01:24
So it seems like `ChangeNotifier` (and I assume other similar classes) is used in one of two ways: 
- by Flutter to make a more refined type of listening (`class ValueNotifier extends ChangeNotifier`)
- to users to connect the backend logic to the frontend (`class MyModel with ChangeNotifier`)

These two seem similar enough to merge into one. `ValueNotifier` can be seen as "a class that includes the ability to notify others when its value changes" instead of "a more specific type of the class `ChangeNotifier`". Does something else go wrong with changing the Flutter classes to use `with` instead of `extends`?

**Comment by Hixie** [comment] 2021-10-15 02:02
The vast majority of uses of ChangeNotifier that I'm aware of are just using it as a superclass with `extends`. They have an "is-a" relationship with that class. They "are" change notifiers. Dart, unlike other languages, is powerful enough that you can _also_ in cases where just inheriting from `ChangeNotifier` doesn't work, mix it in using `with`.

**Comment by leafpetersen** [comment] 2021-10-15 23:43
I think I'm somewhat in agreement with @Hixie here.   Extending is by far the simplest and most familiar way for a user to get access to some shared functionality in an OO language, and if that affordance works for users in the 95% case, then it feels like we should provide the ability for library authors to offer it (e.g. `mixin class`), even if in the 5% case they have to switch to using `with`.  I don't think it's hard for users to get to "normally I'd extend this, but in multiple inheritance cases I can mix it in instead" when they really need to.

**Comment by Hixie** [comment] 2021-10-16 00:27
I'd be fine with the compiler complaining if you tried to mix in a class where there are concrete members in superclasses of the class you're mixing in.

**Comment by Levi-Lesches** [comment] 2021-10-17 04:12
> I think we'd be fighting an uphill battle which would make the language and framework harder to understand if we tried to push people to mix in `ChangeNotifier` instead of extending it.

When using `ChangeNotifier` in my Flutter apps, I always use the following structure: 

```dart
// model.dart
abstract class Model with ChangeNotifier {
  /// Initialize data here.
  Future<void> init();
}

// user.dart
class UserModel extends Model {
  Future<void> init() => loadUserData();

  Future<void> updateUser() async {
    Firestore.updateUser(await loadUserData());  // some update
    notifyListeners();
  }
}
```

I always mix-in `ChangeNotifier` (despite the `prefer_mixins` warning). In my case, I have a hierarchy of my own, so while I do extend the `Model` class, I think of it as "`UserModel` is a `Model` that is able to notify the UI when it changes" (in other words, "_includes_ the ability to..."). Even before I worked out this structure and mixed in `ChangeNotifier` directly, I was still thinking "this is a container class for data that has the ability to notify the UI when it changes". 

So IMO, getting users to think of `ChangeNotifier` as functionality they can "include" in their data models (instead of making their models "become" a `ChangeNotifier`) is pretty intuitive, and my team and I have been going about it that way for a while now.

**Comment by lrhn** [comment] 2024-07-02 11:29
We now have `mixin class` declarations, which can be extended and mixed in (but not declare super-classes, super-interface-constraints, or non-trivial constructors).

**Closed by lrhn** 2024-07-02 11:29 UTC
Labels: question
