### ISSUE TITLE
Shorthand syntax for passing named parameters

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/language#3502] opened 2023-12-08 14:41 UTC
In the situation where (a) the type of an argument does not clarify its use and (b) neither the expression passed in to a function call clarifies its use, a call site can be made more readable by using required named parameters.

```dart
void main() {
  eatBananas(true, false, 123);
}
```

->

```dart
void main() {
  eatBananas(
    peelFirst: true,
    hidePeels: false,
    numberOfBananas: 123,
  );
}
```

However, once using named parameters, there might be other call sites which pass in a variable with exactly the same name as the named parameter resulting in code such as:

```dart
void someFunction() {
  // ...
  eatBananas(
    peelFirst: peelFirst,
    hidePeels: hidePeels,
    numberOfBananas: numberOfBananas,
  );
}
```

As a language feature we could consider omitting the parameter names:

```dart
void someFunction() {
  // ...
  eatBananas(
    : peelFirst,
    : hidePeels,
    : numberOfBananas,
  );
}
```

Or maybe 

```dart
void someFunction() {
  // ...
  eatBananas(
    peelFirst: ,
    hidePeels: ,
    numberOfBananas: ,
  );
}
```

### Alternative: Solve in IDE

Alternatively, we could consider solving this on the IDE level instead of the language level. We could borrow from editors that already aid with show parameter names. In my VSCode C++ editor, the visualization adds `peelFirst=` in front of an argument to a function call _except_ for if the expression passed in is a variable with exactly the same name, and except for if a comment `/*peelFirst=*/` was written. This leads to on the call sites always having at most once the parameter name in the IDE. (In a non-IDE situation E.g. Gerrit/GitHub code review, the visual aid isn't there.)

Example:
<img width="543" alt="image" src="https://github.com/dart-lang/language/assets/3601775/d3026b60-3752-464a-aa01-ef2c7bcbd660">
`name:` is added visualization by the IDE, `script_uri` is the exact parameter name, so the visualization not added, and `/*isolate_data=*/nullptr` already has a comment so it's not in the visualization either.

We already do something with closing brackets in DartCode, so we likely already have infra to tackle something like this. @dantup

**Comment by DanTup** [comment] 2023-12-08 14:47
> We already do something with closing brackets in DartCode, so we likely already have infra to tackle something like this. @DanTup

We have this for parameter names already, but they'll only show while you hold down Ctrl+Alt (they're called "parameter hints" / "inlay hints"). You can change settings to show them always, but it's a bit noisy (we have type hints too, and they're both toggled together in VS Code).

https://github.com/dart-lang/language/assets/1078012/0753987c-6a44-4bfd-811c-7940e5f2fd65

It's always bugged me that using named params requires duplicating the names so much (it's pretty common to be passing some variable and it usually has the same name). TypeScript supports something like this for objects and it's really nice:

```ts
const aaa = '';
const bbb = '';

const ccc = {
  aaa, // same as aaa: aaa
  bbb, // same as bbb: bbb
};
```

**Comment by nex3** [comment] 2024-01-06 01:03
Duplicate of https://github.com/dart-lang/language/issues/3102?

**Comment by lrhn** [comment] 2024-01-08 08:30
Yes, duplicate.

**Closed by lrhn** 2024-01-08 08:30 UTC
