### ISSUE TITLE
Smart cast not smart enough.

### ISSUE THREAD

**Issue by techwnn** [dart-lang/language#3126] opened 2023-06-02 08:16 UTC
When I judge variable not null, Dart allow me use variable as non-nullable:
<img width="400" alt="image" src="https://github.com/dart-lang/language/assets/20474091/32e6503d-9227-4b31-8fc5-d2732ca88406">

But when I wrote like this, Dart not understand that variable is non-nullable now:
<img width="800" alt="image" src="https://github.com/dart-lang/language/assets/20474091/047552e4-1e5b-42f5-865b-0e2100d9c697">

**Comment by srawlins** [comment] 2023-06-05 19:59
Duplicate of https://github.com/dart-lang/language/issues/1224

**Comment by lrhn** [comment] 2023-06-06 09:52
Agree. Closing as duplicate. 
There are many ways to infer that a variable is not `null`, we currently only promote on direct `== null`/`!= null` checks and `is NonNullabelType`. The #1224 issue can stand in for all the ways we can do more.

**Closed by lrhn** 2023-06-06 09:52 UTC
Labels: request
