### ISSUE TITLE
Add struct as a main language feature

### ISSUE THREAD

**Issue by CXCubeHD** [dart-lang/language#2101] opened 2022-02-08 13:03 UTC
Dart should add `struct`s the same way C# did. Structs are in-place, meaning that the place for the members is pre-reserved, like for native types.

Here an example on how the memory structure may look like:

Class
```dart
class MyClass {
    int a;
    MyOtherClass b;
    MyStruct s;
}

struct MyStruct {
    int sA;
    int sB;
}
```
```
--- MyClass begin ---
a: INT (8 bytes)
b: PTR (8 bytes (64 Bit))
c -> All the members from MyStruct (-> 16 bytes)
    sA: INT (8 bytes)
    sB: INT (8 bytes)
--- MyClass end ---
```

Structs are passed by value, meaning they are being copied on each assignment. This can (or cannot) improve performance in certain situations. Also, the GC does not track structs on its own.

Structs should be used on small datatypes like: (fixed) Vectors -> `Vector2` or similar.

This can heavily improve performance in games, as no additional allocations are needed and as no GC tracking is required.

**This feature should be high priority, as Flutter apps and game engines rely on it** (like Flame)**.**

**Comment by mraleph** [comment] 2022-02-08 13:55
This has been discussed for many years now, one of the more recent discussions / approaches are in https://github.com/dart-lang/language/issues/1467

**Comment by munificent** [comment] 2022-02-09 00:15
I'm going to close this as a duplicate of #1467.

**Closed by munificent** 2022-02-09 00:15 UTC
Labels: feature
