### ISSUE TITLE
enums can't have a name, and shouldnt

### ISSUE THREAD

**Issue by synchronisator** [dart-lang/language#2252] opened 2022-05-20 18:39 UTC
If i make an enum like this, everything looks fine

```
enum Player {
  blue("Blue"),
  brown("Brown"),
  red("Red"),
  white("White");

  final String name;
  const Player(this.name);
}
```
But when i build an apk or web app this dartfile is not in the generated bundle.
Sounds like a flutter ticket, but i think its a dart ticket.

Because the error might be, that the field "name" collides with the enum.name
This should be an compile-error.

**Comment by lrhn** [comment] 2022-05-21 22:17
Seems like a duplicate of https://github.com/dart-lang/sdk/issues/49021

It's a bug, the code should work.

**Closed by lrhn** 2022-05-21 22:17 UTC
Labels: request
