### ISSUE TITLE
Ternary conditional operator does not resolve type properly

### ISSUE THREAD

**Issue by yanqui-uxo** [dart-lang/language#2577] opened 2022-10-18 23:41 UTC
This yields the error `A value of type "Object" can't be returned from the function 'func' because it has a return type of 'B'.`. This error does not occur using regular conditional syntax (if/else). I am using Dart 2.18.2, and this can be replicated on DartPad.

```dart
class A {}

class B {}

class C extends A implements B {}

class D extends A implements B {}

B func(bool b) => b ? C() : D();
```

**Comment by srawlins** [comment] 2022-10-18 23:56
Duplicate of https://github.com/dart-lang/language/issues/1904 and https://github.com/dart-lang/language/issues/1877 and similar to https://github.com/dart-lang/language/issues/2216

**Comment by srawlins** [comment] 2022-10-19 00:05
This example is different from others in that it does not even require generics 😢 . The issue here comes from the combination of `extends` and `implements` in C and D. Removing `extends A` in either C or D fixes the issue. Removing `implements B` in either C or D (and changing the `func` return to B) fixes the issue.

**Comment by caseycrogers** [comment] 2023-09-07 17:24
This is also a problem (unsurprisingly) with switch expressions:
`B func(bool b) => switch (b) { true => C(), false => D(), };`

Is there any potential for fixing this? eg bias towards the type declared in the function signature (or variable declaration, if applicable)?

**Comment by munificent** [comment] 2024-01-09 22:03
> This is also a problem (unsurprisingly) with switch expressions: `B func(bool b) => switch (b) { true => C(), false => D(), };`

Yes, definitely. Switch expressions have made least upper bound a bigger pain point than it already was.

> Is there any potential for fixing this? eg bias towards the type declared in the function signature (or variable declaration, if applicable)?

Yes, I think we're leaning towards using the context type as a hint to least upper bound. The tracking issue for that is #1618. I'll close this one in favor of that.

> While this is pretty niche, as far as I can tell there's no way to write this logic in a compile-time safe manner so it seems like a pretty unfortunate limitation.

You can always just upcast. Since it's an upcast, it will never fail. Having to upcast is annoying though, since it's hard to tell if a given cast is casting up (safe) or down (may fail at runtime).

**Closed by munificent** 2024-01-09 22:03 UTC
Labels: least-upper-bound
