### ISSUE TITLE
Records as an argument of lambda expression

### ISSUE THREAD

**Issue by kawa-yo** [dart-lang/language#3134] opened 2023-06-07 04:12 UTC
Hi,
`Record` is very convenient and useful, but I found it a little quirky when used as an argument to a lambda expression.

In the code below, we have tried three different ways of taking the sums in a record using lambda expressions.
`sum0 `is the only method that works, but it would be nice if the records could be passed in pre-parsed values, as in `sum1` and `sum2`.

Is there any prospect of improving this behaviour in the future?

```dart
void main() {
  var list = [for (int i = 0; i < 5; i++) (i, -i)];
  var sum0 = list.map((xy) => xy.$1 + xy.$2);
  var sum1 = list.map((x, y) => x + y);
  var sum2 = list.map(((x, y)) => x + y);
}
```

The error messages in `sum1` and `sum2` are as follows:

`sum1`:
```
The argument type 'InvalidType Function((int, int), dynamic)' can't be assigned to the parameter type 'dynamic Function((int, int))'.dart[argument_type_not_assignable](https://dart.dev/diagnostics/argument_type_not_assignable)
```

`sum2`:
```
The argument type 'InvalidType Function(dynamic Function(dynamic, dynamic))' can't be assigned to the parameter type 'dynamic Function((int, int))'.dart[argument_type_not_assignable](https://dart.dev/diagnostics/argument_type_not_assignable)
Expected an identifier.dart(missing_identifier)
Use the generic function type syntax to declare the parameter ''.
Try using the generic function type syntax.dart[use_function_type_syntax_for_parameters](https://dart-lang.github.io/linter/lints/use_function_type_syntax_for_parameters.html)
```

Thank you for reading to the end!

---
dart version: Dart SDK version: 3.1.0-163.0.dev (dev) (Thu Jun 1 09:55:06 2023 -0700) on "macos_arm64"

**Comment by lrhn** [comment] 2023-06-07 22:50
It's unlikely that `sum1` will work. That syntax already means something else.

Allowing `sum2` to work requires allowing destructuring in parameters, which is something we're considering: https://github.com/dart-lang/language/issues/3001. (Whether it'll require a `(var (x, y))=> ....` is still an open question.)

**Comment by munificent** [comment] 2023-06-08 23:41
Closing this as a dupe of #3001.

**Closed by munificent** 2023-06-08 23:41 UTC
Labels: feature
