### ISSUE TITLE
Static and runtime errors for `main` seem under-specified

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#1120] opened 2020-07-28 22:33 UTC
There seem to be no static errors specified for the signature provided for `main`, and the runtime semantics don't seem to make it clear that as a result the invocation needs to do a dynamic type check.  In practice, the VM at least seems to do so. 
This program:

```dart
void main(int x) {
  x.isEven;
}
```

produces the following runtime error when run:

```
Unhandled exception:
type 'List<String>' is not a subtype of type 'int' of 'x'
#0      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#1      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

This seems like it needs clarification in the spec, and possibly tests.

**Comment by natebosch** [comment] 2020-07-28 22:48
Adding any static error here will be breaking. If we add one it needs to be gated by the language version.

The name `main` is not (currently) reserved for the entrypoint method. You can define `main` in any library and invoke it with any arguments.

 I'm not opposed to it, but we should be aware that we are enforcing a (quite reasonable) _convention_ by adding static checking to the signature of functions named `main`.

**Comment by leafpetersen** [comment] 2020-07-28 23:04
> The name `main` is not (currently) reserved for the entrypoint method. You can define `main` in any library and invoke it with any arguments.

That's not quite true (at least per spec).  The restrictions are small, but as I understand the spec (quoted below):
  - Any symbol named "main" is treated as an entry point
  - It is a compile time error if that symbol is a non-function, and has more than two positional parameters
  - That symbol will be invoked according to a specific procedure.

It's just that the spec above is not restrictive enough to be sound.

```
A script $S$ is executed as follows:

\LMHash{}%
First, $S$ is compiled as a library as specified above.
Then, the top-level function defined by \code{main}
in the exported namespace of $S$ is invoked (\ref{functionInvocation})
as follows:
If \code{main} can be called with with two positional arguments,
it is invoked with the following two actual arguments:
\begin{enumerate}
\item An object whose run-time type implements \code{List<String>}.
\item An object specified when the current isolate $i$ was created,
for example through the invocation of \code{Isolate.spawnUri} that spawned $i$,
or the null object (\ref{null}) if no such object was supplied.
\end{enumerate}
If \code{main} cannot be called with two positional arguments,
but it can be called with one positional argument,
it is invoked with an object whose run-time type implements \code{List<String>}
as the only argument.
If \code{main} cannot be called with one or two positional arguments,
it is invoked with no arguments.

\commentary{
Note that if \code{main} requires more than two positional arguments,
the library is not considered a script.
}

\commentary{
A Dart program will typically be executed by executing a script.
}

\LMHash{}%
It is a compile-time error if a library's export scope contains a declaration
named \code{main}, and the library is not a script.
\commentary{This restriction ensures that all top-level \code{main} declarations
introduce a script main-function, so there cannot be a top-level getter or field
named \code{main}, nor can it be a function that requires more than two
arguments. The restriction allows tools to fail early on invalid \code{main}
methods, without needing to know whether a library will be used as the entry
point of a Dart program. It is possible that this restriction will be removed
in the future.}
```

**Comment by natebosch** [comment] 2020-07-28 23:12
> That's not quite true (at least per spec)

Maybe I misunderstood the scope of this issue? If "static error" means "error reported by a backend" and not "error reported by the analyzer or CFE" then I don't have any concerns.

**Comment by leafpetersen** [comment] 2020-07-28 23:22
> Maybe I misunderstood the scope of this issue? If "static error" means "error reported by a backend" and not "error reported by the analyzer or CFE" then I don't have any concerns.

No, it means the latter.  Runtime error means the former.  I believe that the spec above implies that this program is a static (CFE/analyzer) error:

```dart
void main(int x, int y, int z) {
  x.isEven;
}
```

No such error is, in fact reported.  So the implementations are missing some specified static errors.  I also believe that the above text does *not* imply that the original program should have a runtime error.  But the implementations do in fact report one.  Consequently, the implementations are also implementing **additional** runtime checks beyond what are specified (fortunately).

Both of the above issues should be resolved.  Agreed that if we resolve them by adding compile time errors then it is a breaking change which needs to be guarded by a language version.

**Comment by natebosch** [comment] 2020-07-28 23:28
The spec quote refers to `A script $S$ is executed as follows:` and I understand it to be limited to rules for the libraries that _are_ executed. It does not apply to _all_ libraries.

As per my understanding of the spec (and the behavior of existing tools) the following is a valid Dart library:

```dart
void main(int x, int y, int x) => x.isEven;
```

And here is a valid script that can be executed:

```dart
import 'that_other_file.dart' as other;

void main() {
  print(other.main(1,2,3));
}
```

**Comment by leafpetersen** [comment] 2020-07-28 23:38
@natebosch I can't reconcile with what you are saying with the two pieces quoted below.  The first is commentary and not normative, so it's possible that it's incorrect, but assuming not, I don't see any way to read these as saying anything other than that: "if you have a declaration named `main` you are not a script it's a compile time error" (this is normative) and "if you have main with more than two positional arguments you're not a script" (this is commentary).  If the latter is correct, then the former implies your first example is specified to be compile time error.

> \commentary{
> Note that if \code{main} requires more than two positional arguments,
> the library is not considered a script.
> }



> It is a compile-time error if a library's export scope contains a declaration
> named \code{main}, and the library is not a script.

**Comment by natebosch** [comment] 2020-07-28 23:41
Ah, I missed the second part there.

> It is a compile-time error if a library's export scope contains a declaration
> named \code{main}, and the library is not a script.

Neither the CFE nor analyzer has ever enforced this as far as I can tell. I would bet that there is code that _would_ be broken if we started enforcing it.

**Comment by lrhn** [comment] 2020-07-29 07:52
The rule was introduced at the request of Peter because modular compilation cannot know whether a file is used as a script or not, and the parser output needed a way to designate the `main` method of a library, and whether it is valid or not. I don't remember the exact details of why things had to be this way, it was probably for historical reasons, but after some discussion we ended up with the current specification. Maybe it was just because it meant that you couldn't give a good error message if someone wrote a wrong `main`, because you couldn't know whether it was going to be used as an entry point or not.
Maybe @eernstg remembers more?

I had assumed that Fasta would implement the spec. (Could it be that the error is recorded in the parser output, but that is ignored by later steps?). 


What I would personally prefer is a compile-time error if an *entry point* library does not export a *function declaration* with a signature assignable to one of `void Function()`, `void Function(List<String>)` or `void Function(List<String>, Object?)`.
We could be lenient and dynamic and allow `void Function(List<String>, Never)` for the last one, so that you can type the object that you send with `Isolate.spawnUri` as what it is (and fail dynamically if it isn't, but if the alternative is an immediate `value as ExpectedType`, then it's going to fail anyway).

**Comment by natebosch** [comment] 2020-07-29 15:05
> What I would personally prefer is a compile-time error if an _entry point_ library does not export a _function declaration_ with a signature assignable to one of `void Function()`, `void Function(List<String>)` or `void Function(List<String>, Object?)`.

Our web compilers will never pass "real" arguments through. Should we consider allowing the web compilers to make it an error to use a function that isn't assignable to `void Function()` and disallow the others?

**Comment by rakudrama** [comment] 2020-07-30 01:40
Some customers use dart2js code from node.js, so we should not break them by prohibiting passing parameters to `main`.

I know Sass uses dart2js in this way. They have an primary entry point (`main`) which takes an argument and works from the VM, and a second `main` with no arguments which wraps the primary `main` with js-interop to export the primary `main` as a method of an npm module. This method is called many times by the node.js build app in which the Dart app is embedded.

Unminified output from dart2js has had this comment for many years, so who knows how many other user do something similar:
```
// The code supports the following hooks:
...
// dartMainRunner(main, args):
//    if this function is defined, the Dart [main] method will not be invoked
//    directly. Instead, a closure that will invoke [main], and its arguments
//    [args] is passed to [dartMainRunner].
```

It is very difficult for JavaScript app to call the entry point correctly since it is an internal detail of the Dart app as to what exactly will pass as a `List<String>`. Sass exports a closure similar to this:
```dart
allowInterop((dynamic args) => primary.main(List<String>.from(args as List<dynamic>)));
```
This works because Sass is called with the obvious JavaScript `Array` and DDC and dart2js recognize a JavaScript `Array` as a `List<dynamic>`.

I propose:
- Web compilers permit all specified versions of `main`.
- For `main()`, nothing extra needs to be done, so there is no impact in web apps.
- For other forms of `main`, web compilers inject code into main before any checks to 'upgrade' the first input to a valid `List<String>`. We don't have to call `List.from`, and I think it would be reasonable to take the short-cut of assuming the elements of the Array are strings.

For example, dart2js might inject this code into `main`:
```js
if (args == null) args = [];
if (Array.isArray(args)) args = H.setArrayType(Array.prototype.slice.call(array), type$.JSArray_String);
```
This would handle an inadvertent `null` or `undefined` and not drag in any code that is not already present in non-trivial apps.

**Comment by leafpetersen** [comment] 2020-07-30 04:54
@rakudrama my initial though was just to specify that main is invoked dynamically (hence, you can put whatever the hell you want on it as the type annotations, and so long as a dynamic call to it with whatever the compiler chooses to pass in works, you're good).  Does that not have the properties you want?

**Comment by natebosch** [comment] 2020-07-30 16:42
> Some customers use dart2js code from node.js, so we should not break them by prohibiting passing parameters to `main`.

Does dart2js support that today? When you compile with dart2js for node and use the node preamble, does it support passing arguments through?

> They have an primary entry point (`main`) which takes an argument and works from the VM, and a second `main` with no arguments which wraps the primary `main` with js-interop to export the primary `main` as a method of an npm module.

As long as we only enforce this restriction on the entrypoint which is _used_ this won't affect that use case. Whatever decision we make on restrictions around top-level symbols named `main` I would propose that additional restrictions imposed by the web compilers would _not_ apply to all `main`, and would only apply to to the one that is used.

> * For other forms of `main`, web compilers inject code into main before any checks to 'upgrade' the first input to a valid `List<String>`. We don't have to call `List.from`, and I think it would be reasonable to take the short-cut of assuming the elements of the Array are strings.

I don't understand this. What is the purpose of having a compiler hardcoded to always pass an empty list? As a user I would strongly prefer if it was made statically clear to me that I will never get a "real" value to my `main` from the compiler than if I was just given an empty list no matter what.

**Comment by rakudrama** [comment] 2020-08-04 04:45
@leafpetersen
I'm not keen on allowing any signature other than `void Function()` and `void Function(List<String>)`.
I'm not actually sure how `void Function(List<String>, Object?)` is used.

If we want to permit a parameter to be typed `List<String>` then we need to inject some conversion code because there is no JavaScript object that can be created outside of the program that `is` this type.
I want to limit the number of conversions as much as possible, which is why I would restrict the types of the parameters.
An alternative to conversion is to treat external JavaScript Arrays as `List<any>` or `List<erased>` where `any`/`erased` are treated like Dart 1 `dynamic`. We have not yet proven out this idea, but it looks promising for making js-interop less painful.

I'm not keen on making the invocation a full dynamic call. Within a dart2js compiled program, a dynamic call requires using the right selector, which is not available outside the program. For js-interop this is handled by a conversion which essentially calls `Function.apply`. This pulls in a lot of code for a program that does not otherwise use js-interop or `Function.apply`.

Making the invocation of `main` a dynamic call does not fix any problems with the arguments that require conversion.
I suppose one could write a `main` that works for DartVM and Dart/JS like this:
```dart
void main(Object? externalArgs) {
  List<String> args = List<String>.from(externalArgs as Iterable);
  ...
}
```
This feels artificial for the VM, but if you think it is reasonable to change 'portable' programs to work this way (i.e. pushing the responsibility for conversion on the author) then it could work.
This would require permitting `Object?` for the first argument, but not requiring a full dynamic call.

@natebosch 
`dartMainRunner` can pass whatever it likes to `main`.
For example, preprending this code would allow the d8 shell to forward its [command line arguments](https://v8.dev/docs/d8#pass-flags-into-javascript):
```js
let _dartArgs = arguments;
function dartMainRunner(callMain, _unused_stupid_empty_args) {
  callMain(_dartArgs);
}
```
We could tweak `js_runtime/lib/preambles/d8.js` to work like this.
This might also be useful for a web page that is not a Dart app, but just contains a Dart app.

**Comment by leafpetersen** [comment] 2020-08-04 23:51
Summarizing from discussion today.

**Background**

The specified restrictions are almost universally ignored by implementations.

There is an underlying soundness issue as documented as above, which must be resolved.  As usual, embedders (including dartMainRunner) are capable of violating soundness arbitrarily.  But for standard usage, if a user write `main(int x)` then either they must receive a valid integer argument, or they must get a static error, or they must get a dynamic error when main is called.

There are existing use cases where odd signatures in the flutter ecosystem that are ascribed to a function called main, but it's not clear if they are actually used as entry points or not. 

There are existing use cases where the same `main` function is used as an entry point, or is invoked internally to an app.

There are existing use cases where a single `main` function is used on the web and and on the VM.

Determining whether a file is an entry point or not at compile time is not easily done in our existing build systems.

**Discussion**

@rakudrama is concerned about the cost of supporting arbitrary function signatures with dynamic checks.  

@natebosch would prefer to limit the set of function signatures accepted on the web platforms to those which can be realistically satisfied (e.g. specifically not `main(List<String> x)` which entails that an empty list would always be passed.

A minimal proposal from @leafpetersen is as follows:
  - What libraries are treated as scripts is implementation defined.
  - A is subject to the following additional errors.  It is implementation defined whether these errors are reported at compile time, at link time, or at run time.
     - It is an error if a script contains no top level symbol named `main`
     - It is an error if a script contains a top level symbol named `main` which is not a static top level method
     - It is an error if a script contains a top level symbol named `main` which has a signature which is not a subtype of one of an implementation defined set of supported signatures
       - Subject to the restriction that at a minimum the signature `void main([List<String>? args, Object? extra])` shall be accepted


cc @natebosch @sigmundch @rakudrama @lrhn @munificent @eernstg @jakemac53

**Comment by eernstg** [comment] 2020-08-06 10:28
### What we currently specify

The spec is actually a bit stricter than the discussion so far implies. In relation to the following program

```dart
void main(int x) {
  x.isEven;
}
```

@leafpetersen wrote:

> I also believe that the above text does not imply that the original
> program should have a runtime error. But the implementations do
> in fact report one. Consequently, the implementations are also
> implementing additional runtime checks beyond what are specified (fortunately).

The dynamic error caused by an invocation of a `void main(int)` where a `List<String>` is passed as the actual argument is [specified](https://github.com/dart-lang/language/blob/d23e64e05f7e51c17b9cfbf0382cbc55a7d2c118/specification/dartLangSpec.tex#L10692) as a property of function invocations, there is nothing special about `main`, nor about the initial invocation of `main`. So there shouldn't be a need to mention these dynamic checks in section 'Scripts'.

With respect to the need to avoid a fully general dynamic invocation, it should help that `void main()` and `void main(args)` and `void main(List<String> args)` are common signatures, and they would at most require a dynamic type check of the form `is List<String>`. Wouldn't that suffice to make the specification suitably implementation-friendly?

But I agree that it would be very good if we could report some or all of these errors statically, and that's not covered by the current spec.

> \commentary{
> Note that if \code{main} requires more than two positional arguments,
> the library is not considered a script.
> }

This is commentary because it is a direct consequence of the first paragraph in 'Scripts'.

@natebosch wrote:
> the following is a valid Dart library:

```dart
void main(int x, int y, int x) => x.isEven;
```

This is specified as an error: The library is not a script, and it's an error for a non-script to have a top-level declaration named `main`.

Considering that `main` is widely used :smile: &nbsp;and that we might well want to emit some compile-time errors about declarations of `main` with a non-conforming signature, I'm tempted to suggest that we keep at least as much information about `main` in the specification as we have today. It would be an anomaly to emit compile-time errors for unspecified reasons.

#### Proposal

We update the 'Scripts' section to allow optional positional parameters (following the actual behavior of tools):

> A _script_ is a library whose exported namespace includes
> a top-level function declaration named `main` that has at most
> two required positional arguments.

We add a rule that makes certain parameter types an error, at the end of the section:

> Let _L_ be a script where _D_ is the top-level function declaration
> named `main`. If _D_ declares at least one positional argument, it is
> a compile-time error if the first positional argument has a type _T_
> such that `List<String>` is not a subtype of _T_.

We could add a constraint on the return type, but that does not seem to play a role and it may introduce unnecessary breakage:

> It is a compile-time error if _D_ has a return type which is not
> `void` or `dynamic`.

Finally, we give implementations the freedom to reject whatever they want (avoiding the phrase 'compile-time error' because that's a specified thing):

> An implementation is free to reject processing a script during compilation or at
> run time, based on implementation specific constraints on the allowed signatures
> of `main`.
>
> *This is similar to having additional compile-time errors and dynamic errors,
> but those errors are not specified in this document, and they are restricted
> to be concerned with the signature of `main`.*

#### Discussion

This proposal matches @leafpetersen's proposal pretty closely, except that we continue to specify more things:

> What libraries are treated as scripts is implementation defined.

This proposal keeps it as a specified property of a library whether it's a script, but the broadened definition of a script allows for declarations with headers like `void main(args, int i, [int j])` and `void main(List<String>? args, {int named = 3})` which are currently allowed by implementations.

> A is subject to the following additional errors. It is implementation
> defined whether these errors are reported at compile time, at link
> time, or at run time.

I believe the required degree of freedom for implementations is ensured by the clause at the end allowing implementations to "reject" the processing of a script.

We do require compile-time errors for a parameter type of `int` as in `void main(int x)`, but that should be helpful, even if it is a breaking change to get it implemented.

> It is an error if a script contains no top level symbol named `main`

With this proposal (and the current spec) that library is not a script, so it is vacuously enforced.

It is an implementation specific property what a tool like `dart` will do if it is running a non-script.

> It is an error if a script contains a top level symbol named `main`
> which is not a static top level method

Same error exists with the current specification, but in _every_ library. This is not currently enforced. Would it be too breaking to do that?

As @lrhn mentioned, this error was introduced in order to allow modular compilation: A compiled version of a set of libraries can be linked together. Every `main` in the resulting executable is guaranteed to satisfy the requirements on the `main` that will be called to start the program, so it is not necessary to know at compile time whether a specific script will have its `main` used as the entry point.

> It is an error if a script contains a top level symbol named `main`
> which has a signature which is not a subtype of one of an
> implementation defined set of supported signatures
> Subject to the restriction that at a minimum the signature
> `void main([List<String>? args, Object? extra])` shall be accepted

This proposal says 'at most two required positional arguments', where the first one must have a type which is a supertype of `List<String>`, but it allows implementations to reject anything. However, this proposal assumes a best effort by implementations, which should imply that any "reasonable" signature is accepted.

**Comment by lrhn** [comment] 2020-08-06 11:08
@leafpetersen wrote:

> What libraries are treated as scripts is implementation defined.
> A is subject to the following additional errors. It is implementation defined whether these errors are reported at compile time, > at link time, or at run time.
> It is an error if a script contains no top level symbol named main
> It is an error if a script contains a top level symbol named main which is not a static top level method
> It is an error if a script contains a top level symbol named main which has a signature which is not a subtype of one of an implementation defined set of supported signatures
> Subject to the restriction that at a minimum the signature void main([List<String>? args, Object? extra]) shall be accepted

This confuses me, because "script" is not defined.

Maybe just start with:
> Dart compilation may designate some libraries as *script*s.

Accepting `main([List<String>? args, Object? extra])` is not a sufficient requirement. It can be trivially satisfied by having that signature itself in the set of supported signatures, but then we still won't accept `main()` or `main(List<String>)`.
Just say that `void Function()` and `void Function(List<String>)` must be in the set, and then consider whether to add `void Function(List<String>, Object?)` or `void Function(List<String>, Never)`.

I think Erik has covered most of my concerns with his proposal (including that it's the exported namespace that matters, not the declarations).

**Comment by leafpetersen** [comment] 2020-08-06 18:09
> Just say that `void Function()` and `void Function(List<String>)`

The object that has been raised to this is that the latter will never actually be a non-empty list on the web, which is both confusing to users and requires additional code to be inserted to build a useless empty list.  The desire from (at least some parts of) the web team is explicitly to disallow the latter.

**Comment by leafpetersen** [comment] 2020-08-06 18:22
@eernstg and I discussed this earlier today.  Here is my summary of my understanding of his proposal (re-phrased to eliminate the existing confusing circumlocutions of the previous specification language).

First, all existing terminology around scripts and main is deleted.

Second, text covering the following restrictions is added:

- Any symbol in the exported namespace of a library with the name `main` is subject to the following restrictions:
  - It is an error if there are more than two required positional parameters
  - It is an error if there is at least one positional parameter and and the first positional parameter has a type which is not a supertype of `List<String>`
- Implementations are responsible for choosing some exported symbol from some exported library to use as an entry point
- Implementations are free to impose any additional restrictions on the signature of the symbol chosen for use as an entry point
- Implementations are responsible for ensuring (statically or dynamically) that any symbol chosen for use as an entry point is invoked with arguments that are type compatible with the signature of the entry point.

 @eernstg do you agree with this summary?

**Comment by leafpetersen** [comment] 2020-08-06 18:24
I'm fine with the proposal from @eernstg but I'll make the following observations:

- This means from a specification standpoint, there is no signature whatsoever that is guaranteed to work on more than one implementation.
- It's not clear to me why, given this, we limit the number of positional parameters to two.  Why not allow more?  The spec allows unlimited named parameters (required or optional) and unlimited optional positional parameters, so why restrict the positionals?

**Comment by lrhn** [comment] 2020-08-07 07:28
>> Just say that `void Function()` and `void Function(List<String>)` must be in the set
>
> The objection that has been raised to this is that the latter will never actually be a non-empty list on the web, which is both > confusing to users and requires additional code to be inserted to build a useless empty list. The desire from (at least some parts of) the web team is explicitly to disallow the latter.

I'd be very annoyed if I couldn't write a script that accepts a `List<String>` and run it on both VM and dart2js.
Sure, I can't provide arguments when compiling with dart2js, but I should still be able to run the code.
(Or, if I run with node.js, there is a way to get the command line arguments, and we should probably support that).

It's very obvious statically whether an empty list is needed or not, so I don't worry too much about the compiler complexity.

**Comment by natebosch** [comment] 2020-08-07 16:32
> I'd be very annoyed if I couldn't write a script that accepts a `List<String>` and run it on both VM and dart2js.

My opinion is that this should be written as `void main([List<String>? args])` so that the code is explicit about _how_ it supports both cases. My understanding is that supporting or requiring this with `dart2js` might be more challenging than it's worth.

If we are unable to restrict to no arguments on the web I agree with the rest of the proposal. I do think it would be worthwhile to scan packages on pub and check if any will be broken.

**Comment by eernstg** [comment] 2020-08-07 19:23
@leafpetersen wrote:
> do you agree with this summary?

Yes, that's a nice and clean way to say it.

We could adjust '(statically or dynamically)' to '(by rejecting the program at compile-time or link time, or by raising a dynamic error)', in order to make it obvious that the embedder isn't required to come up with a value of type `Qux` just because it encounters `void main(List<String> args, Qux extra)`.

Also, if null safety is enabled then we need to say that there cannot be any required named parameters.

> there is no signature whatsoever that is guaranteed to work
> on more than one implementation

Right, 'Implementations are free to impose any additional restrictions' allows an implementation to reject anything it wants, so there is no signature which is guaranteed to work on _any_ implementation. But I think we can rely on good will in this case: It is definitely not the intention that this clause should be used to reject a lot of well-known and actively used signatures.

Apart from that clause, I think the door is open for the obvious "reasonable" signatures:

`T main()` should work for all `T`. The dynamic semantics specifies that it will be invoked with no arguments, and the clause at the end does not allow the implementation to reject this invocation, because there are no arguments that could have a wrong type.

With `T main(List<String> args)` for any `T` (and variants of the form `T main(S args)` where `List<String> <: S`), and a specification of the dynamic semantics which says that a `List<String>` will be passed, we should also be OK.

Finally, as @lrhn mentioned, `T main(List<String> args, SomeType extra)` should work, and there should be a dynamic check on the run-time type of the `extra` argument.

I think this should be sufficient to handle the most typical cases.

> why, given this, we limit the number of positional parameters to two

We only require that there are no more than two _required_ positional parameters, it's not a problem if `main` accepts 17 positional parameters as long as 15 or more of them are optional.

The reason why I've proposed these constraints is that the dynamic semantics will definitely fail in the case where it makes an attempt to invoke a `main` that has more than two required positional parameters and/or any required named parameters.

@lrhn wrote, about the signatures that we'd expect to be able to used:
> I did assume that Erik's proposal would retain that, but I can see that
> it wasn't written explicitly.

I think the signatures that you mention are covered, as argued above. Do you agree?

@natebosch wrote:
> My opinion is that this should be written as 
> `void main([List<String>? args])` so that the code is explicit
> about how it supports both cases

The reason why I did not go in this direction is that `void main()` and `void main(List<String> args)` and `void main(List<String> args, SomeType extra)` do not have "nice" relationships with `void main([List<String>? args])`:

`void Function([List<String>?])` is a subtype of `void Function()` and `void Function(List<String>)`, but there are other supertypes that we don't want to imply support for, e.g., `void Function(List<Never>?)`.

And `void Function(List<String>, SomeType)` is simply unrelated to `void Function([List<String>?])`.

So we can't just say that `main` should have a type which is a supertype of `void Function([List<String>?])`. Of course, it also won't work to say that it must be a subtype.

So what is the requirement, if it is not a subtype relationship?

**Comment by natebosch** [comment] 2020-08-07 20:10
> So we can't just say that `main` should have a type which is a supertype of `void Function([List<String>?])`. Of course, it also won't work to say that it must be a subtype.

I don't have a specific proposal for how to specify this. My hope was that the web compilers could reject any `main` that can't be called with zero arguments. This shifts confusion from runtime ("Why is this list empty when I passed arguments to d8?") to compile time - the compiler warns you that it won't give arguments to `main` and requires that main is a function that can be called with 0 arguments.

**Comment by eernstg** [comment] 2020-08-07 22:54
That should be covered:

> Implementations are free to impose any additional restrictions on the signature of the
> symbol chosen for use as an entry point

I think it's fair to say that a web compiler can use that clause to justify rejecting `void main(List<String> args) {...}`. I noticed that @lrhn would prefer to _allow_ that signature, which is of course also possible. I have no strong opinions about whether it's more important to be able to avoid having two entry points just so one of them can have a `main` with one argument and the other takes zero arguments, or it's more important to avoid the confusion about passing arguments to `d8`.

**Comment by rakudrama** [comment] 2020-08-07 23:17
Can we not resolve the surprise "Why is this list empty when I passed arguments to d8?" by passing the command line arguments? d8 is not the web, but it is central to a lot of our testing and benchmarking.

Would there be any surprise if an entry declared as `main(List<String> args)` but `args` is always empty in these contexts?
- _when running on a web page in a browser_
- _when running on a worker in a browser_

**Comment by natebosch** [comment] 2020-08-07 23:40
> Can we not resolve the surprise "Why is this list empty when I passed arguments to d8?" by passing the command line arguments? d8 is not the web, but it is central to a lot of our testing and benchmarking.

Probably, but it introduces magic that would fail in other places. Would we do the same for node? JavaScript shell? Others?

If we do decide to support args for `d8` I would hope that we can make sure it's only included when explicitly needed. Maybe with a new flag? In either case, I'm worried that I've derailed the original conversation. There has been a lot of confusion in this thread... Maybe we can shift the conversation elsewhere?

**Comment by rakudrama** [comment] 2020-08-08 01:14
> If we do decide to support args for d8 I would hope that we can make sure it's only included when explicitly needed. Maybe with a new flag? In either case, I'm worried that I've derailed the original conversation. There has been a lot of confusion in this thread... Maybe we can shift the conversation elsewhere?

I don't think a flag is necessary.

The compilers will expose a JavaScript entry point that calls `main`.

Most genuine web apps use `main()`, and that signature can be handled with minimal code. The JavaScript entry point ignores all arguments and calls `main`. It is likely that we can just use `main` directly and rely on the JavaScript calling convention dropping unused arguments. This is what we do today, which is sound for `main()`.

If the signature is `main(List<String> args)`, then the JavaScript entry point converts a JavaScript Array-like first argument into a Dart `List<String>`, and then calls `main` with the converted value. The conversion ensures all elements of the list are Strings via the JavaScript conversion expression `String(x)`. If you don't like the extra code, compile the production web app via a different `main`. Since we have this magic JavaScript entry function that calls `main`, I want to limit the magic to just these two cases. 

I don't want `main` to have optional arguments because then the JavaScript entry function has to determine the intent of its caller, and then do the right thing to provide a default value.

To circle back to the original issue, I think the Dart/JS compilers should accept two or three signatures and ensure they are called in sound way:
- `main()`
- `main(List<String> args)`
- possibly `main(List<String> args, Object? extra)`

The spec should permit this restriction. Exactly these signatures (parameter names can change). No optionals since we can't be sure of caller intent. No supertypes since we don't know how to convert the elements of a `List<Something>`. No subtypes since we then have to check unconverted values.

---
As a developer, you are on your own interpreting `extra`. You might think you passed a `Quux` to `spawnUri` but it looks like a random JavaScriptObject.

We do the conversion magic for `args`. We fix the code in `js_runtime/lib/preables/`, which uses `dartMainRunner`, to pass through a JavaScript Array-like to the JavaScript entry point so it can be converted to a Dart List when `List<String>` is accepted.

A serious production web app will use `main()` and pay no cost.

**Comment by eernstg** [comment] 2020-08-12 10:35
I've created a [PR proposing new rules about `main` for null-safety](https://github.com/dart-lang/language/pull/1146), and invited reviews from everybody here.

**Comment by eernstg** [comment] 2020-08-12 13:07
@rakudrama wrote:
> the Dart/JS compilers should accept two or three signatures
> and ensure they are called in sound way:
>
> - `main()`
> - `main(List<String> args)`
> - possibly `main(List<String> args, Object? extra)`

This is supported by the [PR I mentioned](https://github.com/dart-lang/language/pull/1146):

An implementation can have arbitrary extra constraints on the allowed signatures of `main`, and in particular it can allow exactly these three (or the first two, if preferred).

They will be called safely: The first positional argument is specified to be an instance of a subtype of `List<String>`, and each variant will be called with exactly the same number of actual arguments as the number of declared parameters.

**Comment by eernstg** [comment] 2020-08-20 16:15
Closing: The PR https://github.com/dart-lang/language/pull/1146 updates the spec, and there is no need to change the implementation of any tool.

**Closed by eernstg** 2020-08-20 16:15 UTC
Labels: nnbd
